// ==UserScript==
// @name         SakaLuX Suite [EXPERIMENTAL]
// @namespace    sakalux.suite
// @version      0.2.0
// @description  Experimental modular master control for the SakaLuX Torn suite with internal Quality of Life modules.
// @author       SakaLuX [2380374]
// @match        https://www.torn.com/*
// @grant        none
// @license      MIT
// @run-at       document-end
// ==/UserScript==

(() => {
'use strict';
const VERSION='0.2.0';
const IDS={fallback:'slx-suite-button',native:'slx-suite-native-button',overlay:'slx-suite-overlay',style:'slx-suite-style'};
const K={modules:'SakaLuX_SUITE_MODULES_V1',api:'SakaLuX_SUITE_TORN_API_KEY',prayer:'SakaLuX_SUITE_PRAYER_DAY'};
const MODULES=[
{id:'prayer',name:'Prayer Reminder',icon:'🙏',cat:'Quality of Life',desc:'Daily prayer reminder that stays hidden after you mark today as prayed.',kind:'internal',enabled:false},
{id:'med-advisor',name:'Med Advisor',icon:'🩹',cat:'Quality of Life',desc:'Quick medical-item recommendation from the life values currently visible in Torn.',kind:'internal',enabled:false},
{id:'item-intel',name:'Item Intel',icon:'🔎',cat:'Quality of Life',desc:'Adds compact purpose markers to useful items on the Items page.',kind:'internal',enabled:false},
{id:'event-intel',name:'Event Intel',icon:'📋',cat:'Quality of Life',desc:'Adds a compact searchable event helper on Torn Events pages.',kind:'internal',enabled:false},
{id:'enhancer',name:'Enhancer Guard',icon:'🛡️',cat:'Inventory',desc:'Enhancer inventory tracker and missing-item intelligence.',global:'SakaLuXEnhancerGuard',button:'#sl-eg-button',kind:'bridge',enabled:true},
{id:'bazaar',name:'Bazaar Thanker',icon:'💬',cat:'Trading',desc:'Buyer grouping, thank-you messages, statistics and history.',global:'SakaLuXBazaarThanker',button:'#sakalux-bt-settings-button',kind:'bridge',enabled:true},
{id:'market',name:'Market Intelligence',icon:'📈',cat:'Trading',desc:'Travel, Bazaar, Item Market, Museum and basket optimization.',global:'SakaLuXMarketIntelligence',button:'#sl-mi-button',kind:'bridge',enabled:true},
{id:'missions',name:'Mission Rewards',icon:'🎯',cat:'Missions',desc:'Mission Shop values, ammo ownership and mod intelligence.',global:'SakaLuXMissionRewards',button:'#sl-mri-button',kind:'bridge',enabled:true},
{id:'elimination',name:'Elimination Assistant',icon:'⚔️',cat:'Combat',desc:'Eliminations target scoring, FF/BS estimates and learning.',global:'SakaLuXEliminationAssistant',button:'#slx-elim-btn',kind:'bridge',enabled:false}
];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let state=load(K.modules,{}),apiKey=localStorage.getItem(K.api)||'';
for(const m of MODULES)if(typeof state[m.id]!=='boolean')state[m.id]=m.enabled;save(K.modules,state);

function api(m){try{return m.global?window[m.global]||null:null}catch{return null}}
function ready(m){if(m.kind==='internal')return true;return!!(api(m)||document.querySelector(m.button))}
function version(m){if(m.kind==='internal')return VERSION;try{return String(api(m)?.version||api(m)?.health?.()?.version||'')}catch{return''}}
function todayUtc(){return new Date().toISOString().slice(0,10)}
function routeText(){return (location.pathname+' '+location.search+' '+location.hash).toLowerCase()}

function css(){if(document.getElementById(IDS.style))return;const s=document.createElement('style');s.id=IDS.style;s.textContent=`
#${IDS.fallback}{position:fixed;right:12px;bottom:88px;z-index:2147483645;width:52px;height:52px;border-radius:50%;border:1px solid #b78b34;background:#171717;color:#e2b34b;font-size:24px;font-weight:900;box-shadow:0 5px 20px #0009}
#${IDS.native}{cursor:pointer!important;-webkit-tap-highlight-color:transparent!important}#${IDS.native} .slxs-skull{display:flex;align-items:center;justify-content:center;font-size:24px;line-height:1;color:#e2b34b!important;min-width:28px;min-height:28px}
#${IDS.overlay}{position:fixed;inset:0;z-index:2147483647;background:#000b;display:flex;align-items:flex-end;justify-content:center;font-family:Arial,sans-serif}
.slxs-panel{width:min(720px,100%);max-height:94vh;display:flex;flex-direction:column;overflow:hidden;background:#111318;color:#f3f4f6;border:1px solid #7c6233;border-radius:20px 20px 0 0;box-shadow:0 -12px 45px #000c}.slxs-head{padding:16px 18px;border-bottom:1px solid #30333a;flex:none}.slxs-row{display:flex;gap:10px;align-items:flex-start}.slxs-grow{flex:1}.slxs-kicker{font-size:10px;letter-spacing:3px;color:#e8bf67;font-weight:900}.slxs-title{font-size:21px;font-weight:900;margin-top:5px}.slxs-sub{font-size:11px;color:#9ca3af;margin-top:5px;line-height:1.45}.slxs-close{width:38px;height:38px;border:1px solid #3b414c;border-radius:10px;background:#252933;color:#fff;font-size:21px}
.slxs-scroll{overflow-y:auto;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;flex:1;min-height:0}.slxs-tools{padding:12px 16px;border-bottom:1px solid #2d3139;display:grid;grid-template-columns:1fr 1fr;gap:8px}.slxs-tool{border:1px solid #3a414d;background:#20242d;color:#fff;border-radius:10px;padding:10px;font-size:11px;font-weight:900}.slxs-api{margin:12px 16px;padding:14px;border:1px solid #5f5131;border-radius:14px;background:#17191f}.slxs-api h4,.slxs-cat h4{margin:0;color:#e8bf67;font-size:10px;letter-spacing:2px}.slxs-note{font-size:10px;color:#8e949f;margin-top:5px;line-height:1.4}.slxs-apirow{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.slxs-api input{min-width:0;background:#101218;color:#fff;border:1px solid #353b46;border-radius:9px;padding:10px}.slxs-api button{border:0;border-radius:9px;background:#d5a63e;color:#17120a;font-weight:900;padding:0 16px}
.slxs-body{padding:0 16px 16px}.slxs-cat{margin-top:12px;border:1px solid #2d3139;border-radius:14px;overflow:hidden;background:#15181e}.slxs-cat h4{padding:11px 14px;border-bottom:1px solid #2d3139}.slxs-mod{display:grid;grid-template-columns:1fr auto;gap:10px;padding:13px 14px;border-bottom:1px solid #282c33}.slxs-mod:last-child{border-bottom:0}.slxs-name{font-size:14px;font-weight:900}.slxs-meta{font-size:10px;color:#9298a3;line-height:1.45;margin-top:5px}.slxs-badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.slxs-badge{font-size:8px;font-weight:900;border:1px solid #3e4653;border-radius:999px;padding:3px 7px}.ready{border-color:#2d7654!important;color:#8ee5b4}.off{border-color:#7d3447!important;color:#ff9bb3}.bridge{border-color:#75622e!important;color:#e8bf67}.slxs-actions{display:flex;flex-direction:column;gap:7px;align-items:flex-end}.slxs-toggle{min-width:78px;border-radius:999px;padding:8px 12px;border:1px solid #7d3447;background:#411c28;color:#ffb3c4;font-size:10px;font-weight:900}.slxs-toggle.on{border-color:#2d7654;background:#183b2c;color:#9bf0bd}.slxs-open{border:1px solid #3a414d;background:#242a34;color:#fff;border-radius:8px;padding:7px 10px;font-size:9px;font-weight:900}.slxs-open:disabled{opacity:.35}.slxs-foot{padding:11px 16px;border-top:1px solid #2d3139;background:#0e1014;color:#7f8590;font-size:9px;display:flex;justify-content:space-between;flex:none}
#slxs-prayer{position:fixed;right:16px;bottom:148px;z-index:2147483600;border:1px solid #99742c;background:#171717;color:#f2c35e;border-radius:999px;padding:9px 12px;font-weight:900;font-size:12px;box-shadow:0 4px 18px #0008}#slxs-med{position:fixed;right:16px;bottom:194px;z-index:2147483599;border:1px solid #39785b;background:#17231d;color:#9ef1be;border-radius:999px;padding:9px 12px;font-weight:900;font-size:11px;box-shadow:0 4px 18px #0008}
.slxs-item-tag{display:inline-block;margin-left:6px;padding:2px 5px;border-radius:5px;border:1px solid #6b5730;color:#e8bf67;font-size:9px;font-weight:900;vertical-align:middle}.slxs-event-panel{margin:10px 0;padding:10px;border:1px solid #6b5730;border-radius:10px;background:#15181e;color:#eee}.slxs-event-panel input{width:100%;box-sizing:border-box;background:#0f1116;border:1px solid #363c46;color:#fff;border-radius:8px;padding:8px}.slxs-event-stats{font-size:10px;color:#aaa;margin-top:7px}
@media(min-width:700px){#${IDS.overlay}{align-items:center}.slxs-panel{border-radius:20px;max-height:88vh}.slxs-tools{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(s)}

function close(){document.getElementById(IDS.overlay)?.remove()}
function card(m){const on=!!state[m.id],r=ready(m),v=version(m),internal=m.kind==='internal';return`<div class="slxs-mod"><div><div class="slxs-name">${m.icon} ${esc(m.name)}</div><div class="slxs-meta">${esc(m.desc)}</div><div class="slxs-badges"><span class="slxs-badge ${on?(r?'ready':'bridge'):'off'}">${on?(r?'READY':'WAITING'):'OFF'}</span><span class="slxs-badge ${internal?'ready':'bridge'}">${internal?'INTERNAL':'BRIDGE'}</span>${v?`<span class="slxs-badge ready">v${esc(v)}</span>`:''}</div></div><div class="slxs-actions"><button class="slxs-toggle ${on?'on':''}" data-toggle="${m.id}">${on?'ON':'OFF'}</button><button class="slxs-open" data-open="${m.id}" ${on&&r?'':'disabled'}>${internal?'RUN':'OPEN'}</button></div></div>`}
function open(){close();const o=document.createElement('div');o.id=IDS.overlay;const cats=[...new Set(MODULES.map(m=>m.cat))];o.innerHTML=`<div class="slxs-panel"><div class="slxs-head"><div class="slxs-row"><div class="slxs-grow"><div class="slxs-kicker">MASTER CONTROL • EXPERIMENTAL</div><div class="slxs-title">☠ SakaLuX Suite</div><div class="slxs-sub">One installation target. Enable only the modules you use. Existing standalone scripts remain untouched.</div></div><button class="slxs-close" id="slxs-close">×</button></div></div><div class="slxs-scroll"><div class="slxs-tools"><button class="slxs-tool" id="slxs-enable">ENABLE READY</button><button class="slxs-tool" id="slxs-disable">DISABLE ALL</button><button class="slxs-tool" id="slxs-export">EXPORT SETTINGS</button><button class="slxs-tool" id="slxs-import">IMPORT SETTINGS</button></div><div class="slxs-api"><h4>SHARED TORN API KEY</h4><div class="slxs-note">Stored only in this browser and excluded from exported Suite settings.</div><div class="slxs-apirow"><input id="slxs-key" type="password" autocomplete="off" placeholder="Enter your Torn API key" value="${esc(apiKey)}"><button id="slxs-save">SAVE KEY</button></div></div><div class="slxs-body">${cats.map(c=>`<div class="slxs-cat"><h4>${esc(c.toUpperCase())}</h4>${MODULES.filter(m=>m.cat===c).map(card).join('')}</div>`).join('')}</div></div><div class="slxs-foot"><span>Active build: v${VERSION}</span><span>QOL MODULE TEST</span></div></div>`;document.body.appendChild(o);o.onclick=e=>{if(e.target===o)close()};document.getElementById('slxs-close').onclick=close;document.getElementById('slxs-save').onclick=()=>{apiKey=document.getElementById('slxs-key').value.trim();localStorage.setItem(K.api,apiKey);document.getElementById('slxs-save').textContent='SAVED ✓'};document.getElementById('slxs-enable').onclick=()=>{for(const m of MODULES)if(ready(m))state[m.id]=true;save(K.modules,state);syncInternal();open()};document.getElementById('slxs-disable').onclick=()=>{for(const m of MODULES)state[m.id]=false;save(K.modules,state);syncInternal();open()};document.getElementById('slxs-export').onclick=()=>prompt('Copy Suite settings:',JSON.stringify({app:'SakaLuX Suite',version:VERSION,modules:state}));document.getElementById('slxs-import').onclick=()=>{const raw=prompt('Paste Suite settings:');if(!raw)return;try{const d=JSON.parse(raw);if(d.app!=='SakaLuX Suite')throw 0;for(const m of MODULES)if(typeof d.modules?.[m.id]==='boolean')state[m.id]=d.modules[m.id];save(K.modules,state);syncInternal();open()}catch{alert('Invalid Suite backup.')}};o.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{state[b.dataset.toggle]=!state[b.dataset.toggle];save(K.modules,state);syncInternal();open()});o.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.open))}

function openModule(id){const m=MODULES.find(x=>x.id===id);if(!m||!state[id])return;if(m.kind==='internal'){close();runInternal(id,true);return}try{const a=api(m);if(typeof a?.open==='function'){close();a.open();return}}catch{}const b=document.querySelector(m.button);if(b){close();b.click()}}

function prayerReminder(force=false){document.getElementById('slxs-prayer')?.remove();if(!state.prayer)return;if(localStorage.getItem(K.prayer)===todayUtc()&&!force)return;const b=document.createElement('button');b.id='slxs-prayer';b.textContent='🙏 PRAY';b.title='Prayer Reminder — tap after praying today';b.onclick=()=>{if(confirm('Mark today as prayed?')){localStorage.setItem(K.prayer,todayUtc());b.remove()}};document.body.appendChild(b)}
function findLife(){const nodes=[...document.querySelectorAll('body *')].filter(el=>el.children.length===0&&/life/i.test(el.textContent||''));for(const el of nodes){const txt=(el.parentElement?.textContent||el.textContent||'').replace(/,/g,' ');const m=txt.match(/life[^0-9]*(\d[\d ]*)\s*\/\s*(\d[\d ]*)/i);if(m){const cur=Number(m[1].replace(/\s/g,'')),max=Number(m[2].replace(/\s/g,''));if(cur>=0&&max>0)return{cur,max}}}return null}
function medRecommendation(){const life=findLife();if(!life)return'Life values are not visible on this page yet.';const missing=life.max-life.cur,pct=life.cur/life.max;if(missing<=0)return`Life ${life.cur}/${life.max}: full health — no med needed.`;let item='Small First Aid Kit';if(pct<.25)item='Blood Bag / strongest available heal';else if(pct<.5)item='Morphine or First Aid Kit';else if(pct<.8)item='First Aid Kit';return`Life ${life.cur}/${life.max} (${Math.round(pct*100)}%). Suggested: ${item}. Use your actual inventory and cooldowns to decide.`}
function medAdvisor(){document.getElementById('slxs-med')?.remove();if(!state['med-advisor'])return;const b=document.createElement('button');b.id='slxs-med';b.textContent='🩹 MED';b.title='SakaLuX Med Advisor';b.onclick=()=>alert(medRecommendation());document.body.appendChild(b)}
const ITEM_RULES=[[/xanax|ecstasy|lsd|vicodin|cannabis/i,'DRUG'],[/first aid|morphine|blood bag/i,'HEAL'],[/energy drink|can of .*energy/i,'ENERGY'],[/candy|chocolate|lollipop|happy/i,'HAPPY'],[/enhancer|parachute|dumbbell|boxing gloves|skateboard/i,'ENHANCER'],[/plushie|flower/i,'MUSEUM']];
function clearItemIntel(){document.querySelectorAll('.slxs-item-tag').forEach(x=>x.remove())}
function itemIntel(){clearItemIntel();if(!state['item-intel']||!/(items|item)/.test(routeText()))return;const nodes=[...document.querySelectorAll('li,tr,[class*="item"],[class*="Item"]')].slice(0,1000);for(const el of nodes){if(el.querySelector('.slxs-item-tag'))continue;const txt=(el.textContent||'').trim();if(!txt||txt.length>500)continue;const rule=ITEM_RULES.find(([re])=>re.test(txt));if(!rule)continue;const tag=document.createElement('span');tag.className='slxs-item-tag';tag.textContent=rule[1];const target=el.querySelector('a,span,div')||el;target.appendChild(tag)}}
function clearEventIntel(){document.getElementById('slxs-event-intel')?.remove();document.querySelectorAll('[data-slxs-hidden="1"]').forEach(el=>{el.style.display='';el.removeAttribute('data-slxs-hidden')})}
function eventIntel(){clearEventIntel();if(!state['event-intel']||!/(event)/.test(routeText()))return;const candidates=[...document.querySelectorAll('li,tr,[class*="event"],[class*="Event"]')].filter(el=>{const t=(el.textContent||'').trim();return t.length>8&&t.length<900&&!el.closest('#slxs-event-intel')});if(!candidates.length)return;const anchor=candidates[0].parentElement||candidates[0];const p=document.createElement('div');p.id='slxs-event-intel';p.className='slxs-event-panel';p.innerHTML=`<b>📋 Event Intel</b><input id="slxs-event-search" placeholder="Search visible events"><div class="slxs-event-stats">${candidates.length} event rows detected</div>`;anchor.parentElement?.insertBefore(p,anchor);const input=p.querySelector('input');input.oninput=()=>{const q=input.value.trim().toLowerCase();for(const el of candidates){const hide=q&&!String(el.textContent||'').toLowerCase().includes(q);el.style.display=hide?'none':'';if(hide)el.setAttribute('data-slxs-hidden','1');else el.removeAttribute('data-slxs-hidden')}}}
function runInternal(id,force=false){if(id==='prayer'){prayerReminder(force);if(force&&localStorage.getItem(K.prayer)===todayUtc())alert('Prayer Reminder: today is already marked as prayed.')}if(id==='med-advisor')alert(medRecommendation());if(id==='item-intel'){itemIntel();if(force)alert('Item Intel refreshed on the current page.')}if(id==='event-intel'){eventIntel();if(force&& !document.getElementById('slxs-event-intel'))alert('Open Torn Events, then run Event Intel again.')}}
function syncInternal(){prayerReminder();medAdvisor();if(state['item-intel'])itemIntel();else clearItemIntel();if(state['event-intel'])eventIntel();else clearEventIntel()}

function fallback(){let b=document.getElementById(IDS.fallback);if(!b){b=document.createElement('button');b.id=IDS.fallback;b.textContent='☠';b.title='SakaLuX Suite';b.onclick=open;document.body.appendChild(b)}syncLaunchers()}
function moneyTarget(){const all=[...document.querySelectorAll('a,button,[role="button"]')];return all.find(el=>{if(el.id===IDS.native||el.closest('#'+IDS.overlay))return false;const t=`${el.getAttribute('aria-label')||''} ${el.getAttribute('title')||''} ${el.textContent||''}`.toLowerCase();const h=String(el.getAttribute('href')||'').toLowerCase();return /\b(money|cash|wallet|bank)\b/.test(t)||/(money|wallet|bank)/.test(h)})||null}
function nativeLauncher(){if(document.getElementById(IDS.native)){syncLaunchers();return true}const target=moneyTarget();if(!target?.parentElement)return false;const n=target.cloneNode(false);n.id=IDS.native;n.removeAttribute('href');n.removeAttribute('target');n.setAttribute('role','button');n.setAttribute('aria-label','Open SakaLuX Suite');n.setAttribute('title','SakaLuX Suite');n.innerHTML='<span class="slxs-skull">☠</span>';n.onclick=e=>{e.preventDefault();e.stopPropagation();open()};target.parentElement.insertBefore(n,target);syncLaunchers();return true}
function syncLaunchers(){const b=document.getElementById(IDS.fallback);if(b)b.style.display=document.getElementById(IDS.native)?'none':'block'}
function health(){return{version:VERSION,nativeLauncher:!!document.getElementById(IDS.native),sharedApiKeyStored:!!apiKey,modules:MODULES.map(m=>({id:m.id,kind:m.kind,enabled:!!state[m.id],ready:ready(m),version:version(m)}))}}
window.SakaLuXSuite={version:VERSION,open,close,health,isModuleEnabled:id=>!!state[id],getSharedApiKey:()=>apiKey,runModule:id=>runInternal(id,true)};
function init(){css();fallback();nativeLauncher();syncInternal();setInterval(()=>{if(!document.getElementById(IDS.native))nativeLauncher();syncLaunchers();if(state.prayer)prayerReminder();},1500);setInterval(()=>{if(state['item-intel'])itemIntel();if(state['event-intel'])eventIntel();},7000);window.addEventListener('hashchange',()=>setTimeout(()=>{nativeLauncher();syncInternal()},300));window.dispatchEvent(new CustomEvent('SakaLuXSuiteReady',{detail:{version:VERSION}}));console.log('[SakaLuX Suite v'+VERSION+'] loaded')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();