// ==UserScript==
// @name         SakaLuX Elimination Assistant
// @namespace    sakalux.elimination.assistant
// @version      1.2.8
// @description  Torn Eliminations target advisor with FFScouter, BS calibration, learning, PDA support and safe Hub ON/OFF control.
// @author       SakaLuX [2380374]
// @license      MIT
// @match        https://www.torn.com/*
// @grant        GM_xmlhttpRequest
// @connect      api.torn.com
// @connect      ffscouter.com
// @downloadURL  https://update.greasyfork.org/scripts/594921/SakaLuX%20Elimination%20Assistant.user.js
// @updateURL    https://update.greasyfork.org/scripts/594921/SakaLuX%20Elimination%20Assistant.meta.js
// ==/UserScript==
(() => {
'use strict';
const VERSION='1.2.8';
const HUB_INSTALL_URL='https://update.greasyfork.org/scripts/592699/SakaLuX%20Script%20Hub.user.js';
const HUB_PROMPT_STORAGE='SakaLuX_HUB_INSTALL_PROMPT_LAST';
const HUB_PROMPT_ID='sakalux-hub-install-prompt';
const HUB_PROMPT_INTERVAL=86400000;
const TORN_KEY_CREATE_URL='https://www.torn.com/preferences.php#tab=api?step=addNewKey&title=SakaLuX_Elimination_Assistant&user=basic,battlestats&torn=elimination,eliminationteam';
const IDS={button:'slx-elim-btn',panel:'slx-elim',style:'slx-elim-style'};
const K={torn:'slx_elim_torn_key',ff:'slx_elim_ff_key',team:'slx_elim_team',enabled:'slx_elim_enabled',hist:'slx_elim_history_v4',learn:'slx_elim_learning_v1',cache:'slx_elim_ff_cache_v2',my:'slx_elim_my_stats_v1'};
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={enabled:localStorage.getItem(K.enabled)!=='0',tornKey:localStorage.getItem(K.torn)||'',ffKey:localStorage.getItem(K.ff)||'',teamId:Number(localStorage.getItem(K.team)||0),teams:[],players:[],view:[],history:load(K.hist,[]),learning:load(K.learn,{}),cache:load(K.cache,{}),my:load(K.my,{total:null,at:0,source:''}),busy:false,keyBusy:false,lastRefresh:0};
const fmtBS=n=>{n=Number(n||0);if(!n)return'—';if(n>=1e12)return(n/1e12).toFixed(2)+'T';if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(1)+'M';if(n>=1e3)return(n/1e3).toFixed(1)+'K';return String(Math.round(n))};
const age=ts=>{if(!ts)return'—';const s=Math.max(0,Math.floor(Date.now()/1000)-Number(ts));return s<60?s+'s':s<3600?Math.floor(s/60)+'m':s<86400?Math.floor(s/3600)+'h':Math.floor(s/86400)+'d'};
function requestJSON(url){return new Promise((resolve,reject)=>{const parse=t=>{try{const j=JSON.parse(t);if(j?.error){const e=new Error(j.error.error||j.error.message||'API error');e.code=Number(j.error.code||0);reject(e)}else resolve(j)}catch(e){reject(e)}};if(typeof window.PDA_httpGet==='function'){window.PDA_httpGet(url,{Accept:'application/json'}).then(r=>parse(String(r?.responseText??r?.body??r??''))).catch(reject);return}if(window.flutter_inappwebview?.callHandler){window.flutter_inappwebview.callHandler('PDA_httpGet',url,{Accept:'application/json'}).then(r=>parse(String(r?.responseText??r?.body??r??''))).catch(reject);return}if(typeof GM_xmlhttpRequest==='function'){GM_xmlhttpRequest({method:'GET',url,timeout:15000,onload:r=>r.status>=200&&r.status<400?parse(r.responseText):reject(new Error('HTTP '+r.status)),onerror:()=>reject(new Error('Network error')),ontimeout:()=>reject(new Error('Timeout'))});return}fetch(url).then(r=>r.text()).then(parse).catch(reject)})}
function torn(path,params={}){if(!state.tornKey)return Promise.reject(new Error('Set Torn API key in Settings'));const u=new URL('https://api.torn.com/v2/'+path.replace(/^\/+/,''));u.searchParams.set('key',state.tornKey.trim());u.searchParams.set('striptags','true');Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));return requestJSON(u.href)}
function ffReq(ids){if(!state.ffKey)return Promise.reject(new Error('Set FFScouter API key in Settings'));const u=new URL('https://ffscouter.com/api/v1/get-stats');u.searchParams.set('key',state.ffKey.trim());u.searchParams.set('targets',ids.join(','));return requestJSON(u.href)}
function normTeams(raw){const r=raw?.elimination||raw?.teams||raw?.data||raw;const a=Array.isArray(r)?r:(r&&typeof r==='object'?(Array.isArray(r.teams)?r.teams:Object.entries(r).map(([id,x])=>({id:Number(id),...(x||{})}))):[]);return a.map((t,i)=>({id:Number(t.id??t.team_id??i),name:t.name??t.team_name??('Team '+(t.id??i)),score:Number(t.score??t.points??0)})).filter(x=>Number.isFinite(x.id))}
function normPlayers(raw){const r=raw?.eliminationteam||raw?.players||raw?.members||raw?.data||raw;const a=Array.isArray(r)?r:(r&&typeof r==='object'?(Array.isArray(r.players)?r.players:Array.isArray(r.members)?r.members:Object.entries(r).map(([id,x])=>({id:Number(id),...(x||{})}))):[]);return a.map((p,i)=>({id:Number(p.id??p.user_id??p.player_id??i),name:p.name??p.player_name??p.username??('Player '+i),level:Number(p.level??0),score:Number(p.score??p.points??p.contribution??0),last:Number(p.last_action?.timestamp??p.last_action_timestamp??0),status:String(p.status?.state??p.status?.description??p.status??''),ff:null,bs:null})).filter(p=>p.id>0)}
function normFF(raw){const a=Array.isArray(raw)?raw:Array.isArray(raw?.players)?raw.players:Array.isArray(raw?.data)?raw.data:[];return a.map(x=>({id:Number(x.player_id??x.id??0),ff:Number(x.fair_fight??x.ff??0)||null,bs:Number(x.bs_estimate??x.battle_stats??x.bss??0)||null})).filter(x=>x.id>0)}
function unavailable(p){return/hospital|federal|fallen|jail/i.test(p.status)}
function learn(id){const x=state.learning[String(id)]||{};return{wins:Number(x.wins||0),losses:Number(x.losses||0)}}
function risk(p){let n=50;const l=learn(p.id);const edge=state.my.total&&p.bs?state.my.total/Math.max(1,p.bs):null;if(edge!==null){if(edge>=5)n-=38;else if(edge>=2)n-=27;else if(edge>=1.25)n-=14;else if(edge<.8)n+=34;else n+=8}else if(p.ff){if(p.ff>=5)n-=34;else if(p.ff>=3)n-=25;else if(p.ff>=1.5)n-=7;else n+=27}else{if(p.level&&p.level<=10)n-=22;else if(p.level<=25)n-=13;else if(p.level<=50)n+=4;else if(p.level<=75)n+=15;else if(p.level>75)n+=26}if(p.last){const h=(Date.now()/1000-p.last)/3600;if(h>=168)n-=16;else if(h>=24)n-=10;else if(h<4)n+=8}if(l.wins+l.losses){const wr=l.wins/(l.wins+l.losses);if(l.wins+l.losses>=2&&wr>=.75)n-=14;else if(l.wins+l.losses>=2&&wr<=.4)n+=22}if(unavailable(p))n=100;n=Math.max(0,Math.min(100,Math.round(n)));return{score:n,label:n<=34?'SAFE':n<=64?'RISKY':'SKIP',edge}}
function smart(p){const r=risk(p);let s=100-r.score;if(p.ff)s+=Math.max(-8,Math.min(16,(p.ff-1)*4));if(r.edge!==null)s+=Math.max(-18,Math.min(20,Math.log2(Math.max(.1,r.edge))*8));if(unavailable(p))s=0;return Math.max(0,Math.min(100,Math.round(s)))}
function signal(p){const r=risk(p);return`${p.ff?'FF '+p.ff.toFixed(2):'FF —'} · ${p.bs?'BS ~'+fmtBS(p.bs):'BS —'}${r.edge!==null?' · '+r.edge.toFixed(1)+'× edge':''} · ${r.label} · ${smart(p)}/100`}
function syncHubPower(){
  for(const b of $$('[data-script="elimination-assistant"][data-action="toggle"]')){
    const txt=state.enabled?'⏻ ON':'⏻ OFF';
    if(b.textContent!==txt)b.textContent=txt;
    b.style.setProperty('display','inline-block','important');
    b.style.setProperty('background',state.enabled?'#166534':'#991b1b','important');
    b.style.setProperty('border-color',state.enabled?'#22c55e':'#ef4444','important');
    b.style.setProperty('color','#fff','important');
    b.style.setProperty('font-weight','900','important');
    const actions=b.closest('.slh-actions');
    if(actions){
      for(const x of $$('.slh-action',actions)){
        if(x===b)x.style.setProperty('display','inline-block','important');
        else if(state.enabled)x.style.removeProperty('display');
        else x.style.setProperty('display','none','important');
      }
    }
  }
}
function isHubInstalled(){return!!(window.SakaLuXScriptHub||$('#sakalux-hub-button'))}
function showHubPrompt(){if(!state.enabled||isHubInstalled()||$('#'+HUB_PROMPT_ID))return;const last=Number(localStorage.getItem(HUB_PROMPT_STORAGE)||0);if(last&&Date.now()-last<HUB_PROMPT_INTERVAL)return;const d=document.createElement('div');d.id=HUB_PROMPT_ID;d.style.cssText='position:fixed;inset:0;z-index:2147483647;background:#000b;display:flex;align-items:center;justify-content:center';d.innerHTML='<div style="background:#111;color:#fff;padding:18px;border-radius:12px"><b>Install SakaLuX Script Hub?</b><div style="margin-top:12px"><button id="slx-later">LATER</button> <button id="slx-install">INSTALL HUB</button></div></div>';document.body.appendChild(d);$('#slx-later',d).onclick=()=>{localStorage.setItem(HUB_PROMPT_STORAGE,String(Date.now()));d.remove()};$('#slx-install',d).onclick=()=>{localStorage.setItem(HUB_PROMPT_STORAGE,String(Date.now()));location.href=HUB_INSTALL_URL}}
function css(){if($('#'+IDS.style))return;const s=document.createElement('style');s.id=IDS.style;s.textContent=`#${IDS.button}{position:fixed;right:12px;bottom:82px;z-index:999999;background:#171b21;color:#fff;border:1px solid #414a55;border-radius:999px;padding:10px 13px;font-weight:800}#${IDS.panel}{display:none;position:fixed;right:6px;bottom:125px;z-index:999998;width:min(920px,calc(100vw - 12px));height:80vh;background:#101419;color:#fff;border:1px solid #343c45;border-radius:14px;overflow:hidden;font:12px Arial}#${IDS.panel}.open{display:flex;flex-direction:column}.slx-h,.slx-t,.slx-s{display:flex;gap:6px;align-items:center;padding:8px;border-bottom:1px solid #28313a;flex-wrap:wrap}.slx-h b,.slx-s span{flex:1}.slx-t input,.slx-t select,.slx-t button,.slx-a,.slx-h button{background:#171d24;color:#fff;border:1px solid #3b4652;border-radius:7px;padding:7px}.slx-body{overflow:auto;flex:1}.slx-body table{width:100%;border-collapse:collapse}.slx-body td,.slx-body th{padding:6px;border-bottom:1px solid #242c34;text-align:left}.safe{color:#63d889;font-weight:900}.risky{color:#f2c15c;font-weight:900}.skip{color:#ef7474;font-weight:900}.slx-modal{display:none;position:absolute;inset:0;z-index:20;background:#0c1015f5;padding:14px;overflow:auto}.slx-modal.open{display:block}.slx-modal input{width:100%;padding:8px;margin:4px 0 10px;background:#11161c;color:#fff;border:1px solid #35404c;border-radius:7px}`;document.head.appendChild(s)}
function inject(){if(!state.enabled||$('#'+IDS.panel))return;css();const b=document.createElement('button');b.id=IDS.button;b.textContent='ELIM ⚔';const p=document.createElement('div');p.id=IDS.panel;p.innerHTML=`<div class="slx-h"><b>SakaLuX Elimination Assistant v${VERSION}</b><button id="slx-set">⚙</button><button id="slx-close">✕</button></div><div class="slx-t"><select id="slx-team"><option value="">Team…</option></select><button id="slx-load">LOAD</button><button id="slx-ff">FF SCAN</button><button id="slx-cal">CALIBRATE ME</button><input id="slx-q" placeholder="Player / ID"><select id="slx-filter"><option value="all">All</option><option value="safe">SAFE</option><option value="ok">SAFE + RISKY</option><option value="new">Not opened</option></select></div><div class="slx-s"><span id="slx-status">Set Torn API key in ⚙ Settings.</span><b id="slx-summary"></b></div><div class="slx-body"><table><thead><tr><th>Signal</th><th>Player</th><th>Lvl</th><th>Last</th><th>Actions</th></tr></thead><tbody id="slx-rows"></tbody></table></div><div class="slx-modal" id="slx-settings"><h3>Settings</h3><p>TEST TORN KEY checks battlestats and Eliminations separately. API 32 on eliminationteam means that Torn is not currently exposing that event endpoint; it is not treated as a bad API key.</p><button class="slx-a" id="slx-create">🔑 CREATE REQUIRED TORN KEY</button> <button class="slx-a" id="slx-test">🧪 TEST TORN KEY</button><label>Torn API key</label><input id="slx-torn"><label>FFScouter API key (optional)</label><input id="slx-ffkey"><label>Manual total BS</label><input id="slx-manual" type="number"><button class="slx-a" id="slx-save">SAVE</button> <button class="slx-a" id="slx-cancel">CLOSE</button></div>`;document.body.append(b,p);b.onclick=()=>p.classList.toggle('open');$('#slx-close',p).onclick=()=>p.classList.remove('open');$('#slx-set',p).onclick=openSettings;$('#slx-cancel',p).onclick=()=>$('#slx-settings',p).classList.remove('open');$('#slx-save',p).onclick=saveSettings;$('#slx-create',p).onclick=createKey;$('#slx-test',p).onclick=()=>busy(testKey);$('#slx-load',p).onclick=()=>busy(loadTeam);$('#slx-ff',p).onclick=()=>busy(()=>loadFF(true));$('#slx-cal',p).onclick=()=>busy(()=>calibrate(true));$('#slx-q',p).oninput=apply;$('#slx-filter',p).onchange=apply;$('#slx-team',p).onchange=e=>{state.teamId=Number(e.target.value||0);localStorage.setItem(K.team,String(state.teamId||''))};if(state.tornKey)busy(refresh)}
function removeUI(){$('#'+IDS.panel)?.remove();$('#'+IDS.button)?.remove();$('#'+HUB_PROMPT_ID)?.remove()}
function setEnabled(v){state.enabled=!!v;localStorage.setItem(K.enabled,state.enabled?'1':'0');state.enabled?inject():removeUI();syncHubPower();window.dispatchEvent(new CustomEvent('SakaLuXEliminationAssistantStateChanged',{detail:{enabled:state.enabled,version:VERSION}}));return state.enabled}
function toggleEnabled(){return setEnabled(!state.enabled)}
function setStatus(t){const e=$('#slx-status');if(e)e.textContent=t}
function createKey(){if(state.keyBusy)return false;state.keyBusy=true;setTimeout(()=>state.keyBusy=false,2500);location.href=TORN_KEY_CREATE_URL;return true}
function openSettings(){const m=$('#slx-settings');if(!m)return;$('#slx-torn',m).value=state.tornKey;$('#slx-ffkey',m).value=state.ffKey;$('#slx-manual',m).value=state.my.source==='manual'?(state.my.total||0):0;m.classList.add('open')}
function saveSettings(){const m=$('#slx-settings');state.tornKey=$('#slx-torn',m).value.trim();state.ffKey=$('#slx-ffkey',m).value.trim();const n=Number($('#slx-manual',m).value||0);if(n>0){state.my={total:n,at:Date.now(),source:'manual'};save(K.my,state.my)}localStorage.setItem(K.torn,state.tornKey);localStorage.setItem(K.ff,state.ffKey);m.classList.remove('open');busy(refresh)}
async function testKey(){const typed=$('#slx-torn')?.value.trim();if(typed){state.tornKey=typed;localStorage.setItem(K.torn,typed)}if(!state.tornKey)throw new Error('Paste a Torn API key first');const out=[];for(const [path,label] of [['user/battlestats','battlestats'],['torn/elimination','elimination']]){try{await torn(path);out.push(label+': OK')}catch(e){out.push(label+': FAIL'+(e.code?' API '+e.code:''))}}if(state.teamId){try{await torn(`torn/${state.teamId}/eliminationteam`,{limit:1,offset:0});out.push('eliminationteam: OK')}catch(e){if(Number(e.code)===32)out.push('eliminationteam: ⏸ UNAVAILABLE (API 32) — key not rejected');else out.push('eliminationteam: FAIL'+(e.code?' API '+e.code:''))}}else out.push('eliminationteam: not tested until a team is selected');setStatus(out.join(' | '));return !out.some(x=>x.includes('FAIL'))}
async function calibrate(force=false){if(state.my.source==='manual'&&!force)return state.my.total;if(!force&&state.my.total&&Date.now()-Number(state.my.at||0)<900000)return state.my.total;const raw=await torn('user/battlestats');const x=raw?.battlestats??raw?.data??raw??{};const total=['strength','defense','speed','dexterity'].reduce((s,k)=>s+Number(x[k]??x?.battle_stats?.[k]??0),0);if(!total)throw new Error('battlestats not returned; run TEST TORN KEY');state.my={total,at:Date.now(),source:'Torn API'};save(K.my,state.my);apply();return total}
async function loadTeams(){state.teams=normTeams(await torn('torn/elimination'));if(!state.teamId&&state.teams[0])state.teamId=state.teams[0].id;const e=$('#slx-team');if(e)e.innerHTML='<option value="">Team…</option>'+state.teams.map(t=>`<option value="${t.id}" ${t.id===state.teamId?'selected':''}>${esc(t.name)}</option>`).join('')}
async function loadTeam(){if(!state.teamId)throw new Error('Choose a team');const a=[];for(let off=0,i=0;i<5;i++,off+=100){let raw;try{raw=await torn(`torn/${state.teamId}/eliminationteam`,{limit:100,offset:off})}catch(e){if(Number(e.code)===32)throw new Error('Elimination team data is currently unavailable from Torn (API 32). Your API key was not rejected; try again when Torn enables the Eliminations team endpoint.');throw e}const batch=normPlayers(raw);a.push(...batch);if(batch.length<100)break}state.players=[...new Map(a.map(p=>[p.id,p])).values()];applyCache();if(state.ffKey)await loadFF(false);apply();setStatus('Loaded '+state.players.length+' players')}
function applyCache(){for(const p of state.players){const c=state.cache[String(p.id)];if(c&&Date.now()-Number(c.at||0)<1800000){p.ff=c.ff||null;p.bs=c.bs||null}}}
async function loadFF(force=false){if(!state.players.length)throw new Error('Load a team first');if(!state.ffKey)throw new Error('Set FFScouter API key');const ids=state.players.filter(p=>force||!state.cache[String(p.id)]||Date.now()-Number(state.cache[String(p.id)].at||0)>=1800000).map(p=>p.id),all=[];for(let i=0;i<ids.length;i+=205)all.push(...normFF(await ffReq(ids.slice(i,i+205))));for(const x of all)state.cache[String(x.id)]={...x,at:Date.now()};save(K.cache,state.cache);applyCache();apply();setStatus('FF scan ready')}
function apply(){const q=($('#slx-q')?.value||'').toLowerCase(),f=$('#slx-filter')?.value||'all';let a=state.players.filter(p=>!q||p.name.toLowerCase().includes(q)||String(p.id).includes(q));a=a.filter(p=>{const r=risk(p);if(unavailable(p))return false;if(f==='safe')return r.label==='SAFE';if(f==='ok')return r.label!=='SKIP';if(f==='new')return !state.history.some(h=>Number(h.id)===p.id);return true});a.sort((x,y)=>smart(y)-smart(x));state.view=a;render()}
function render(){const e=$('#slx-rows');if(!e)return;e.innerHTML=state.view.map(p=>{const r=risk(p),c=r.label==='SAFE'?'safe':r.label==='RISKY'?'risky':'skip',l=learn(p.id);return`<tr><td class="${c}">${esc(signal(p))}</td><td><a class="slx-a" href="https://www.torn.com/profiles.php?XID=${p.id}" target="_blank">${esc(p.name)}</a><small> ${l.wins}W/${l.losses}L</small></td><td>${p.level||'—'}</td><td>${age(p.last)}</td><td><a class="slx-a atk" data-id="${p.id}" href="https://www.torn.com/loader.php?sid=attack&user2ID=${p.id}">ATTACK</a><button class="slx-a win" data-id="${p.id}">WIN</button><button class="slx-a loss" data-id="${p.id}">LOSS</button></td></tr>`}).join('');$$('.atk',e).forEach(a=>a.onclick=()=>{const p=state.players.find(x=>x.id===Number(a.dataset.id));if(p){state.history.unshift({id:p.id,name:p.name,action:'opened',at:Date.now()});save(K.hist,state.history.slice(0,1000))}});$$('.win',e).forEach(b=>b.onclick=()=>record(state.players.find(x=>x.id===Number(b.dataset.id)),'win'));$$('.loss',e).forEach(b=>b.onclick=()=>record(state.players.find(x=>x.id===Number(b.dataset.id)),'loss'));const safe=state.players.filter(p=>!unavailable(p)&&risk(p).label==='SAFE').length;$('#slx-summary').textContent=`ME ${state.my.total?fmtBS(state.my.total):'uncalibrated'} · SAFE ${safe}`}
function record(p,res){if(!p)return;const l=learn(p.id);res==='win'?l.wins++:l.losses++;state.learning[String(p.id)]=l;save(K.learn,state.learning);apply()}
async function refresh(){if(!state.enabled)return false;await loadTeams();if(state.teamId)await loadTeam();state.lastRefresh=Date.now();return true}
async function busy(fn){if(!state.enabled||state.busy)return false;state.busy=true;try{await fn();return true}catch(e){console.error('[SakaLuX Elimination]',e);setStatus('Error: '+e.message);return false}finally{state.busy=false}}
function open(){if(!state.enabled)setEnabled(true);inject();$('#'+IDS.panel)?.classList.add('open');return true}
function close(){$('#'+IDS.panel)?.classList.remove('open')}
function health(){return{version:VERSION,enabled:state.enabled,ready:state.enabled&&!!$('#'+IDS.panel),targets:state.players.length,myBattleStats:state.my.total||null,lastRefresh:state.lastRefresh}}
function goToEliminations(){location.href='https://www.torn.com/page.php?sid=elimination'}
window.SakaLuXEliminationAssistant={version:VERSION,open,close,refresh:()=>busy(refresh),scanFF:()=>busy(()=>loadFF(true)),calibrate:()=>busy(()=>calibrate(true)),testTornKey:()=>busy(testKey),createRequiredTornKey:createKey,setEnabled,toggleEnabled,isEnabled:()=>state.enabled,goToEliminations,health};
window.dispatchEvent(new CustomEvent('SakaLuXEliminationAssistantReady',{detail:{version:VERSION,enabled:state.enabled}}));
function start(){syncHubPower();setInterval(syncHubPower,900);if(state.enabled){inject();setTimeout(showHubPrompt,1200)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();