// ==UserScript==
// @name         SakaLuX Chat Intelligence
// @namespace    sakalux.chat.intelligence
// @version      1.0.2
// @description  Torn Chat 3 enhancements for SakaLuX Hub: search, resize, mentions, favorites, aliases, local mute, timestamps, notifications and TornPDA controls.
// @author       SakaLuX [2380374]
// @match        https://www.torn.com/*
// @grant        none
// @license      All Rights Reserved
// @downloadURL  https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Chat-Intelligence.user.js
// @updateURL    https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Chat-Intelligence.user.js
// ==/UserScript==
(function(){'use strict';
const V='1.0.2',ID='chat-intelligence',API='SakaLuXChatIntelligence',K={s:'SakaLuX_CHAT_SETTINGS_V1',p:'SakaLuX_CHAT_PEOPLE_V1',f:'SakaLuX_CHAT_FAVORITES_V1',m:'SakaLuX_CHAT_MUTED_V1',seen:'SakaLuX_CHAT_SEEN_V1'};
const D={enabled:true,search:true,timestamps:true,quickActions:true,quickReply:true,notifications:true,autoGrowComposer:true,mentionAutocomplete:true,compactMobile:true,maxSeenMessages:800};
const L=(k,d)=>{try{let x=localStorage.getItem(k);return x?JSON.parse(x):d}catch{return d}},S=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let C={...D,...L(K.s,D)},P=L(K.p,{}),F=new Set(L(K.f,[])),M=new Set(L(K.m,[])),Seen=new Set(L(K.seen,[]));
const initRoots=new WeakSet(),bound=new WeakSet(),norm=x=>String(x??'').replace(/\s+/g,' ').trim(),hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
function save(){S(K.s,C);S(K.p,P);S(K.f,[...F]);S(K.m,[...M]);let a=[...Seen];if(a.length>C.maxSeenMessages)a=a.slice(-C.maxSeenMessages);S(K.seen,a)}
function p(el){let a=el.querySelector('a[href*="profiles.php"],a[href*="XID="]'),id='',name='';if(a){let m=(a.getAttribute('href')||'').match(/[?&]XID=(\d+)/i);if(m)id=m[1];name=norm(a.textContent)}if(!name)name=norm(el.querySelector('[class*="sender"],[class*="author"],[class*="username"],[class*="playerName"]')?.textContent);return{id,name}}
function key(x){return x.id?'id:'+x.id:x.name?'name:'+x.name.toLowerCase():''}
function msg(el){if(!el||!el.isConnected||el.closest('.slx-chat-tools,.slx-chat-actions,.slx-chat-time,.slx-chat-mentions,#slx-chat-toast-stack'))return false;if(el.querySelector('textarea,[contenteditable="true"]'))return false;let t=norm(el.innerText||el.textContent),c=typeof el.className==='string'?el.className.toLowerCase():'';if(!t||t.length>3000)return false;let ok=el.hasAttribute('data-message-id')||el.hasAttribute('data-message')||c.includes('chatmessage')||c.includes('messageitem')||c.includes('messagerow')||((!!el.querySelector('a[href*="profiles.php"],a[href*="XID="]'))&&(!!el.querySelector('[class*="sender"],[class*="author"],[class*="username"],[class*="playerName"]')));if(!ok)return false;return !el.querySelector('[data-message-id] [data-message-id],[class*="chatMessage"] [class*="chatMessage"],[class*="messageItem"] [class*="messageItem"]')}
function msgs(root){let q='[data-message-id],[data-message],[class*="chatMessage"],[class*="messageItem"],[class*="message-item"],[class*="messageRow"],[class*="message-row"]',a=[...root.querySelectorAll(q)].filter(msg);if(!a.length)a=[...root.querySelectorAll('a[href*="profiles.php"],a[href*="XID="]')].map(x=>x.closest('div,section,article')).filter(msg);return a.filter((e,i)=>!a.some((o,j)=>j!==i&&e.contains(o)))}
function roots(){let z=new Set;document.querySelectorAll('textarea,[contenteditable="true"]').forEach(inp=>{let n=inp;for(let i=0;n&&i<7;i++,n=n.parentElement){if(n===document.body)break;let r=n.getBoundingClientRect(),sig=n.querySelector('[data-message-id],[data-message],[class*="chatMessage"],[class*="messageItem"],[class*="messageRow"],a[href*="profiles.php"]');if(sig&&r.width>=220&&r.width<=Math.min(innerWidth*.98,900)&&r.height>=180&&r.height<=innerHeight*.95){z.add(n);break}}});return[...z]}
function body(el,x){let c=el.cloneNode(true);c.querySelectorAll('.slx-chat-actions,.slx-chat-time,.slx-chat-mentions,.slx-chat-tools').forEach(e=>e.remove());let t=norm(c.innerText||c.textContent);if(x.name&&t.startsWith(x.name))t=norm(t.slice(x.name.length));return t}
function ident(root,el,x,b){return'm:'+(el.dataset.messageId||el.id||hash((x.id||x.name)+'|'+b))}
function toast(t,b){let st=document.getElementById('slx-chat-toast-stack');if(!st){st=document.createElement('div');st.id='slx-chat-toast-stack';document.body.appendChild(st)}let k=hash(t+'|'+b);if(st.querySelector('[data-k="'+k+'"]'))return;let e=document.createElement('div');e.className='slx-chat-toast';e.dataset.k=k;e.innerHTML='<b>'+t.replace(/[<>]/g,'')+'</b><span>'+b.replace(/[<>]/g,'')+'</span>';st.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},3200)}
function notify(root,x,b,id,sup){if(Seen.has(id))return;Seen.add(id);save();let k=key(x);if(sup||!C.notifications||!k||M.has(k)||!b)return;toast((F.has(k)?'★ ':'')+(P[k]?.alias||x.name),b.slice(0,180))}
function stamp(el){if(!C.timestamps||el.querySelector(':scope>.slx-chat-time'))return;let t=el.querySelector('time[datetime],[data-timestamp],[class*="timestamp"]'),v='';if(t){let d=t.getAttribute('datetime')||t.dataset?.timestamp;if(d){let n=Number(d),dt=Number.isFinite(n)?new Date(n<1e12?n*1000:n):new Date(d);if(!isNaN(dt))v=dt.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}if(!v)v=norm(t.textContent)}let s=document.createElement('span');s.className='slx-chat-time';s.textContent=v||new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});el.appendChild(s)}
function composer(r){return r.querySelector('textarea,[contenteditable="true"]')}
function reply(r,x){let c=composer(r);if(!c||!x.name)return;if('value'in c){c.value='@'+x.name+' '+(c.value||'');c.dispatchEvent(new Event('input',{bubbles:true}));c.focus()}}
function acts(r,el,x){if(!C.quickActions||el.querySelector(':scope>.slx-chat-actions'))return;let k=key(x);if(!k)return;let box=document.createElement('div');box.className='slx-chat-actions';[['fav',F.has(k)?'★':'☆'],['reply','↩'],['id','ID'],['profile','↗'],['mute',M.has(k)?'🔈':'🔇'],['alias','✎']].forEach(([a,t])=>{let b=document.createElement('button');b.textContent=t;b.onclick=e=>{e.preventDefault();e.stopPropagation();if(a==='fav'){F.has(k)?F.delete(k):F.add(k);save()}else if(a==='reply')reply(r,x);else if(a==='id'&&x.id)navigator.clipboard?.writeText(x.id);else if(a==='profile'&&x.id)location.href='https://www.torn.com/profiles.php?XID='+x.id;else if(a==='mute'){M.has(k)?M.delete(k):M.add(k);save()}else if(a==='alias'){let v=prompt('Alias for '+x.name,P[k]?.alias||'');if(v!==null){P[k]={...(P[k]||{}),alias:norm(v)};save()}}};box.appendChild(b)});el.appendChild(box)}
function decorate(r,el,sup){let x=p(el),b=body(el,x);if(!b&&!x.name)return;let id=ident(r,el,x,b);el.dataset.slxId=id;el.classList.add('slx-chat-message');let k=key(x),n=el.querySelector('a[href*="profiles.php"],[class*="sender"],[class*="author"],[class*="username"],[class*="playerName"]');if(n&&P[k]?.alias)n.textContent=P[k].alias;if(k)el.classList.toggle('slx-chat-muted-message',M.has(k));stamp(el);acts(r,el,x);notify(r,x,b,id,sup);if(C.quickReply&&!el.dataset.slxQr){el.dataset.slxQr=1;el.ondblclick=e=>{if(!e.target.closest('a,button,input,textarea'))reply(r,x)}}}
function toolbar(r){if(!C.search||r.querySelector(':scope>.slx-chat-tools'))return;let c=composer(r);if(!c)return;let t=document.createElement('div');t.className='slx-chat-tools';t.innerHTML='<button>🔎</button><input placeholder="Search loaded messages…"><span>0</span>';c.parentElement?.parentElement?.insertBefore(t,c.parentElement);let i=t.querySelector('input'),count=t.querySelector('span'),run=()=>{let q=norm(i.value).toLowerCase(),m=msgs(r),n=0;m.forEach(e=>{let hit=!q||norm(body(e,p(e))).toLowerCase().includes(q)||norm(p(e).name).toLowerCase().includes(q);e.classList.toggle('slx-chat-search-hidden',!!q&&!hit);if(q&&hit)n++});count.textContent=q?n:m.length};i.oninput=run;t.firstElementChild.onclick=run}
function bindComposer(r){let c=composer(r);if(!c||bound.has(c))return;bound.add(c);if(C.autoGrowComposer&&c.tagName==='TEXTAREA'){let g=()=>{c.style.height='auto';c.style.height=Math.min(96,Math.max(38,c.scrollHeight))+'px'};c.addEventListener('input',g);g()}}
function enhance(r){r.classList.add('slx-chat-root');toolbar(r);bindComposer(r);let first=!initRoots.has(r),m=msgs(r);m.forEach(e=>decorate(r,e,first));if(first)initRoots.add(r);let c=r.querySelector('.slx-chat-tools span');if(c)c.textContent=m.length}
let obs,timer;
function own(rec){let t=rec.target?.nodeType===1?rec.target:rec.target?.parentElement;if(t?.closest?.('.slx-chat-tools,.slx-chat-actions,.slx-chat-time,.slx-chat-mentions,#slx-chat-toast-stack,#sakalux-chat-settings-overlay'))return true;let a=[...(rec.addedNodes||[])].filter(n=>n.nodeType===1);return a.length&&a.every(n=>n.matches?.('.slx-chat-tools,.slx-chat-actions,.slx-chat-time,.slx-chat-mentions,.slx-chat-toast,#slx-chat-toast-stack,#sakalux-chat-settings-overlay')||n.closest?.('.slx-chat-tools,.slx-chat-actions,.slx-chat-mentions,#slx-chat-toast-stack'))}
function scan(){if(!C.enabled)return;roots().forEach(enhance);bridge()}
function start(){if(obs)return;obs=new MutationObserver(rs=>{if(rs.some(r=>r.type==='childList'&&r.addedNodes.length&&!own(r))){clearTimeout(timer);timer=setTimeout(scan,120)}});obs.observe(document.documentElement,{childList:true,subtree:true})}
function bridge(){let b=document.getElementById('sakalux-module-bridge-'+ID);if(!b){b=document.createElement('button');b.id='sakalux-module-bridge-'+ID;b.hidden=true;b.style.display='none';b.onclick=()=>{let a=b.dataset.action;if(a==='open')settings();else if(a==='on')setEnabled(true);else if(a==='off')setEnabled(false);else if(a==='toggle')setEnabled(!C.enabled);b.dataset.action=''};document.documentElement.appendChild(b)}b.dataset.moduleId=ID;b.dataset.version=V;b.dataset.enabled=String(C.enabled);b.dataset.ready='true'}
function setEnabled(v){C.enabled=!!v;save();if(C.enabled){start();scan()}else{obs?.disconnect();obs=null;document.querySelectorAll('.slx-chat-tools,.slx-chat-actions,.slx-chat-time').forEach(e=>e.remove())}bridge();return C.enabled}
function settings(){if(document.getElementById('sakalux-chat-settings-overlay'))return;let o=document.createElement('div');o.id='sakalux-chat-settings-overlay';o.innerHTML='<section><header><b>💬 Chat Intelligence v'+V+'</b><button>×</button></header><main>'+[['enabled','Module enabled'],['search','Search'],['timestamps','Timestamps'],['quickActions','Quick actions'],['quickReply','Quick reply'],['notifications','Notifications'],['autoGrowComposer','Auto-grow message box']].map(([k,l])=>'<label><span>'+l+'</span><input type="checkbox" data-k="'+k+'" '+(C[k]?'checked':'')+'></label>').join('')+'</main><footer>SakaLuX [2380374]</footer></section>';document.body.appendChild(o);o.querySelector('header button').onclick=()=>o.remove();o.querySelectorAll('[data-k]').forEach(x=>x.onchange=()=>{C[x.dataset.k]=x.checked;save();if(x.dataset.k==='enabled')setEnabled(x.checked)})}
function css(){if(document.getElementById('sakalux-chat-intelligence-style'))return;let s=document.createElement('style');s.id='sakalux-chat-intelligence-style';s.textContent='.slx-chat-root{position:relative!important}.slx-chat-tools{display:flex!important;gap:5px!important;padding:5px!important;background:#101821!important;border:1px solid #34475d!important;border-radius:9px!important}.slx-chat-tools input{flex:1!important;min-width:0!important;background:#111b26!important;color:#eee!important;border:1px solid #34475d!important;border-radius:7px!important;padding:7px!important}.slx-chat-tools button{width:38px!important}.slx-chat-message{position:relative!important}.slx-chat-actions{display:none!important;gap:3px!important;margin:3px 0!important}.slx-chat-message:hover>.slx-chat-actions,.slx-chat-message:focus-within>.slx-chat-actions{display:flex!important}@media(max-width:700px){.slx-chat-message>.slx-chat-actions{display:flex!important;overflow:auto!important}.slx-chat-actions button{min-width:30px!important;height:28px!important}}.slx-chat-time{margin-left:6px!important;color:#778ca4!important;font-size:8px!important}.slx-chat-muted-message{opacity:.25!important}.slx-chat-search-hidden{display:none!important}#slx-chat-toast-stack{position:fixed!important;right:10px!important;top:70px!important;z-index:2147483647!important;width:min(330px,calc(100vw - 20px))!important}.slx-chat-toast{opacity:0!important;transform:translateX(110%)!important;transition:.2s!important;padding:10px!important;margin-bottom:6px!important;background:#111a24!important;color:#eee!important;border:1px solid #3b4d63!important;border-radius:10px!important}.slx-chat-toast.show{opacity:1!important;transform:none!important}.slx-chat-toast b,.slx-chat-toast span{display:block!important}#sakalux-chat-settings-overlay{position:fixed!important;inset:0!important;z-index:2147483647!important;background:#000b!important;display:flex!important;align-items:flex-end!important;justify-content:center!important}#sakalux-chat-settings-overlay section{width:min(560px,100%)!important;background:#101821!important;color:#eee!important;border-radius:18px 18px 0 0!important;padding:12px!important}#sakalux-chat-settings-overlay header{display:flex!important;justify-content:space-between!important}#sakalux-chat-settings-overlay label{display:flex!important;justify-content:space-between!important;padding:10px!important;border-bottom:1px solid #26384d!important}';document.head.appendChild(s)}
function init(){css();bridge();window[API]={id:ID,version:V,open:settings,refresh:scan,setEnabled,toggleEnabled:()=>setEnabled(!C.enabled),isEnabled:()=>C.enabled,health:()=>({id:ID,version:V,enabled:C.enabled,chatRoots:roots().length,enhancedMessages:document.querySelectorAll('.slx-chat-message').length})};if(C.enabled){start();scan();setTimeout(scan,1200)}window.dispatchEvent(new CustomEvent('SakaLuX:ModuleReady',{detail:{id:ID,version:V,apiGlobal:API}}))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();