// ==UserScript==
// @name         SakaLuX Bounty Hunter
// @namespace    sakalux.bounty.hunter
// @version      0.1.0
// @description  Mobile-first Torn bounty scanner with Safe/Profit modes, grouped rewards, watchlist, blacklist and Hub integration.
// @author       SakaLuX [2380374]
// @match        https://www.torn.com/*
// @grant        none
// @license      All Rights Reserved
// @downloadURL  https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Bounty-Hunter.user.js
// @updateURL    https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Bounty-Hunter.user.js
// @homepage     https://github.com/SakaLuX/SakaLuX-Script-HUB
// ==/UserScript==
(()=>{'use strict';
const VERSION='0.1.0',ID='bounty-hunter',API='SakaLuXBountyHunter';
const KS='SLX_BOUNTY_SETTINGS_V1',KW='SLX_BOUNTY_WATCH_V1',KB='SLX_BOUNTY_BLACK_V1';
const D={enabled:true,mode:'safe',minReward:50000,maxLevel:100,okay:true,hospital:true,hideUnknown:false,autoRefresh:true,refreshSec:20,compact:true};
const J=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},W=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},N=v=>String(v??'').replace(/\s+/g,' ').trim();
let S={...D,...J(KS,{})},WATCH=J(KW,{}),BLACK=J(KB,{}),timer=0,lastRows=[];
const save=()=>W(KS,S),saveLists=()=>{W(KW,WATCH);W(KB,BLACK)};
function money(t){const a=[...String(t||'').matchAll(/\$\s*([\d,.]+)\s*([kmbt])?/ig)];let best=0;for(const m of a){let n=Number(m[1].replace(/,/g,''));const u=(m[2]||'').toLowerCase();if(u==='k')n*=1e3;if(u==='m')n*=1e6;if(u==='b')n*=1e9;if(u==='t')n*=1e12;if(Number.isFinite(n))best=Math.max(best,n)}return best}
function fmt(n){if(n>=1e9)return'$'+(n/1e9).toFixed(n>=1e10?1:2)+'B';if(n>=1e6)return'$'+(n/1e6).toFixed(n>=1e7?1:2)+'M';if(n>=1e3)return'$'+Math.round(n/1e3)+'K';return'$'+Math.round(n||0).toLocaleString()}
function onBounties(){return /\/bounties\.php/i.test(location.pathname)||/bount/i.test(document.title)}
function idFrom(a){const s=(a?.href||'')+' '+(a?.getAttribute?.('href')||'');return (s.match(/[?&](?:XID|userID)=(\d+)/i)||[])[1]||''}
function parseLevel(t){const m=String(t).match(/(?:level|lvl)\s*[:#-]?\s*(\d{1,3})/i);return m?Number(m[1]):null}
function statusOf(t){t=N(t);if(/hospital/i.test(t))return'Hospital';if(/okay|healthy|available/i.test(t))return'Okay';if(/jail/i.test(t))return'Jail';if(/travel|abroad|flying/i.test(t))return'Abroad';return'Unknown'}
function rowFor(a){let n=a;for(let i=0;i<8&&n?.parentElement;i++,n=n.parentElement){const q=n.getBoundingClientRect?.();const txt=N(n.innerText);if(q&&q.width>180&&q.height>28&&q.height<280&&/\$/.test(txt))return n}return a.parentElement}
function scanDom(){if(!onBounties())return[];const map=new Map();for(const a of document.querySelectorAll('a[href*="profiles.php"],a[href*="XID="],a[href*="userID="]')){const id=idFrom(a);if(!id)continue;const row=rowFor(a);if(!row)continue;const text=N(row.innerText),reward=money(text);if(!reward)continue;const name=N(a.textContent).replace(/\[\d+\]$/,'').trim()||('Player '+id),level=parseLevel(text),status=statusOf(text),atk=row.querySelector('a[href*="loader.php"][href*="attack"],a[href*="sid=attack"]');const old=map.get(id)||{id,name,level,status,reward:0,count:0,row,attack:atk?.href||('https://www.torn.com/loader.php?sid=attack&user2ID='+id)};old.reward+=reward;old.count++;if(old.status==='Unknown'&&status!=='Unknown')old.status=status;if(old.level==null&&level!=null)old.level=level;map.set(id,old)}lastRows=[...map.values()];return lastRows}
function allowed(x){if(BLACK[x.id])return false;if(x.reward<Number(S.minReward||0))return false;if(x.level!=null&&x.level>Number(S.maxLevel||100))return false;if(S.hideUnknown&&x.status==='Unknown')return false;if(x.status==='Okay'&&!S.okay)return false;if(x.status==='Hospital'&&!S.hospital)return false;if(['Jail','Abroad'].includes(x.status))return false;if(S.mode==='safe'&&x.status!=='Okay'&&x.status!=='Hospital')return false;return true}
function score(x){if(S.mode==='profit')return x.reward*(x.status==='Okay'?1.15:x.status==='Hospital'?.9:.55);return (x.status==='Okay'?1e15:x.status==='Hospital'?5e14:0)+x.reward}
function filtered(){return scanDom().filter(allowed).sort((a,b)=>score(b)-score(a)||b.reward-a.reward)}
function ensureCss(){if(document.getElementById('slx-bh-css'))return;const s=document.createElement('style');s.id='slx-bh-css';s.textContent=`#slx-bh-btn{position:fixed;right:12px;bottom:92px;z-index:2147482000;width:48px;height:48px;border:1px solid #56677b;border-radius:14px;background:#172331;color:#fff;font-size:24px;box-shadow:0 8px 26px #0009}#slx-bh{position:fixed;inset:0;z-index:2147483600;background:#000b;display:flex;align-items:flex-end;justify-content:center}#slx-bh>section{width:min(680px,100%);max-height:88dvh;display:flex;flex-direction:column;background:#101820;color:#edf3fa;border:1px solid #394c61;border-radius:16px 16px 0 0;overflow:hidden}#slx-bh header{display:flex;align-items:center;gap:8px;padding:10px;background:#182431}#slx-bh header b{flex:1}#slx-bh button,#slx-bh input,#slx-bh select{min-height:36px;border:1px solid #3d5066;border-radius:8px;background:#172331;color:#edf3fa}#slx-bh header button{width:38px}#slx-bh .bar{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;padding:8px}#slx-bh .bar label{font-size:10px;color:#9fb0c2}#slx-bh .bar input,#slx-bh .bar select{width:100%;box-sizing:border-box;padding:6px}#slx-bh .tog{display:flex;gap:6px;padding:0 8px 8px;flex-wrap:wrap}.slx-bh-chip{padding:6px 9px!important;min-height:30px!important}.slx-bh-chip.on{border-color:#59d98a!important;color:#7ee5a5!important}.slx-bh-list{overflow:auto;padding:8px;display:flex;flex-direction:column;gap:7px}.slx-bh-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px;border:1px solid #34465b;border-radius:10px;background:#15202b}.slx-bh-row .name{font-weight:800}.slx-bh-row .meta{font-size:11px;color:#9fb0c2;margin-top:3px}.slx-bh-row .money{font-weight:900;color:#78df9d}.slx-bh-actions{display:flex;gap:5px;align-items:center}.slx-bh-actions button,.slx-bh-actions a{display:grid;place-items:center;min-width:36px;height:34px;border:1px solid #3d5066;border-radius:8px;background:#1b2b3a;color:#fff;text-decoration:none}.slx-bh-empty{padding:20px;text-align:center;color:#9fb0c2}.slx-bh-foot{display:flex;justify-content:space-between;gap:8px;padding:8px;border-top:1px solid #2f4052;font-size:11px;color:#9fb0c2}@media(max-width:480px){#slx-bh .bar{grid-template-columns:1fr 1fr}.slx-bh-row{grid-template-columns:1fr}.slx-bh-actions{justify-content:flex-end}}`;document.head.appendChild(s)}
function button(){ensureCss();let b=document.getElementById('slx-bh-btn');if(!b){b=document.createElement('button');b.id='slx-bh-btn';b.textContent='🎯';b.title='SakaLuX Bounty Hunter';b.onclick=open;document.body.appendChild(b)}b.hidden=!S.enabled||!onBounties()}
function chip(label,on,fn){const b=document.createElement('button');b.className='slx-bh-chip'+(on?' on':'');b.textContent=label;b.onclick=fn;return b}
function render(){const o=document.getElementById('slx-bh');if(!o)return;const list=o.querySelector('.slx-bh-list'),rows=filtered();list.innerHTML='';if(!rows.length){list.innerHTML='<div class="slx-bh-empty">No matching bounties on the currently loaded board.</div>'}for(const x of rows.slice(0,150)){const r=document.createElement('div');r.className='slx-bh-row';const left=document.createElement('div');left.innerHTML='<div class="name">'+x.name.replace(/[<>]/g,'')+' <small>['+x.id+']</small></div><div class="meta">'+x.status+(x.level!=null?' · L'+x.level:'')+' · '+x.count+' bounty'+(x.count===1?'':'ies')+'</div><div class="money">'+fmt(x.reward)+'</div>';const a=document.createElement('div');a.className='slx-bh-actions';const atk=document.createElement('a');atk.href=x.attack;atk.textContent='⚔';atk.title='Attack';const w=document.createElement('button');w.textContent=WATCH[x.id]?'★':'☆';w.title='Watch';w.onclick=()=>{if(WATCH[x.id])delete WATCH[x.id];else WATCH[x.id]={name:x.name,addedAt:Date.now()};saveLists();render()};const bl=document.createElement('button');bl.textContent='🚫';bl.title='Blacklist';bl.onclick=()=>{BLACK[x.id]={name:x.name,addedAt:Date.now()};saveLists();render()};a.append(atk,w,bl);r.append(left,a);list.appendChild(r)}o.querySelector('[data-count]').textContent=rows.length+' matches / '+lastRows.length+' loaded'}
function open(){ensureCss();document.getElementById('slx-bh')?.remove();const o=document.createElement('div');o.id='slx-bh';o.innerHTML='<section><header><b>🎯 SakaLuX Bounty Hunter v'+VERSION+'</b><button data-r title="Refresh">↻</button><button data-x>×</button></header><div class="bar"><label>Mode<select data-mode><option value="safe">Safe</option><option value="profit">Profit</option></select></label><label>Min reward<input data-min type="number" step="10000"></label><label>Max level<input data-level type="number" min="1" max="100"></label></div><div class="tog"></div><div class="slx-bh-list"></div><div class="slx-bh-foot"><span data-count></span><span>Board DOM scanner · no API key required</span></div></section>';document.body.appendChild(o);o.querySelector('[data-x]').onclick=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)o.remove()});const mode=o.querySelector('[data-mode]'),min=o.querySelector('[data-min]'),lev=o.querySelector('[data-level]');mode.value=S.mode;min.value=S.minReward;lev.value=S.maxLevel;mode.onchange=()=>{S.mode=mode.value;save();render()};min.onchange=()=>{S.minReward=Math.max(0,Number(min.value)||0);save();render()};lev.onchange=()=>{S.maxLevel=Math.max(1,Math.min(100,Number(lev.value)||100));save();render()};const tg=o.querySelector('.tog');const rebuild=()=>{tg.innerHTML='';tg.append(chip('Okay',S.okay,()=>{S.okay=!S.okay;save();rebuild();render()}),chip('Hospital',S.hospital,()=>{S.hospital=!S.hospital;save();rebuild();render()}),chip('Hide unknown',S.hideUnknown,()=>{S.hideUnknown=!S.hideUnknown;save();rebuild();render()}),chip('Auto '+S.refreshSec+'s',S.autoRefresh,()=>{S.autoRefresh=!S.autoRefresh;save();schedule();rebuild()}),chip('Clear blacklist ('+Object.keys(BLACK).length+')',false,()=>{BLACK={};saveLists();rebuild();render()}))};rebuild();o.querySelector('[data-r]').onclick=render;render()}
function schedule(){clearInterval(timer);timer=0;if(S.enabled&&S.autoRefresh)timer=setInterval(()=>{if(onBounties()){button();if(document.getElementById('slx-bh'))render()}},Math.max(10,Number(S.refreshSec)||20)*1000)}
function enable(v){S.enabled=!!v;save();button();schedule();bridge();return S.enabled}
function bridge(){let b=document.getElementById('sakalux-module-bridge-'+ID);if(!b){b=document.createElement('button');b.id='sakalux-module-bridge-'+ID;b.hidden=true;b.style.display='none';b.onclick=()=>{const a=b.dataset.action;if(a==='open')open();else if(a==='on')enable(true);else if(a==='off')enable(false);else if(a==='toggle')enable(!S.enabled);else if(a==='refresh')render();b.dataset.action=''};document.documentElement.appendChild(b)}b.dataset.version=VERSION;b.dataset.enabled=String(S.enabled);b.dataset.ready='true'}
function go(){location.href='https://www.torn.com/bounties.php'}
function init(){ensureCss();button();bridge();schedule();window[API]={id:ID,version:VERSION,open,refresh:render,goToBounties:go,setEnabled:enable,toggleEnabled:()=>enable(!S.enabled),isEnabled:()=>S.enabled,health:()=>({version:VERSION,onBounties:onBounties(),loaded:lastRows.length,watch:Object.keys(WATCH).length,blacklist:Object.keys(BLACK).length})};addEventListener('hashchange',()=>setTimeout(button,300));setInterval(button,2500);dispatchEvent(new CustomEvent('SakaLuX:ModuleReady',{detail:{id:ID,version:VERSION,apiGlobal:API}}))}
document.readyState==='loading'?addEventListener('DOMContentLoaded',init,{once:true}):init();
})();