// ==UserScript==
// @name         SakaLuX Market Intelligence
// @namespace    sakalux.market.intelligence
// @version      1.8.0
// @description  Torn market and travel intelligence with Travel Buy Planner, budget-aware shopping plans, real flight-time detection, Bazaar Flip Intelligence, Item Market trend/signals, arrival prediction and Museum valuation.
// @author       SakaLuX
// @match        https://www.torn.com/*
// @grant        GM_xmlhttpRequest
// @connect      api.torn.com
// @connect      yata.yt
// @connect      raw.githubusercontent.com
// @license      MIT
// @run-at       document-end
// @downloadURL  https://update.greasyfork.org/scripts/592781/SakaLuX%20Market%20Intelligence.user.js
// @updateURL    https://update.greasyfork.org/scripts/592781/SakaLuX%20Market%20Intelligence.meta.js
// ==/UserScript==

(function () {
    'use strict';

    const VERSION = '1.8.0';
    const NAME = 'SakaLuX Market Intelligence';
    const PDA_KEY = '###PDA-APIKEY###';
    const HUB_INSTALL_URL = 'https://update.greasyfork.org/scripts/592699/SakaLuX%20Script%20Hub.user.js';
    const HUB_PROMPT_STORAGE = 'SakaLuX_HUB_INSTALL_PROMPT_LAST';
    const HUB_PROMPT_INTERVAL = 24 * 60 * 60 * 1000;
    const YATA_EXPORT_URL = 'https://yata.yt/api/v1/travel/export/';

    const STORAGE = {
        apiKey: 'SakaLuX_MI_API_KEY',
        settings: 'SakaLuX_MI_SETTINGS_V2',
        marketCache: 'SakaLuX_MI_MARKET_CACHE_V1',
        watchlist: 'SakaLuX_MI_WATCHLIST_V1',
        pointsRate: 'SakaLuX_MI_POINTS_RATE_V1',
        stockHistory: 'SakaLuX_MI_STOCK_HISTORY_V1',
        itemCatalog: 'SakaLuX_MI_ITEM_CATALOG_V1',
        priceHistory: 'SakaLuX_MI_PRICE_HISTORY_V1'
    };

    const MARKET_CACHE_MS = 10 * 60 * 1000;
    const TRAVEL_CACHE_MAX_STALE_MS = 6 * 60 * 60 * 1000;
    const TRAVEL_REFRESH_LIMIT = 15;
    const ARRIVAL_REFRESH_LIMIT = 12;
    const MAX_LIVE_FETCHES = 45;
    const CONCURRENCY = 6;
    const MAX_HISTORY_EVENTS = 8;
    const STOCK_HISTORY_MAX_AGE = 30 * 24 * 60 * 60 * 1000;
    const ITEM_CATALOG_MAX_AGE = 30 * 24 * 60 * 60 * 1000;
    const POINTS_RATE_MAX_AGE = 24 * 60 * 60 * 1000;
    const PRICE_HISTORY_MAX_AGE = 14 * 24 * 60 * 60 * 1000;
    const PRICE_HISTORY_MAX_SAMPLES = 120;
    const PRICE_HISTORY_MIN_GAP = 5 * 60 * 1000;

    const FLIGHT_MINS = {
        Mexico: 25, Caymans: 33, Canada: 39, Hawaii: 127, UK: 151,
        Argentina: 158, Switzerland: 166, Japan: 213, China: 229,
        UAE: 257, 'South Africa': 281
    };

    const YATA_COUNTRY_MAP = {
        mex: 'Mexico', cay: 'Caymans', can: 'Canada', haw: 'Hawaii',
        uni: 'UK', arg: 'Argentina', swi: 'Switzerland', jap: 'Japan',
        chi: 'China', uae: 'UAE', sou: 'South Africa'
    };

    const MUSEUM_SETS = [
        { id:'arrowheads', name:'Arrowhead Set', points:25, members:[{name:'Chert Point',qty:1},{name:'Quartzite Point',qty:1},{name:'Basalt Point',qty:1},{name:'Obsidian Point',qty:1},{name:'Quartz Point',qty:1},{name:'Chalcedony Point',qty:1}]},
        { id:'medieval-coins', name:'Medieval Coin Set', points:100, members:[{name:'Leopard Coin',qty:1},{name:'Florin Coin',qty:1},{name:'Gold Noble Coin',qty:1}]},
        { id:'patagonian-fossil', name:'Patagonian Fossil', points:20, members:[{name:'Patagonian Fossil',qty:1}] },
        { id:'meteorite-fragment', name:'Meteorite Fragment', points:15, members:[{name:'Meteorite Fragment',qty:1}] },
        { id:'vairocana-buddha', name:'Vairocana Buddha', points:100, members:[{name:'Vairocana Buddha Sculpture',qty:1}] },
        { id:'ganesha', name:'Ganesha Sculpture', points:250, members:[{name:'Ganesha Sculpture',qty:1}] },
        { id:'shabti', name:'Shabti Sculpture', points:500, members:[{name:'Shabti Sculpture',qty:1}] },
        { id:'senet', name:'Senet Game Set', points:2000, members:[{name:'Senet Board',qty:1},{name:'White Senet Pawn',qty:5},{name:'Black Senet Pawn',qty:5}]},
        { id:'companion-scripts', name:'Companion Script Set', points:1000, members:[{name:'Companion Script : Abdullah',qty:1},{name:'Companion Script : Ali',qty:1},{name:'Companion Script : Ubay',qty:1}]},
        { id:'egyptian-amulet', name:'Egyptian Amulet', points:10000, members:[{name:'Egyptian Amulet',qty:1}] }
    ];

    const TORN_TRAVEL_LABELS = {
        Mexico: ['Mexico'], Caymans: ['Cayman Islands', 'Caymans'], Canada: ['Canada'], Hawaii: ['Hawaii'], UK: ['United Kingdom', 'UK'],
        Argentina: ['Argentina'], Switzerland: ['Switzerland'], Japan: ['Japan'], China: ['China'], UAE: ['UAE', 'United Arab Emirates'], 'South Africa': ['South Africa']
    };

    const DEFAULT_SETTINGS = {
        enabled: true, travel: true, bestRun: true, stockEta: true, arrivalStock: true, bazaar: true, itemMarket: true, items: true, museum: true, points: true,
        showButton: true, marketFeePct: 5, minProfit: 0, travelSlots: 29, travelBudget: 0, flightMultiplier: 1
    };

    let settings = Object.assign({}, DEFAULT_SETTINGS, loadJson(STORAGE.settings, {}));
    let marketCache = loadJson(STORAGE.marketCache, {});
    let watchlist = loadJson(STORAGE.watchlist, {});
    let stockHistory = loadJson(STORAGE.stockHistory, {});
    let priceHistory = loadJson(STORAGE.priceHistory, {});

    const state = {
        page: '', apiMode: '', busy: false, lastScan: 0, lastError: '', scanCount: 0, marketRequests: 0, decorated: 0, observer: null, scanTimer: null,
        bestRunRows: 0, stockEtaLearned: 0, arrivalRows: 0, flightDestination: '', landingMins: null,
        travelCacheHits: 0, travelRefreshes: 0, observerSkips: 0, lastObserverScan: 0, museumSets: 0, museumRecommendation: '', museumMissingSets: 0,
        bazaarDeals: 0, bazaarBestProfit: 0, bazaarBestRoi: 0, itemMarketSignal: '', itemMarketTrend: 0, itemMarketVolatility: 0, itemMarketHistorySamples: 0,
        actualFlightTimes: 0, travelTimeSource: 'fallback', travelPlanItems: 0, travelPlanCost: 0, travelPlanProfit: 0, travelPlanSlots: 0, travelPlanBudget: 0, travelPlanUnusedBudget: 0
    };

    function loadJson(key, fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(_){return fallback;}}
    function saveJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(_){}}
    function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
    function money(v){const n=Number(v);if(!Number.isFinite(n))return'?';return(n<0?'-':'')+'$'+Math.round(Math.abs(n)).toLocaleString('en-US');}
    function pct(v){const n=Number(v);if(!Number.isFinite(n))return'?';return(n>=0?'+':'')+n.toFixed(1)+'%';}
    function parseMoney(text){const s=String(text||'').replace(/[^0-9]/g,'');return s?Number(s):NaN;}
    function fmtDuration(mins){if(mins==null||!Number.isFinite(mins))return'learning';mins=Math.max(0,Math.round(mins));if(mins<60)return'~'+mins+'m';const h=Math.floor(mins/60),m=mins%60;return'~'+h+'h'+(m?' '+m+'m':'');}
    function normText(text){return String(text||'').replace(/\s+/g,' ').trim();}
    function median(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null;}

    function museumNameKey(name){return normText(name).toLowerCase().replace(/\s*:\s*/g,':');}
    function museumDomCatalog(){const map=new Map();document.querySelectorAll('img[src*="/images/items/"]').forEach(img=>{const id=itemIdFromImg(img);if(!id)return;const row=rowContainer(img);const raw=normText(img.getAttribute('alt')||'')||normText((row?.innerText||'').split('\n')[0]);if(raw)map.set(museumNameKey(raw),{id,name:raw,source:'museum-dom'});});return map;}
    async function loadMuseumCatalog(){const merged=museumDomCatalog();const cached=loadJson(STORAGE.itemCatalog,null);if(cached?.items&&cached?.at&&Date.now()-cached.at<ITEM_CATALOG_MAX_AGE){for(const item of cached.items){if(item?.id&&item?.name)merged.set(museumNameKey(item.name),item);}return merged;}const key=getApiKey();if(!key)return merged;try{const data=await requestJson('https://api.torn.com/torn/?selections=items&key='+encodeURIComponent(key));checkApiError(data);const items=[];for(const [id,meta] of Object.entries(data?.items||{})){const n=Number(id);if(!n||!meta?.name)continue;const item={id:n,name:meta.name,type:meta.type||'',source:'torn-catalog'};items.push(item);merged.set(museumNameKey(item.name),item);}if(items.length)saveJson(STORAGE.itemCatalog,{at:Date.now(),items});}catch(_){}return merged;}
    function freshPointsRate(){const row=loadJson(STORAGE.pointsRate,null);if(!row?.rate||!row?.at)return null;if(Date.now()-Number(row.at)>POINTS_RATE_MAX_AGE)return null;return Number(row.rate)||null;}
    function normalizeDestination(value){const text=normText(value).toLowerCase();if(!text)return null;for(const [key,labels] of Object.entries(TORN_TRAVEL_LABELS)){if(key.toLowerCase()===text||labels.some(v=>v.toLowerCase()===text))return key;}if(text.includes('cayman'))return'Caymans';if(text==='united kingdom'||text==='uk')return'UK';if(text.includes('united arab')||text==='uae')return'UAE';if(text.includes('south africa'))return'South Africa';for(const key of Object.keys(FLIGHT_MINS))if(text.includes(key.toLowerCase()))return key;return null;}
    function getApiKey(){if(PDA_KEY&&PDA_KEY!=='###PDA-APIKEY###'){state.apiMode='Torn PDA';return PDA_KEY;}try{const key=localStorage.getItem(STORAGE.apiKey)||'';if(key)state.apiMode='Manual';return key;}catch(_){return'';}}
    function saveApiKey(key){try{localStorage.setItem(STORAGE.apiKey,key);state.apiMode='Manual';}catch(_){}}
    function requestJson(url){return new Promise((resolve,reject)=>{if(typeof window.PDA_httpGet==='function'){state.apiMode='Torn PDA';window.PDA_httpGet(url,{Accept:'application/json'}).then(r=>{try{if(typeof r==='string')return resolve(JSON.parse(r));const raw=r?.responseText??r?.body??r?.data??r;resolve(typeof raw==='string'?JSON.parse(raw):raw);}catch(e){reject(e);}}).catch(reject);return;}if(typeof GM_xmlhttpRequest==='function'){state.apiMode=state.apiMode||'Tampermonkey';GM_xmlhttpRequest({method:'GET',url,timeout:15000,headers:{Accept:'application/json'},onload:r=>{try{resolve(JSON.parse(r.responseText));}catch(e){reject(e);}},onerror:()=>reject(new Error('Network error')),ontimeout:()=>reject(new Error('Request timeout'))});return;}fetch(url).then(r=>r.json()).then(resolve).catch(reject);});}
    function checkApiError(data){if(data?.error)throw new Error(data.error.error||data.error.message||'Torn API error');}
    function detectPage(){const u=location.href;if(/sid=travel/i.test(u))return'travel';if(/sid=ItemMarket/i.test(u))return'itemmarket';if(/bazaar\.php/i.test(u))return'bazaar';if(/item\.php/i.test(u))return'items';if(/museum\.php/i.test(u))return'museum';if(/pmarket\.php/i.test(u))return'points';return'other';}
    function detectDestination(){const body=document.body?.innerText||'';const m=body.match(/You are in ([A-Z][A-Za-z ]+?) and have/);return m?normalizeDestination(m[1]):null;}
    function detectInFlight(){const body=document.body?.innerText||'';return/Remaining Flight Time/i.test(body)||/Traveling from .* to /i.test(body);}
    function parseClockToSeconds(text){const m=String(text||'').match(/(\d{1,2}):(\d{2})(?::(\d{2}))?/);if(!m)return null;if(m[3]!=null)return Number(m[1])*3600+Number(m[2])*60+Number(m[3]);return Number(m[1])*60+Number(m[2]);}
    function detectFlightFromDom(){const body=document.body?.innerText||'';let destination=null,seconds=null;const to=body.match(/Traveling\s+(?:from\s+.+?\s+)?to\s+([A-Za-z ]+?)(?:\n|Remaining|$)/i);if(to)destination=normalizeDestination(to[1]);const rt=body.match(/Remaining Flight Time[^0-9]*(\d{1,2}:\d{2}(?::\d{2})?)/i);if(rt)seconds=parseClockToSeconds(rt[1]);return{destination,seconds,source:'page'};}
    async function fetchFlightStatus(){const fallback=detectFlightFromDom();const key=getApiKey();if(!key)return fallback;try{const data=await requestJson('https://api.torn.com/user/?selections=travel&key='+encodeURIComponent(key));checkApiError(data);const travel=data?.travel||{};const destination=normalizeDestination(travel.destination)||fallback.destination;let seconds=Number(travel.time_left);if(!Number.isFinite(seconds)||seconds<0){const ts=Number(travel.timestamp);seconds=Number.isFinite(ts)&&ts>0?Math.max(0,ts-Math.floor(Date.now()/1000)):fallback.seconds;}return{destination,seconds:Number.isFinite(seconds)?seconds:fallback.seconds,source:'Torn API'};}catch(_){return fallback;}}
    function isVisible(el){if(!el||!(el instanceof Element))return false;const r=el.getBoundingClientRect();if(r.width===0&&r.height===0)return false;const s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden';}
    function parseTravelDurationMinutes(text){const t=normText(text);let m=t.match(/\b(\d{1,2}):(\d{2})(?::(\d{2}))?\b/);if(m){const total=Number(m[1])*60+Number(m[2])+(m[3]?Number(m[3])/60:0);if(total>=1&&total<=600)return total;}m=t.match(/\b(\d+)\s*h(?:ours?)?\s*(?:(\d+)\s*m(?:in(?:ute)?s?)?)?/i);if(m){const total=Number(m[1])*60+Number(m[2]||0);if(total>=1&&total<=600)return total;}m=t.match(/\b(\d+)\s*m(?:in(?:ute)?s?)\b/i);if(m){const total=Number(m[1]);if(total>=1&&total<=600)return total;}return null;}
    function fmtFlightMinutes(mins){const n=Math.max(0,Math.round(Number(mins)||0));if(n<60)return n+'m';const h=Math.floor(n/60),m=n%60;return h+'h'+(m?' '+m+'m':'');}
    function scrapeTravelTimes(){const found=new Map();const nodes=[...document.querySelectorAll('tr,li,[role="row"],a,button,[class*="destination"],[class*="travel"],[class*="row"],[class*="Row"]')];for(const destination of Object.keys(FLIGHT_MINS)){const labels=TORN_TRAVEL_LABELS[destination]||[destination];let best=null;for(const el of nodes){if(!isVisible(el))continue;const text=normText(el.innerText||el.textContent);if(!text||text.length>260)continue;const lower=text.toLowerCase();if(!labels.some(label=>lower.includes(label.toLowerCase())))continue;const mins=parseTravelDurationMinutes(text);if(!Number.isFinite(mins))continue;const score=text.length+(el.children?.length||0)*2;if(!best||score<best.score)best={mins,score,text};}if(best)found.set(destination,{mins:best.mins,source:'torn-page'});}return found;}
    function flightInfo(destination,actualMap){const actual=actualMap?.get(destination);if(actual&&Number.isFinite(actual.mins))return actual;const base=Number(FLIGHT_MINS[destination]);if(!Number.isFinite(base))return null;return{mins:base*Math.max(0.1,Number(settings.flightMultiplier)||1),source:'fallback'};}
    function selectTravelDestination(destination){if(detectPage()!=='travel'||detectDestination()||detectInFlight())return false;const labels=TORN_TRAVEL_LABELS[destination]||[destination];const candidates=[];for(const el of document.querySelectorAll('a,button,[role="button"],li,tr,div')){if(!isVisible(el))continue;const text=normText(el.innerText||el.textContent);if(!text||text.length>180)continue;const lower=text.toLowerCase();if(labels.some(label=>lower===label.toLowerCase()||lower.startsWith(label.toLowerCase()+' ')))candidates.push({el,textLen:text.length,area:Math.max(1,el.getBoundingClientRect().width*el.getBoundingClientRect().height)});}candidates.sort((a,b)=>a.textLen-b.textLen||a.area-b.area);const seed=candidates[0]?.el;if(!seed)return false;const target=seed.closest('a,button,[role="button"],li,tr')||seed;try{target.scrollIntoView({behavior:'smooth',block:'center'});}catch(_){}setTimeout(()=>{try{target.click();}catch(_){}},120);return true;}
    function rowContainer(img){return img.closest('tr')||img.closest('li')||img.closest('[class*="row"]')||img.closest('[class*="Row"]')||img.closest('[class*="item"]')||img.parentElement?.parentElement||img.parentElement;}
    function itemIdFromImg(img){const m=(img?.getAttribute('src')||'').match(/\/images\/items\/(\d+)\//);return m?Number(m[1]):null;}
    function extractFirstPrice(node){const txt=(node?.innerText||node?.textContent||'').replace(/\s+/g,' ');const m=txt.match(/\$\s*([\d,.]+)/);return m?parseMoney(m[1]):NaN;}
    function extractStock(node){const txt=(node?.innerText||'').replace(/\$\s*[\d,.]+/g,' ');const nums=txt.match(/\b\d[\d,]*\b/g)||[];if(!nums.length)return null;const vals=nums.map(x=>Number(x.replace(/,/g,''))).filter(Number.isFinite);return vals.length?Math.max(...vals):null;}
    function cacheGet(itemId){const row=marketCache[String(itemId)];if(!row||!row.at||Date.now()-row.at>MARKET_CACHE_MS)return null;return row;}
    function cachePeek(itemId,maxAge=TRAVEL_CACHE_MAX_STALE_MS){const row=marketCache[String(itemId)];if(!row||!row.at||Date.now()-row.at>maxAge)return null;return row;}
    function cachePut(itemId,row){marketCache[String(itemId)]=Object.assign({},row,{at:Date.now()});saveJson(STORAGE.marketCache,marketCache);}
    async function fetchMarket(itemId,force=false){if(!force){const c=cacheGet(itemId);if(c)return c;}const key=getApiKey();if(!key)return null;state.marketRequests++;const data=await requestJson('https://api.torn.com/v2/market/'+encodeURIComponent(itemId)+'/itemmarket?key='+encodeURIComponent(key));checkApiError(data);const listings=Array.isArray(data?.itemmarket?.listings)?data.itemmarket.listings:(Array.isArray(data?.itemmarket)?data.itemmarket:[]);const norm=listings.map(l=>({price:Number(l.price??l.cost??0),qty:Number(l.amount??l.quantity??1)})).filter(l=>l.price>0).sort((a,b)=>a.price-b.price);if(!norm.length)return null;const effective=norm.find(l=>l.qty>=2)||norm[0];const row={price:effective.price,minPrice:norm[0].price,qty:effective.qty,count:norm.length};cachePut(itemId,row);return row;}
    async function mapWithLimit(items,fn){const out=new Array(items.length);let i=0;async function worker(){while(i<items.length){const idx=i++;try{out[idx]=await fn(items[idx],idx);}catch(_){out[idx]=null;}}}const workers=[];for(let w=0;w<Math.min(CONCURRENCY,items.length);w++)workers.push(worker());await Promise.all(workers);return out;}
    function metrics(buyPrice,marketPrice){const fee=Math.max(0,Number(settings.marketFeePct)||0)/100;const net=marketPrice*(1-fee);const profit=net-buyPrice;return{net,profit,roi:buyPrice>0?profit/buyPrice*100:0};}
    function stockKey(destination,itemId){return destination+'|'+itemId;}
    function nextQuarterHourMins(now=Date.now()){const tick=15*60*1000;return(Math.ceil(now/tick)*tick-now)/60000;}
    function recordStock(destination,itemId,stock,now=Date.now()){if(!destination||!Number.isFinite(Number(stock)))return;const key=stockKey(destination,itemId),qty=Number(stock);let h=stockHistory[key]||{last:null,restocks:[],restockQty:[]};if(!Array.isArray(h.restocks))h.restocks=[];if(!Array.isArray(h.restockQty))h.restockQty=[];if(h.last&&Number.isFinite(h.last.qty)&&qty>h.last.qty){const delta=qty-h.last.qty;h.restocks=h.restocks.filter(t=>now-t<STOCK_HISTORY_MAX_AGE);h.restocks.push(now);h.restocks=h.restocks.slice(-MAX_HISTORY_EVENTS);h.restockQty.push(delta);h.restockQty=h.restockQty.filter(v=>Number.isFinite(v)&&v>0).slice(-MAX_HISTORY_EVENTS);}h.last={qty,at:now};stockHistory[key]=h;}
    function restockStats(destination,itemId,now=Date.now()){const h=stockHistory[stockKey(destination,itemId)];const events=(h?.restocks||[]).filter(t=>Number.isFinite(t)&&now-t<STOCK_HISTORY_MAX_AGE).sort((a,b)=>a-b);const gaps=[];for(let i=1;i<events.length;i++){const g=(events[i]-events[i-1])/60000;if(g>0&&g<24*60)gaps.push(g);}return{events,gaps,medGap:median(gaps),medQty:median((h?.restockQty||[]).map(Number).filter(v=>v>0)),samples:events.length};}
    function estimateRestock(destination,itemId,now=Date.now()){const stats=restockStats(destination,itemId,now);if(stats.medGap&&stats.events.length>=2){const last=stats.events[stats.events.length-1];let target=last+stats.medGap*60000;while(target<=now)target+=stats.medGap*60000;state.stockEtaLearned++;return{mins:(target-now)/60000,learned:true,samples:stats.events.length,gap:stats.medGap,qty:stats.medQty};}return{mins:nextQuarterHourMins(now),learned:false,samples:stats.events.length,gap:null,qty:stats.medQty};}
    function predictAtArrival(destination,itemId,currentStock,landingMins,now=Date.now()){const stock=Number(currentStock),horizon=Math.max(0,Number(landingMins)||0),e=estimateRestock(destination,itemId,now);let expectedRestocks=0,confidence='LOW',projected=Number.isFinite(stock)?stock:null;if(e.learned&&e.gap>0){if(e.mins<=horizon)expectedRestocks=1+Math.floor(Math.max(0,horizon-e.mins)/e.gap);confidence=e.samples>=5?'HIGH':e.samples>=3?'MEDIUM':'LOW';if(projected!=null&&e.qty&&expectedRestocks>0)projected+=e.qty*expectedRestocks;}else{expectedRestocks=Math.max(0,Math.floor((horizon-nextQuarterHourMins(now))/15)+1);confidence='LEARNING';}return{current:projected==null?null:stock,projected,expectedRestocks,confidence,eta:e};}
    function stockEtaText(destination,itemId,stock){if(!settings.stockEta)return'';const e=estimateRestock(destination,itemId);if(e.learned)return' · next stock '+fmtDuration(e.mins);if(Number(stock)===0)return' · possible restock ≤'+Math.max(1,Math.ceil(e.mins))+'m';return' · restock ETA learning';}
    function flushStockHistory(){saveJson(STORAGE.stockHistory,stockHistory);}
    async function fetchYataAll(){const data=await requestJson(YATA_EXPORT_URL);const countries=data?.stocks||data||{},rows=[];for(const code of Object.keys(countries)){const destination=YATA_COUNTRY_MAP[code];if(!destination)continue;const arr=countries[code]?.stocks||countries[code]||[];if(!Array.isArray(arr))continue;for(const s of arr){const id=Number(s.id),buy=Number(s.cost),stock=Number(s.quantity);if(!id||!(buy>0))continue;rows.push({itemId:id,name:s.name||('Item #'+id),destination,buyPrice:buy,stock:Number.isFinite(stock)?stock:null});}}return rows;}
    function ensureBadge(row,cls){let box=row.querySelector(':scope > .'+cls);if(!box){box=document.createElement('div');box.className=cls;row.appendChild(box);}return box;}
    function buildBestRunRows(candidates,marketMap,actualTimes){const slots=Math.max(1,Number(settings.travelSlots)||29),ranked=[];for(const r of candidates){const market=marketMap.get(r.itemId),flight=flightInfo(r.destination,actualTimes);if(!market||!flight)continue;const m=metrics(r.buyPrice,market.price);if(m.profit<=0)continue;const qty=r.stock==null?slots:Math.min(slots,r.stock);if(qty<=0)continue;const profitRun=m.profit*qty,roundTrip=flight.mins*2,profitHour=profitRun/(roundTrip/60);ranked.push(Object.assign({},r,{market:market.price,net:m.net,profitItem:m.profit,roi:m.roi,qty,profitRun,profitHour,flightMins:flight.mins,flightSource:flight.source,eta:estimateRestock(r.destination,r.itemId)}));}return ranked.sort((a,b)=>b.profitHour-a.profitHour).slice(0,11);}
    function paintBestTravelRun(top,phase){document.getElementById('sl-mi-best-run')?.remove();state.bestRunRows=top.length;if(!top.length)return;const bar=document.createElement('div');bar.id='sl-mi-best-run';const best=top[0];bar.innerHTML='<div class="sl-mi-br-head"><span class="sl-mi-br-title">☠︎ BEST TRAVEL RUN</span><strong>'+esc(best.name)+' → '+esc(best.destination)+'</strong><span>'+money(best.profitHour)+'/hr</span><button type="button">▾</button></div><div class="sl-mi-perf-note">'+esc(phase||'cached')+'</div><div class="sl-mi-br-body"></div>';const body=bar.querySelector('.sl-mi-br-body');for(const r of top){const row=document.createElement('div');row.className='sl-mi-br-row sl-mi-route';row.dataset.destination=r.destination;row.tabIndex=0;row.setAttribute('role','button');const eta=(r.eta.learned?('next '+fmtDuration(r.eta.mins)):('ETA learning · possible ≤'+Math.max(1,Math.ceil(r.eta.mins))+'m'))+' · flight '+fmtFlightMinutes(r.flightMins)+' '+(r.flightSource==='torn-page'?'actual':'fallback');row.innerHTML='<span class="name">'+esc(r.name)+'</span><span>'+esc(r.destination)+'</span><span>stock '+(r.stock==null?'?':Number(r.stock).toLocaleString('en-US'))+'</span><span class="eta">'+eta+'</span><span>'+money(r.profitRun)+'/run</span><strong>'+money(r.profitHour)+'/hr</strong>';const activate=()=>selectTravelDestination(r.destination);row.onclick=activate;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}};body.appendChild(row);}bar.querySelector('.sl-mi-br-head').onclick=()=>bar.classList.toggle('open');mountTop(bar);}
    function travelRefreshIds(candidates,limit,actualTimes){const scored=candidates.map(r=>{const c=cachePeek(r.itemId),flight=flightInfo(r.destination,actualTimes)?.mins||9999;let score=0;if(c){const m=metrics(r.buyPrice,c.price);score=Math.max(0,m.profit)*(Math.min(Math.max(1,Number(settings.travelSlots)||29),r.stock==null?999:r.stock))/(flight||1);}else score=Math.max(1,r.buyPrice)/Math.max(1,flight);return{id:r.itemId,score,cached:!!c};}).sort((a,b)=>(b.cached-a.cached)||(b.score-a.score));const ids=[],seen=new Set();for(const x of scored){if(seen.has(x.id))continue;seen.add(x.id);ids.push(x.id);if(ids.length>=limit)break;}return ids;}
    async function renderBestTravelRun(){document.getElementById('sl-mi-best-run')?.remove();if(!settings.bestRun||detectDestination()||detectInFlight())return;const yata=await fetchYataAll();if(!yata.length)return;const candidates=[];for(const r of yata){if(r.stock!=null)recordStock(r.destination,r.itemId,r.stock);if(r.stock===0)continue;candidates.push(r);}flushStockHistory();const actualTimes=scrapeTravelTimes();state.actualFlightTimes=actualTimes.size;state.travelTimeSource=actualTimes.size?'torn-page':'fallback';const cachedMap=new Map();for(const r of candidates){const c=cachePeek(r.itemId);if(c)cachedMap.set(r.itemId,c);}state.travelCacheHits=cachedMap.size;const cachedTop=buildBestRunRows(candidates,cachedMap,actualTimes);if(cachedTop.length)paintBestTravelRun(cachedTop,'instant cache · '+(actualTimes.size?'actual Torn times '+actualTimes.size+'/'+Object.keys(FLIGHT_MINS).length:'fallback flight times')+' · refreshing '+TRAVEL_REFRESH_LIMIT+' prices');const ids=travelRefreshIds(candidates,TRAVEL_REFRESH_LIMIT,actualTimes);state.travelRefreshes=ids.length;await mapWithLimit(ids,async id=>{const m=await fetchMarket(id,true);return m;});const finalMap=new Map();for(const r of candidates){const c=cachePeek(r.itemId);if(c)finalMap.set(r.itemId,c);}const finalTop=buildBestRunRows(candidates,finalMap,actualTimes);if(finalTop.length)paintBestTravelRun(finalTop,'live-refreshed · '+(actualTimes.size?'actual Torn flight times':'fallback flight times')+' · '+ids.length+' prices checked');}
    async function renderArrivalStock(){document.getElementById('sl-mi-arrival')?.remove();state.arrivalRows=0;state.flightDestination='';state.landingMins=null;if(!settings.arrivalStock||!detectInFlight())return;const flight=await fetchFlightStatus(),destination=normalizeDestination(flight.destination),landingMins=Number(flight.seconds)/60;if(!destination||!Number.isFinite(landingMins)||landingMins<0)return;state.flightDestination=destination;state.landingMins=landingMins;const yata=(await fetchYataAll()).filter(r=>r.destination===destination);if(!yata.length)return;for(const r of yata)if(r.stock!=null)recordStock(destination,r.itemId,r.stock);flushStockHistory();const marketMap=new Map();for(const r of yata){const c=cachePeek(r.itemId);if(c)marketMap.set(r.itemId,c);}const ids=travelRefreshIds(yata,ARRIVAL_REFRESH_LIMIT,new Map());await mapWithLimit(ids,async id=>{const m=await fetchMarket(id,true);if(m)marketMap.set(id,m);});const slots=Math.max(1,Number(settings.travelSlots)||29),rows=[];for(const r of yata){const market=marketMap.get(r.itemId);if(!market)continue;const m=metrics(r.buyPrice,market.price);if(m.profit<=0)continue;const p=predictAtArrival(destination,r.itemId,r.stock,landingMins),availableQty=p.projected==null?slots:Math.min(slots,Math.max(0,p.projected)),projectedProfit=m.profit*availableQty;rows.push(Object.assign({},r,{market:market.price,profitItem:m.profit,roi:m.roi,p,projectedProfit,score:projectedProfit}));}rows.sort((a,b)=>b.score-a.score);const top=rows.slice(0,8);state.arrivalRows=top.length;if(!top.length)return;const bar=document.createElement('div');bar.id='sl-mi-arrival';bar.className='open';bar.innerHTML='<div class="sl-mi-arrival-head"><div><span class="sl-mi-br-title">✈ ARRIVAL STOCK</span><strong>'+esc(destination)+'</strong></div><div>Landing '+fmtDuration(landingMins)+' · '+esc(flight.source)+'</div><button type="button">▾</button></div><div class="sl-mi-arrival-body"></div>';const body=bar.querySelector('.sl-mi-arrival-body');for(const r of top){const row=document.createElement('div');row.className='sl-mi-arrival-row';row.innerHTML='<span class="name">'+esc(r.name)+'</span><span>now '+(r.stock==null?'?':r.stock)+'</span><span>arrival ~'+Math.max(0,Math.round(r.p.projected||0))+'</span><span class="conf '+r.p.confidence.toLowerCase()+'">'+r.p.confidence+'</span><strong>'+money(r.projectedProfit)+'/run</strong>';body.appendChild(row);}bar.querySelector('.sl-mi-arrival-head').onclick=()=>bar.classList.toggle('open');mountTop(bar);}

    function buildTravelBuyPlan(destination,entries,marketMap){
        const slots=Math.max(1,Number(settings.travelSlots)||29);
        const configuredBudget=Math.max(0,Number(settings.travelBudget)||0);
        let budgetLeft=configuredBudget>0?configuredBudget:Infinity;
        const ranked=[];
        for(const e of entries){const market=marketMap.get(e.id);if(!market)continue;const m=metrics(e.buy,market.price);if(m.profit<=0)continue;const stock=e.stock==null?slots:Math.max(0,Number(e.stock)||0);if(stock<=0)continue;ranked.push({id:e.id,name:e.name,buy:e.buy,stock,market:market.price,profitItem:m.profit,roi:m.roi,row:e.row,efficiency:e.buy>0?m.profit/e.buy:0});}
        ranked.sort((a,b)=>b.profitItem-a.profitItem||b.efficiency-a.efficiency||b.roi-a.roi);
        let remaining=slots,totalCost=0,totalProfit=0;const plan=[];
        for(const r of ranked){if(remaining<=0||budgetLeft<=0)break;const affordable=Number.isFinite(budgetLeft)?Math.floor(budgetLeft/r.buy):remaining;const qty=Math.min(remaining,r.stock,affordable);if(qty<=0)continue;const cost=r.buy*qty,profit=r.profitItem*qty;totalCost+=cost;totalProfit+=profit;remaining-=qty;if(Number.isFinite(budgetLeft))budgetLeft-=cost;plan.push({...r,qty,cost,profit});}
        return{destination,slots,used:slots-remaining,remaining,totalCost,totalProfit,rows:plan,budget:configuredBudget,unusedBudget:configuredBudget>0?Math.max(0,configuredBudget-totalCost):null};
    }

    function paintTravelBuyPlan(plan){document.getElementById('sl-mi-travel-plan')?.remove();state.travelPlanItems=plan?.rows?.length||0;state.travelPlanCost=plan?.totalCost||0;state.travelPlanProfit=plan?.totalProfit||0;state.travelPlanSlots=plan?.used||0;state.travelPlanBudget=plan?.budget||0;state.travelPlanUnusedBudget=plan?.unusedBudget||0;if(!plan?.rows?.length)return;const bar=document.createElement('div');bar.id='sl-mi-travel-plan';bar.className='open';const budgetText=plan.budget>0?(' · budget '+money(plan.budget)):' · unlimited budget';bar.innerHTML='<div class="sl-mi-plan-head"><div><span class="sl-mi-br-title">🧳 TRAVEL BUY PLANNER</span><strong>'+esc(plan.destination)+'</strong></div><div>'+plan.used+'/'+plan.slots+' slots · '+money(plan.totalProfit)+' profit'+budgetText+'</div><button type="button">▾</button></div><div class="sl-mi-plan-note">Plan respects both your configured travel capacity and optional cash budget. Set budget to 0 for no money limit.</div><div class="sl-mi-plan-summary"><span>Spend <strong>'+money(plan.totalCost)+'</strong></span><span>Expected net profit <strong>'+money(plan.totalProfit)+'</strong></span><span>Unused slots <strong>'+plan.remaining+'</strong></span>'+(plan.budget>0?'<span>Budget left <strong>'+money(plan.unusedBudget)+'</strong></span>':'')+'</div><div class="sl-mi-plan-body"></div>';const body=bar.querySelector('.sl-mi-plan-body');for(const r of plan.rows){const row=document.createElement('div');row.className='sl-mi-plan-row';row.tabIndex=0;row.setAttribute('role','button');row.innerHTML='<span class="name">'+esc(r.name)+'</span><span>BUY ×'+r.qty+'</span><span>'+money(r.buy)+'/ea</span><span>cost '+money(r.cost)+'</span><span>'+money(r.profit)+'</span><strong>'+pct(r.roi)+'</strong>';const go=()=>{try{r.row?.scrollIntoView({behavior:'smooth',block:'center'});}catch(_){}if(r.row){r.row.classList.add('sl-mi-target');setTimeout(()=>r.row.classList.remove('sl-mi-target'),2200);}};row.onclick=go;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};body.appendChild(row);}bar.querySelector('.sl-mi-plan-head').onclick=()=>bar.classList.toggle('open');mountTop(bar);}

    async function scanTravel(){if(!settings.travel)return;if(detectInFlight()){document.getElementById('sl-mi-best-run')?.remove();await renderArrivalStock();return;}document.getElementById('sl-mi-arrival')?.remove();if(!detectDestination()){await renderBestTravelRun();return;}const destination=detectDestination();if(!destination)return;document.getElementById('sl-mi-best-run')?.remove();const imgs=[...document.querySelectorAll('img[src*="/images/items/"]')],entries=[],seen=new Set();for(const img of imgs){const id=itemIdFromImg(img),row=rowContainer(img);if(!id||!row||seen.has(row))continue;const buy=extractFirstPrice(row);if(!(buy>0))continue;seen.add(row);entries.push({id,row,buy,name:img.alt||('Item #'+id),stock:extractStock(row)});}const unique=[...new Map(entries.map(e=>[e.id,e])).values()].slice(0,MAX_LIVE_FETCHES),marketMap=new Map();for(const e of unique){const c=cachePeek(e.id);if(c)marketMap.set(e.id,c);}await mapWithLimit(unique,async e=>{if(e.stock!=null)recordStock(destination,e.id,e.stock);const market=await fetchMarket(e.id);if(!market)return;marketMap.set(e.id,market);const m=metrics(e.buy,market.price),box=ensureBadge(e.row,'sl-mi-travel');box.classList.toggle('loss',m.profit<Number(settings.minProfit||0));box.innerHTML='<b>☠︎ MI</b> Market '+money(market.price)+' · Net '+money(m.net)+' · <strong>'+money(m.profit)+' ('+pct(m.roi)+')</strong>'+(e.stock!=null?' · Stock '+e.stock+stockEtaText(destination,e.id,e.stock):'');state.decorated++;});flushStockHistory();paintTravelBuyPlan(buildTravelBuyPlan(destination,unique,marketMap));}

    function paintBazaarBoard(rows){document.getElementById('sl-mi-bazaar-board')?.remove();state.bazaarDeals=rows.length;state.bazaarBestProfit=rows[0]?.profit||0;state.bazaarBestRoi=rows.slice().sort((a,b)=>b.roi-a.roi)[0]?.roi||0;if(!rows.length)return;const top=rows.slice(0,10),best=top[0],bar=document.createElement('div');bar.id='sl-mi-bazaar-board';bar.className='open';bar.innerHTML='<div class="sl-mi-baz-head"><div><span class="sl-mi-br-title">💰 BAZAAR FLIP INTELLIGENCE</span><strong>'+esc(best.name)+' · '+money(best.profit)+'</strong></div><div>'+top.length+' deals</div><button type="button">▾</button></div><div class="sl-mi-baz-body"></div>';const body=bar.querySelector('.sl-mi-baz-body');for(const r of top){const row=document.createElement('div');row.className='sl-mi-baz-row';row.innerHTML='<span class="name">'+esc(r.name)+'</span><span>Buy '+money(r.buy)+'</span><span>Market '+money(r.market)+'</span><strong>'+money(r.profit)+'</strong><span>'+pct(r.roi)+'</span>';body.appendChild(row);}bar.querySelector('.sl-mi-baz-head').onclick=()=>bar.classList.toggle('open');mountTop(bar);}
    async function scanBazaar(){if(!settings.bazaar)return;document.getElementById('sl-mi-bazaar-board')?.remove();const imgs=[...document.querySelectorAll('img[src*="/images/items/"]')],entries=[],seen=new Set();for(const img of imgs){const id=itemIdFromImg(img),row=rowContainer(img);if(!id||!row||seen.has(row))continue;const buy=extractFirstPrice(row);if(!(buy>1))continue;seen.add(row);entries.push({id,row,buy,name:img.alt||('Item #'+id)});}const ids=[...new Set(entries.map(e=>e.id))].slice(0,MAX_LIVE_FETCHES),map=new Map();for(const id of ids){const c=cachePeek(id);if(c)map.set(id,c);}await mapWithLimit(ids,async id=>{const m=await fetchMarket(id);if(m)map.set(id,m);});const deals=[];for(const e of entries){const market=map.get(e.id);if(!market)continue;const m=metrics(e.buy,market.price),box=ensureBadge(e.row,'sl-mi-bazaar'),good=m.profit>0;box.innerHTML='<b>'+(good?'▲ DEAL':'▼ NO FLIP')+'</b> · Market '+money(market.price)+' · '+money(m.profit)+' · '+pct(m.roi);if(good)deals.push({id:e.id,row:e.row,name:e.name,buy:e.buy,market:market.price,profit:m.profit,roi:m.roi});}deals.sort((a,b)=>b.profit-a.profit);paintBazaarBoard(deals);}
    function selectedMarketItemId(){const m=(location.hash||'').match(/itemID=(\d+)/i);return m?Number(m[1]):null;}
    async function scanItemMarket(){if(!settings.itemMarket)return;const id=selectedMarketItemId();document.getElementById('sl-mi-market-bar')?.remove();if(!id)return;const market=await fetchMarket(id,true);if(!market)return;const watched=watchlist[String(id)]||null,bar=document.createElement('div');bar.id='sl-mi-market-bar';bar.innerHTML='<div><b>📈 ITEM MARKET INTELLIGENCE</b> · floor <strong>'+money(market.minPrice)+'</strong> · effective <strong>'+money(market.price)+'</strong></div><div class="sl-mi-watch-row"><input id="sl-mi-watch-price" inputmode="numeric" value="'+esc(watched?.maxPrice||'')+'"><button id="sl-mi-watch-save">SAVE WATCH</button></div>';mountTop(bar);bar.querySelector('#sl-mi-watch-save').onclick=()=>{const n=parseMoney(bar.querySelector('#sl-mi-watch-price').value);if(n>0){watchlist[String(id)]={itemId:id,maxPrice:n,updatedAt:Date.now()};saveJson(STORAGE.watchlist,watchlist);}};}
    async function scanItems(){if(!settings.items)return;}
    function scrapePointsRate(){const vals=[];document.querySelectorAll('*').forEach(el=>{if(el.children.length)return;const m=(el.textContent||'').trim().match(/^\$\s*([\d,]+)$/);if(!m)return;const n=parseMoney(m[1]);if(n>=5000&&n<=200000)vals.push(n);});return vals.length?Math.min(...vals):null;}
    function scanPoints(){if(!settings.points)return;const rate=scrapePointsRate();if(rate)saveJson(STORAGE.pointsRate,{rate,at:Date.now()});}
    async function scanMuseum(){if(!settings.museum)return;document.getElementById('sl-mi-museum-bar')?.remove();const pointsRate=freshPointsRate(),catalog=await loadMuseumCatalog(),rows=[],itemIds=new Set();for(const set of MUSEUM_SETS){const members=[],missing=[];for(const member of set.members){const item=catalog.get(museumNameKey(member.name));if(!item?.id){missing.push(member.name);continue;}members.push({id:Number(item.id),name:item.name||member.name,qty:Number(member.qty)||1});itemIds.add(Number(item.id));}rows.push({set,members,missing});}const marketMap=new Map();for(const id of itemIds){const c=cachePeek(id);if(c)marketMap.set(id,c);}await mapWithLimit([...itemIds].slice(0,MAX_LIVE_FETCHES),async id=>{const m=await fetchMarket(id);if(m)marketMap.set(id,m);});const bar=document.createElement('div');bar.id='sl-mi-museum-bar';bar.innerHTML='<b>🏛 MUSEUM INTELLIGENCE</b> · Points rate '+(pointsRate?money(pointsRate)+'/pt':'not captured');mountTop(bar);}
    function mountTop(el){const host=document.querySelector('#mainContainer .content-wrapper')||document.querySelector('.content-wrapper')||document.querySelector('#mainContainer')||document.body;host.insertBefore(el,host.firstChild);}
    async function scan(force=false){if(!settings.enabled||state.busy)return;state.busy=true;state.page=detectPage();try{if(force)document.querySelectorAll('.sl-mi-travel,.sl-mi-bazaar,.sl-mi-items,#sl-mi-best-run,#sl-mi-arrival,#sl-mi-museum-bar,#sl-mi-bazaar-board,#sl-mi-travel-plan,#sl-mi-market-bar').forEach(n=>n.remove());switch(state.page){case'travel':await scanTravel();break;case'bazaar':await scanBazaar();break;case'itemmarket':await scanItemMarket();break;case'items':await scanItems();break;case'points':scanPoints();break;case'museum':await scanMuseum();break;}state.lastScan=Date.now();state.scanCount++;}catch(e){state.lastError=String(e?.message||e);console.error('['+NAME+']',e);}finally{state.busy=false;}}
    function scheduleScan(force=false){if(state.scanTimer)clearTimeout(state.scanTimer);state.scanTimer=setTimeout(()=>{state.scanTimer=null;scan(force);},450);}
    function toggle(key,label){return'<label class="sl-mi-toggle"><input id="sl-mi-'+key+'" type="checkbox" '+(settings[key]?'checked':'')+'><span>'+esc(label)+'</span></label>';}
    function openSettings(){document.getElementById('sl-mi-overlay')?.remove();const overlay=document.createElement('div');overlay.id='sl-mi-overlay';overlay.innerHTML='<div id="sl-mi-panel"><div class="sl-mi-head"><div><div class="sl-mi-title">☠︎ SakaLuX Market Intelligence</div><div class="sl-mi-sub">v'+VERSION+'</div></div><button id="sl-mi-close">×</button></div>'+toggle('enabled','Enable Market Intelligence')+toggle('travel','Travel profit intelligence')+toggle('bestRun','Best Travel Run board')+toggle('stockEta','Stock + restock ETA')+toggle('arrivalStock','Arrival-stock prediction while flying')+toggle('bazaar','Bazaar deal detection')+toggle('itemMarket','Item Market + local watchlist')+toggle('items','Inventory market estimates')+toggle('museum','Museum intelligence')+toggle('points','Points Market rate capture')+'<label class="sl-mi-field">Travel slots<input id="sl-mi-slots" type="number" min="1" max="100" value="'+esc(settings.travelSlots)+'"></label><label class="sl-mi-field">Travel budget ($)<input id="sl-mi-budget" inputmode="numeric" value="'+esc(settings.travelBudget||0)+'" placeholder="0 = unlimited"></label><label class="sl-mi-field">Fallback flight multiplier<input id="sl-mi-flight" type="number" min="0.1" max="1" step="0.01" value="'+esc(settings.flightMultiplier)+'"></label><label class="sl-mi-field">Market fee %<input id="sl-mi-fee" type="number" min="0" max="100" step="0.1" value="'+esc(settings.marketFeePct)+'"></label><button class="sl-mi-primary" id="sl-mi-save">SAVE</button></div>';document.body.appendChild(overlay);overlay.querySelector('#sl-mi-close').onclick=()=>overlay.remove();overlay.querySelector('#sl-mi-save').onclick=()=>{for(const k of['enabled','travel','bestRun','stockEta','arrivalStock','bazaar','itemMarket','items','museum','points'])settings[k]=!!overlay.querySelector('#sl-mi-'+k)?.checked;settings.travelSlots=Math.max(1,Number(overlay.querySelector('#sl-mi-slots').value)||29);settings.travelBudget=Math.max(0,parseMoney(overlay.querySelector('#sl-mi-budget').value)||0);settings.flightMultiplier=Math.max(.1,Number(overlay.querySelector('#sl-mi-flight').value)||1);settings.marketFeePct=Number(overlay.querySelector('#sl-mi-fee').value)||0;saveJson(STORAGE.settings,settings);overlay.remove();scheduleScan(true);};}
    function injectCss(){if(document.getElementById('sl-mi-style'))return;const s=document.createElement('style');s.id='sl-mi-style';s.textContent=`#sl-mi-best-run,#sl-mi-arrival,#sl-mi-museum-bar,#sl-mi-bazaar-board,#sl-mi-travel-plan,#sl-mi-market-bar{box-sizing:border-box;margin:8px auto 10px;max-width:1100px;padding:7px 8px;border-radius:6px;background:#15191f;border:1px solid #2c333d;border-left:3px solid #d7b94c;color:#d7dce5;font:700 11px/1.4 Arial,sans-serif}.sl-mi-br-head,.sl-mi-arrival-head,.sl-mi-plan-head,.sl-mi-baz-head{display:flex;align-items:center;justify-content:space-between;gap:8px;cursor:pointer}.sl-mi-br-title{color:#d7b94c;font-weight:900}.sl-mi-br-body,.sl-mi-arrival-body,.sl-mi-plan-body,.sl-mi-baz-body{display:none;margin-top:7px;gap:4px}.open .sl-mi-br-body,.open .sl-mi-arrival-body,#sl-mi-travel-plan.open .sl-mi-plan-body,#sl-mi-bazaar-board.open .sl-mi-baz-body{display:flex;flex-direction:column}.sl-mi-br-row,.sl-mi-arrival-row,.sl-mi-plan-row,.sl-mi-baz-row{display:grid;grid-template-columns:minmax(0,1.4fr) auto auto auto auto auto;gap:8px;align-items:center;padding:6px;border:1px solid #292f38;border-radius:5px;font-size:10px}.sl-mi-plan-summary{display:flex;gap:12px;flex-wrap:wrap;margin-top:7px;padding:6px;border:1px solid #29323a;border-radius:6px}.sl-mi-plan-note,.sl-mi-perf-note{margin-top:5px;color:#8f98a5;font-size:9px}.sl-mi-target{outline:2px solid #d7b94c!important}#sl-mi-button{position:fixed;right:10px;bottom:106px;z-index:2147483644;border:0;border-radius:999px;padding:9px 11px;background:#18181b;color:#fff;font-weight:900}#sl-mi-overlay{position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.78);display:flex;align-items:flex-end;justify-content:center}#sl-mi-panel{width:min(560px,100%);max-height:90vh;overflow:auto;padding:14px;background:#101318;color:#fff;border-radius:18px 18px 0 0}.sl-mi-head{display:flex;justify-content:space-between}.sl-mi-toggle,.sl-mi-field{display:flex;justify-content:space-between;gap:8px;margin:7px 0;padding:10px;background:#181d24;border:1px solid #292f38;border-radius:9px}.sl-mi-field input{width:45%;background:#0f1217;color:#fff;border:1px solid #303640;border-radius:7px;padding:7px}.sl-mi-primary{width:100%;min-height:40px;border:0;border-radius:9px;background:#2563eb;color:#fff;font-weight:900}@media(max-width:700px){.sl-mi-br-row,.sl-mi-arrival-row,.sl-mi-plan-row,.sl-mi-baz-row{grid-template-columns:minmax(0,1fr) auto auto;gap:3px 7px}}`;document.head.appendChild(s);}
    function createButton(){if(document.getElementById('sl-mi-button'))return;const b=document.createElement('button');b.id='sl-mi-button';b.textContent='☠︎ Market';b.onclick=openSettings;document.body.appendChild(b);}
    function maybePromptHub(){if(window.SakaLuXScriptHub)return;}
    function startObserver(){if(state.observer)return;state.observer=new MutationObserver(()=>scheduleScan(false));state.observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>scheduleScan(true));}
    window.SakaLuXMarketIntelligence={id:'market-intelligence',name:'Market Intelligence',version:VERSION,open(){openSettings();return true;},async refresh(){await scan(true);return true;},health(){return{ready:true,version:VERSION,page:state.page||detectPage(),travelPlanItems:state.travelPlanItems,travelPlanCost:state.travelPlanCost,travelPlanProfit:state.travelPlanProfit,travelPlanSlots:state.travelPlanSlots,travelPlanBudget:state.travelPlanBudget,travelPlanUnusedBudget:state.travelPlanUnusedBudget};},goToTravel(){location.href='https://www.torn.com/page.php?sid=travel';return true;},goToBestRun(){location.href='https://www.torn.com/page.php?sid=travel';return true;},selectDestination(destination){return selectTravelDestination(destination);},goToMarket(){location.href='https://www.torn.com/page.php?sid=ItemMarket';return true;},goToBazaar(){location.href='https://www.torn.com/bazaar.php';return true;},goToMuseum(){location.href='https://www.torn.com/museum.php';return true;}};
    window.dispatchEvent(new CustomEvent('SakaLuX:MarketIntelligenceReady',{detail:{version:VERSION}}));
    function init(){injectCss();createButton();startObserver();maybePromptHub();scheduleScan(true);console.log('['+NAME+' v'+VERSION+'] Loaded.');}
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();