// ==UserScript==
// @name         SakaLuX Bounty Hunter
// @namespace    sakalux.bounty.hunter
// @version      0.2.0
// @description  Mobile-first Torn bounty intelligence with full-board API paging, FF/BS hints, hospital countdown, target alerts, Safe/Profit modes, watchlist and blacklist.
// @author       SakaLuX [2380374]
// @match        https://www.torn.com/*
// @grant        none
// @license      All Rights Reserved
// @downloadURL  https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Bounty-Hunter.user.js
// @updateURL    https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/SakaLuX-Bounty-Hunter.user.js
// @homepage     https://github.com/SakaLuX/SakaLuX-Script-HUB
// ==/UserScript==
(()=>{'use strict';
const VERSION='0.2.0',ID='bounty-hunter',API='SakaLuXBountyHunter';
const KS='SLX_BOUNTY_SETTINGS_V2',KW='SLX_BOUNTY_WATCH_V1',KB='SLX_BOUNTY_BLACK_V1',KK='SakaLuX_BOUNTY_API_KEY',KC='SLX_BOUNTY_CACHE_V1';
const D={enabled:true,mode:'safe',source:'auto',minReward:50000,maxLevel:100,okay:true,hospital:true,hideUnknown:false,autoRefresh:true,refreshSec:20,compact:true,fullBoard:true,maxPages:8,notifyTargets:true,notifyMinReward:250000,notifyWatch:true,maxFF:0,maxBS:0,hospitalWindowMin:30};
const J=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},W=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},N=v=>String(v??'').replace(/\s+/g,' ').trim(),num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
let S={...D,...J(KS,{})},WATCH=J(KW,{}),BLACK=J(KB,{}),CACHE=J(KC,{rows:[],at:0}),timer=0,lastRows=[],busy=false,lastError='',lastSource='DOM',notified=new Map();
const save=()=>W(KS,S),saveLists=()=>{W(KW,WATCH);W(KB,BLACK)},saveCache=()=>W(KC,CACHE);
function fmt(n){n=num(n);if(n>=1e9)return'$'+(n/1e9).toFixed(n>=1e10?1:2)+'B';if(n>=1e6)return'$'+(n/1e6).toFixed(n>=1e7?1:2)+'M';if(n>=1e3)return'$'+Math.round(n/1e3)+'K';return'$'+Math.round(n).toLocaleString()}
function money(t){const a=[...String(t||'').matchAll(/\$\s*([\d,.]+)\s*([kmbt])?/ig)];let best=0;for(const m of a){let n=Number(m[1].replace(/,/g,''));const u=(m[2]||'').toLowerCase();if(u==='k')n*=1e3;if(u==='m')n*=1e6;if(u==='b')n*=1e9;if(u==='t')n*=1e12;if(Number.isFinite(n))best=Math.max(best,n)}return best}
function onBounties(){return /\/bounties\.php/i.test(location.pathname)||/bount/i.test(document.title)}
function getKey(){try{const hub=window.SakaLuXHub||window.SakaLuXScriptHub||window.SakaLuX?.hub;const hk=typeof hub?.getApiKey==='function'?hub.getApiKey():'';if(hk)return String(hk).trim()}catch{}try{return String(localStorage.getItem('SakaLuX_HUB_TORN_API_KEY')||localStorage.getItem(KK)||'').trim()}catch{return''}}
function setLocalKey(v){try{localStorage.setItem(KK,String(v||'').trim())}catch{}}
function idFrom(a){const s=(a?.href||'')+' '+(a?.getAttribute?.('href')||'');return (s.match(/[?&](?:XID|userID|user2ID)=(\d+)/i)||[])[1]||''}
function parseLevel(t){const m=String(t).match(/(?:level|lvl)\s*[:#-]?\s*(\d{1,3})/i);return m?Number(m[1]):null}
function parseFF(t){const m=String(t).match(/(?:FF|fair\s*fight|FFS)\s*[:#-]?\s*(\d+(?:\.\d+)?)/i);return m?Number(m[1]):null}
function parseBS(t){const m=String(t).match(/(?:BS|battle\s*score|battle\s*stats?)\s*[:#-]?\s*([\d,.]+)\s*([kmbt])?/i);if(!m)return null;let n=Number(m[1].replace(/,/g,''));const u=(m[2]||'').toLowerCase();if(u==='k')n*=1e3;if(u==='m')n*=1e6;if(u==='b')n*=1e9;if(u==='t')n*=1e12;return Number.isFinite(n)?n:null}
function statusOf(t){t=N(t);if(/hospital/i.test(t))return'Hospital';if(/okay|healthy|available/i.test(t))return'Okay';if(/jail/i.test(t))return'Jail';if(/travel|abroad|flying/i.test(t))return'Abroad';return'Unknown'}
function hospitalUntilFromText(t){const now=Math.floor(Date.now()/1000),s=String(t||'');let m=s.match(/(?:hospital|hosp).*?(\d+)\s*h(?:ours?)?\s*(\d+)?\s*m?/i);if(m)return now+Number(m[1])*3600+Number(m[2]||0)*60;m=s.match(/(?:hospital|hosp).*?(\d+)\s*m(?:in(?:ute)?s?)?/i);if(m)return now+Number(m[1])*60;return 0}
function rowFor(a){let n=a;for(let i=0;i<8&&n?.parentElement;i++,n=n.parentElement){const q=n.getBoundingClientRect?.(),txt=N(n.innerText);if(q&&q.width>180&&q.height>28&&q.height<320&&/\$/.test(txt))return n}return a.parentElement}
function scanDom(){if(!onBounties())return[];const map=new Map();for(const a of document.querySelectorAll('a[href*="profiles.php"],a[href*="XID="],a[href*="userID="],a[href*="user2ID="]')){const id=idFrom(a);if(!id)continue;const row=rowFor(a);if(!row)continue;const text=N(row.innerText),reward=money(text);if(!reward)continue;const name=N(a.textContent).replace(/\[\d+\]$/,'').trim()||('Player '+id),level=parseLevel(text),status=statusOf(text),ff=parseFF(text),bs=parseBS(text),hospitalUntil=hospitalUntilFromText(text),atk=row.querySelector('a[href*="loader.php"][href*="attack"],a[href*="sid=attack"]');const old=map.get(id)||{id,name,level,status,reward:0,count:0,row,ff,bs,hospitalUntil,attack:atk?.href||('https://www.torn.com/loader.php?sid=attack&user2ID='+id),source:'DOM'};old.reward+=reward;old.count++;if(old.status==='Unknown'&&status!=='Unknown')old.status=status;if(old.level==null&&level!=null)old.level=level;if(old.ff==null&&ff!=null)old.ff=ff;if(old.bs==null&&bs!=null)old.bs=bs;if(!old.hospitalUntil&&hospitalUntil)old.hospitalUntil=hospitalUntil;map.set(id,old)}return[...map.values()]}
function pick(obj,...keys){for(const k of keys){if(obj&&obj[k]!=null)return obj[k]}return null}
function normalizeApiBounty(b){const target=pick(b,'target','player','user')||{},id=String(pick(b,'target_id','targetID','user_id','userID','player_id','playerID')??pick(target,'id','user_id','player_id')??'');if(!id)return null;const reward=num(pick(b,'reward','amount','money','bounty')??0),name=String(pick(b,'target_name','name')??pick(target,'name')??('Player '+id));const levelRaw=pick(b,'level')??pick(target,'level'),level=levelRaw==null?null:num(levelRaw);const statusObj=pick(b,'status')??pick(target,'status'),statusText=typeof statusObj==='object'?String(pick(statusObj,'state','description','details')||''):String(statusObj||'');const status=statusOf(statusText);let hospitalUntil=num(pick(b,'hospital_until','hospitalUntil','until')??(typeof statusObj==='object'?pick(statusObj,'until','timestamp'):0));if(hospitalUntil>1e12)hospitalUntil=Math.floor(hospitalUntil/1000);return{id,name,level,status,reward,count:1,row:null,ff:null,bs:null,hospitalUntil,attack:'https://www.torn.com/loader.php?sid=attack&user2ID='+id,source:'API'}}
function apiList(data){if(Array.isArray(data))return data;if(Array.isArray(data?.bounties))return data.bounties;if(data?.bounties&&typeof data.bounties==='object')return Object.values(data.bounties);if(Array.isArray(data?.data))return data.data;return[]}
async function fetchPage(offset,key){const url='https://api.torn.com/v2/torn/bounties?limit=100&offset='+offset+'&key='+encodeURIComponent(key);const core=window.SakaLuXCore?.api;if(core?.requestJson)return core.requestJson({url,ttl:8000,retries:1,timeout:12000,throwApiError:true});const r=await fetch(url,{credentials:'omit'});if(!r.ok)throw new Error('Torn API HTTP '+r.status);const j=await r.json();if(j?.error)throw new Error(j.error.error||j.error.message||'Torn API error');return j}
async function fetchFullBoard(force=false){const key=getKey();if(!key)throw new Error('No Torn API key. Add one in API settings or Script Hub.');if(!force&&CACHE.rows?.length&&Date.now()-num(CACHE.at)<12000)return CACHE.rows;const map=new Map(),pages=Math.max(1,Math.min(20,num(S.maxPages)||8));for(let p=0;p<pages;p++){const list=apiList(await fetchPage(p*100,key));for(const b of list){const x=normalizeApiBounty(b);if(!x||!x.reward)continue;const old=map.get(x.id)||x;if(old!==x){old.reward+=x.reward;old.count+=1;if(old.status==='Unknown'&&x.status!=='Unknown')old.status=x.status;if(!old.hospitalUntil&&x.hospitalUntil)old.hospitalUntil=x.hospitalUntil}map.set(x.id,old)}if(list.length<100)break}const rows=[...map.values()];CACHE={rows,at:Date.now()};saveCache();return rows}
function mergeDomHints(apiRows){const dom=new Map(scanDom().map(x=>[x.id,x]));return apiRows.map(x=>{const d=dom.get(x.id);if(!d)return x;return{...x,name:d.name||x.name,level:d.level??x.level,status:d.status!=='Unknown'?d.status:x.status,ff:d.ff??x.ff,bs:d.bs??x.bs,hospitalUntil:d.hospitalUntil||x.hospitalUntil,attack:d.attack||x.attack}})}
function hospLeft(x){const sec=num(x.hospitalUntil)-Math.floor(Date.now()/1000);return sec>0?sec:0}
function hospText(x){const s=hospLeft(x);if(!s)return'';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),z=s%60;return(h?h+'h ':'')+(m?m+'m ':'')+z+'s'}
function allowed(x){if(BLACK[x.id])return false;if(x.reward<num(S.minReward))return false;if(x.level!=null&&x.level>num(S.maxLevel||100))return false;if(S.maxFF>0&&x.ff!=null&&x.ff>S.maxFF)return false;if(S.maxBS>0&&x.bs!=null&&x.bs>S.maxBS)return false;if(S.hideUnknown&&x.status==='Unknown')return false;if(x.status==='Okay'&&!S.okay)return false;if(x.status==='Hospital'&&!S.hospital)return false;if(['Jail','Abroad'].includes(x.status))return false;if(x.status==='Hospital'&&num(S.hospitalWindowMin)>0&&hospLeft(x)>num(S.hospitalWindowMin)*60&&!WATCH[x.id])return false;if(S.mode==='safe'&&x.status!=='Okay'&&x.status!=='Hospital')return false;return true}
function score(x){let risk=1;if(x.status==='Okay')risk=1.25;else if(x.status==='Hospital')risk=hospLeft(x)<=300?1.1:.85;else risk=.45;if(x.ff!=null)risk*=Math.max(.35,Math.min(1.2,2.2/(1+x.ff)));if(x.bs!=null&&S.maxBS>0)risk*=Math.max(.4,1-x.bs/(S.maxBS*1.5));return S.mode==='profit'?x.reward*risk:(x.status==='Okay'?1e15:x.status==='Hospital'?5e14:0)+x.reward*risk}
async function collect(force=false){lastError='';let rows=[];const wantApi=S.fullBoard&&S.source!=='dom'&&!!getKey();try{if(wantApi){rows=mergeDomHints(await fetchFullBoard(force));lastSource='API'}else{rows=scanDom();lastSource='DOM'}}catch(e){lastError=e.message||String(e);rows=scanDom();lastSource='DOM fallback'}lastRows=rows;return rows}
function bestRows(){return lastRows.filter(allowed).sort((a,b)=>score(b)-score(a)||b.reward-a.reward)}
function toast(msg){let h=document.getElementById('slx-bh-toast');if(!h){h=document.createElement('div');h.id='slx-bh-toast';document.body.appendChild(h)}const d=document.createElement('div');d.textContent=msg;h.appendChild(d);setTimeout(()=>d.remove(),5500)}
function maybeNotify(rows){if(!S.notifyTargets)return;const now=Date.now();for(const x of rows.slice(0,8)){if(x.reward<num(S.notifyMinReward)&&!WATCH[x.id])continue;if(x.status!=='Okay'&&!(x.status==='Hospital'&&hospLeft(x)<=300))continue;const key=x.id+':'+x.status+':'+Math.floor(x.reward/50000),last=notified.get(key)||0;if(now-last<10*60*1000)continue;notified.set(key,now);const text=(WATCH[x.id]?'★ ':'')+x.name+' '+fmt(x.reward)+' · '+x.status+(x.status==='Hospital'?' '+hospText(x):'');toast('🎯 '+text);if('Notification'in window&&Notification.permission==='granted'){try{new Notification('SakaLuX Bounty Hunter',{body:text})}catch{}}}}
function ensureCss(){if(document.getElementById('slx-bh-css'))return;const s=document.createElement('style');s.id='slx-bh-css';s.textContent=`#slx-bh-btn{position:fixed;right:12px;bottom:92px;z-index:2147482000;width:48px;height:48px;border:1px solid #56677b;border-radius:14px;background:#172331;color:#fff;font-size:24px;box-shadow:0 8px 26px #0009}#slx-bh{position:fixed;inset:0;z-index:2147483600;background:#000b;display:flex;align-items:flex-end;justify-content:center}#slx-bh>section{width:min(720px,100%);max-height:91dvh;display:flex;flex-direction:column;background:#101820;color:#edf3fa;border:1px solid #394c61;border-radius:16px 16px 0 0;overflow:hidden}#slx-bh header{display:flex;align-items:center;gap:7px;padding:9px;background:#182431}#slx-bh header b{flex:1}#slx-bh button,#slx-bh input,#slx-bh select{min-height:34px;border:1px solid #3d5066;border-radius:8px;background:#172331;color:#edf3fa}#slx-bh header button{width:38px}#slx-bh .bar{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;padding:8px}#slx-bh .bar label{font-size:10px;color:#9fb0c2}#slx-bh .bar input,#slx-bh .bar select{width:100%;box-sizing:border-box;padding:5px}.slx-bh-tools,.slx-bh-tog{display:flex;gap:6px;padding:0 8px 8px;flex-wrap:wrap}.slx-bh-chip{padding:5px 8px!important;min-height:30px!important}.slx-bh-chip.on{border-color:#59d98a!important;color:#7ee5a5!important}.slx-bh-list{overflow:auto;padding:8px;display:flex;flex-direction:column;gap:7px}.slx-bh-row{display:grid;grid-template-columns:1fr auto;gap:8px;padding:9px;border:1px solid #34465b;border-radius:10px;background:#15202b}.slx-bh-row .name{font-weight:800}.slx-bh-row .meta{font-size:11px;color:#9fb0c2;margin-top:3px}.slx-bh-row .money{font-weight:900;color:#78df9d}.slx-bh-row.watch{border-color:#d9ba59}.slx-bh-actions{display:flex;gap:5px;align-items:center}.slx-bh-actions button,.slx-bh-actions a{display:grid;place-items:center;min-width:36px;height:34px;border:1px solid #3d5066;border-radius:8px;background:#1b2b3a;color:#fff;text-decoration:none}.slx-bh-empty{padding:20px;text-align:center;color:#9fb0c2}.slx-bh-foot{display:flex;justify-content:space-between;gap:8px;padding:8px;border-top:1px solid #2f4052;font-size:11px;color:#9fb0c2}#slx-bh-toast{position:fixed;top:76px;right:8px;z-index:2147483646;display:flex;flex-direction:column;gap:6px;max-width:min(360px,92vw)}#slx-bh-toast>div{padding:9px 11px;border:1px solid #4c6178;border-radius:10px;background:#13202cf2;color:#fff;box-shadow:0 8px 24px #0009}.slx-bh-api{padding:9px;border-top:1px solid #2f4052;background:#111b25;font-size:11px}.slx-bh-api input{width:100%;box-sizing:border-box;padding:6px}.slx-bh-api .row{display:flex;gap:6px;margin-top:6px}.slx-bh-api .row button{flex:1}@media(max-width:520px){#slx-bh .bar{grid-template-columns:1fr 1fr}.slx-bh-row{grid-template-columns:1fr}.slx-bh-actions{justify-content:flex-end}}`;document.head.appendChild(s)}
function button(){ensureCss();let b=document.getElementById('slx-bh-btn');if(!b){b=document.createElement('button');b.id='slx-bh-btn';b.textContent='🎯';b.title='SakaLuX Bounty Hunter';b.onclick=open;document.body.appendChild(b)}b.hidden=!S.enabled||!onBounties()}
function chip(label,on,fn){const b=document.createElement('button');b.className='slx-bh-chip'+(on?' on':'');b.textContent=label;b.onclick=fn;return b}
async function render(force=false){const o=document.getElementById('slx-bh');if(!o||busy)return;busy=true;const list=o.querySelector('.slx-bh-list');list.innerHTML='<div class="slx-bh-empty">Scanning bounty board…</div>';try{await collect(force);const rows=bestRows();list.innerHTML='';if(!rows.length)list.innerHTML='<div class="slx-bh-empty">No matching targets.'+(lastError?'<br>'+lastError.replace(/[<>]/g,''):'')+'</div>';for(const x of rows.slice(0,200)){const r=document.createElement('div');r.className='slx-bh-row'+(WATCH[x.id]?' watch':'');const tags=[x.status,x.level!=null?'L'+x.level:'',x.ff!=null?'FF '+x.ff:'',x.bs!=null?'BS '+fmt(x.bs).replace('$',''):'',x.count+' bounty'+(x.count===1?'':'ies'),x.status==='Hospital'&&hospLeft(x)?'⏱ '+hospText(x):''].filter(Boolean);const left=document.createElement('div');left.innerHTML='<div class="name">'+x.name.replace(/[<>]/g,'')+' <small>['+x.id+']</small></div><div class="meta">'+tags.join(' · ')+'</div><div class="money">'+fmt(x.reward)+'</div>';const a=document.createElement('div');a.className='slx-bh-actions';const atk=document.createElement('a');atk.href=x.attack;atk.textContent='⚔';atk.title='Attack';const w=document.createElement('button');w.textContent=WATCH[x.id]?'★':'☆';w.title='Watch';w.onclick=()=>{if(WATCH[x.id])delete WATCH[x.id];else WATCH[x.id]={name:x.name,addedAt:Date.now()};saveLists();render(false)};const bl=document.createElement('button');bl.textContent='🚫';bl.title='Blacklist';bl.onclick=()=>{BLACK[x.id]={name:x.name,addedAt:Date.now()};saveLists();render(false)};a.append(atk,w,bl);r.append(left,a);list.appendChild(r)}o.querySelector('[data-count]').textContent=rows.length+' matches / '+lastRows.length+' loaded';o.querySelector('[data-source]').textContent=lastSource+(getKey()?' · API key ready':' · no API key');maybeNotify(rows)}finally{busy=false}}
function apiPanel(o){const p=document.createElement('div');p.className='slx-bh-api';const source=getKey()?(localStorage.getItem('SakaLuX_HUB_TORN_API_KEY')?'Hub key':'Local/Hub key'):'No API key';p.innerHTML='<b>API Access</b><div>Source: '+source+'. Full-board paging uses Torn API v2. FF/BS are read from compatible page helpers when present.</div><input type="password" placeholder="Optional local Torn API key"><div class="row"><button data-save>Save local key</button><button data-clear>Clear local key</button><button data-notify>Enable notifications</button></div>';const i=p.querySelector('input');p.querySelector('[data-save]').onclick=()=>{setLocalKey(i.value);i.value='';toast('API key saved locally');render(true)};p.querySelector('[data-clear]').onclick=()=>{setLocalKey('');toast('Local API key cleared');render(false)};p.querySelector('[data-notify]').onclick=async()=>{if(!('Notification'in window))return toast('System notifications unavailable');try{const v=await Notification.requestPermission();toast('Notifications: '+v)}catch{}};o.querySelector('section').appendChild(p)}
function open(){ensureCss();document.getElementById('slx-bh')?.remove();const o=document.createElement('div');o.id='slx-bh';o.innerHTML='<section><header><b>🎯 SakaLuX Bounty Hunter v'+VERSION+'</b><button data-api title="API">🔑</button><button data-r title="Refresh">↻</button><button data-x>×</button></header><div class="bar"><label>Mode<select data-mode><option value="safe">Safe</option><option value="profit">Profit</option></select></label><label>Min reward<input data-min type="number" step="10000"></label><label>Max level<input data-level type="number" min="1" max="100"></label><label>Hosp window min<input data-hosp type="number" min="0" max="240"></label><label>Max FF (0 off)<input data-ff type="number" min="0" step="0.1"></label><label>Max BS (0 off)<input data-bs type="number" min="0" step="1000"></label><label>Alert reward<input data-alert type="number" min="0" step="10000"></label><label>Max API pages<input data-pages type="number" min="1" max="20"></label></div><div class="slx-bh-tog"></div><div class="slx-bh-list"></div><div class="slx-bh-foot"><span data-count></span><span data-source></span></div></section>';document.body.appendChild(o);o.querySelector('[data-x]').onclick=()=>o.remove();o.addEventListener('click',e=>{if(e.target===o)o.remove()});const bindNum=(sel,key,min,max)=>{const e=o.querySelector(sel);e.value=S[key];e.onchange=()=>{S[key]=Math.max(min,Math.min(max,num(e.value)));save();render(false)}};const mode=o.querySelector('[data-mode]');mode.value=S.mode;mode.onchange=()=>{S.mode=mode.value;save();render(false)};bindNum('[data-min]','minReward',0,1e12);bindNum('[data-level]','maxLevel',1,100);bindNum('[data-hosp]','hospitalWindowMin',0,240);bindNum('[data-ff]','maxFF',0,999);bindNum('[data-bs]','maxBS',0,1e15);bindNum('[data-alert]','notifyMinReward',0,1e12);bindNum('[data-pages]','maxPages',1,20);const tg=o.querySelector('.slx-bh-tog');const rebuild=()=>{tg.innerHTML='';tg.append(chip('Okay',S.okay,()=>{S.okay=!S.okay;save();rebuild();render(false)}),chip('Hospital',S.hospital,()=>{S.hospital=!S.hospital;save();rebuild();render(false)}),chip('Full board API',S.fullBoard,()=>{S.fullBoard=!S.fullBoard;save();rebuild();render(true)}),chip('Target alerts',S.notifyTargets,()=>{S.notifyTargets=!S.notifyTargets;save();rebuild()}),chip('Hide unknown',S.hideUnknown,()=>{S.hideUnknown=!S.hideUnknown;save();rebuild();render(false)}),chip('Auto '+S.refreshSec+'s',S.autoRefresh,()=>{S.autoRefresh=!S.autoRefresh;save();schedule();rebuild()}),chip('Clear blacklist ('+Object.keys(BLACK).length+')',false,()=>{BLACK={};saveLists();rebuild();render(false)}))};rebuild();o.querySelector('[data-r]').onclick=()=>render(true);o.querySelector('[data-api]').onclick=()=>{const p=o.querySelector('.slx-bh-api');if(p)p.remove();else apiPanel(o)};render(false)}
async function backgroundRefresh(){if(!S.enabled||!onBounties()||busy)return;busy=true;try{await collect(false);maybeNotify(bestRows());if(document.getElementById('slx-bh')){busy=false;return render(false)}}catch{}finally{busy=false}}
function schedule(){clearInterval(timer);timer=0;if(S.enabled&&S.autoRefresh)timer=setInterval(backgroundRefresh,Math.max(10,num(S.refreshSec)||20)*1000)}
function enable(v){S.enabled=!!v;save();button();schedule();bridge();return S.enabled}
function bridge(){let b=document.getElementById('sakalux-module-bridge-'+ID);if(!b){b=document.createElement('button');b.id='sakalux-module-bridge-'+ID;b.hidden=true;b.style.display='none';b.onclick=()=>{const a=b.dataset.action;if(a==='open')open();else if(a==='on')enable(true);else if(a==='off')enable(false);else if(a==='toggle')enable(!S.enabled);else if(a==='refresh')backgroundRefresh();b.dataset.action=''};document.documentElement.appendChild(b)}b.dataset.version=VERSION;b.dataset.enabled=String(S.enabled);b.dataset.ready='true'}
function go(){location.href='https://www.torn.com/bounties.php'}
function init(){ensureCss();button();bridge();schedule();window[API]={id:ID,version:VERSION,open,refresh:()=>render(true),refreshBackground:backgroundRefresh,goToBounties:go,setEnabled:enable,toggleEnabled:()=>enable(!S.enabled),isEnabled:()=>S.enabled,getApiKeySource:()=>getKey()?'available':'missing',health:()=>({version:VERSION,onBounties:onBounties(),loaded:lastRows.length,watch:Object.keys(WATCH).length,blacklist:Object.keys(BLACK).length,source:lastSource,error:lastError,fullBoard:S.fullBoard})};addEventListener('hashchange',()=>setTimeout(button,300));setInterval(button,2500);dispatchEvent(new CustomEvent('SakaLuX:ModuleReady',{detail:{id:ID,version:VERSION,apiGlobal:API}}));if(onBounties())setTimeout(backgroundRefresh,800)}
document.readyState==='loading'?addEventListener('DOMContentLoaded',init,{once:true}):init();
})();