// Offline Chromium stress suite. No real Torn accounts, keys or trades.
const fs=require('node:fs'),assert=require('node:assert/strict');
fs.mkdirSync('reports/extended-performance-2026-09-18',{recursive:true});
const {chromium}=require('playwright');
const files=fs.readdirSync('.').filter(x=>x.endsWith('.user.js')).sort();
const registry=JSON.parse(fs.readFileSync('scripts.json','utf8'));
const urls={Enhancer:'item.php',Bazaar:'page.php?sid=events',Market:'page.php?sid=ItemMarket',Mission:'loader.php?sid=missions',Elimination:'competition.php',Company:'joblist.php',Stock:'page.php?sid=stocks',Poker:'page.php?sid=holdem',Chat:'index.php'};
const html='<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{background:#222;color:white;margin:0}#chat-box{position:fixed;bottom:36px;right:0;width:310px;height:280px;background:#133}#chat-box header{height:40px}.chat-messages{height:180px;overflow:auto}textarea{width:280px}li{height:28px}</style></head><body><header id="topHeader"><ul class="status-icons"><li><a href="index.php">Status</a></li></ul></header><main id="mainContainer"><div class="content-wrapper" id="visible"><ul id="stock_visible"></ul></div></main><aside id="chat-box"><header>Global</header><div class="chat-messages"><div data-message-id="initial"><a href="profiles.php?XID=1000">Player</a> initial</div></div><div><textarea placeholder="Type your message"></textarea></div></aside></body></html>';
const report={fixture:'Offline synthetic Chromium touch viewport 412x915. 30-minute wall-clock soak; no authenticated Torn/PDA, actual battery or FPS measurement. API error/slow modes cover exercised requests only; missing-key code paths remain inactive.',results:[],errors:[],assertions:[],soak:[]};
function check(value,label){report.assertions.push({label,passed:!!value});console.log('CHECK '+JSON.stringify({label,passed:!!value}));}
(async()=>{const browser=await chromium.launch({headless:true});const contexts=[];
async function setup(file,combined=false,enabled=false){const context=await browser.newContext({viewport:{width:412,height:915},hasTouch:true,isMobile:true});contexts.push(context);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().isNavigationRequest()?r.fulfill({status:200,contentType:'text/html',body:html}):r.abort());await page.goto('https://www.torn.com/'+(enabled?'factions.php?step=your':combined?'page.php?sid=stocks':urls[Object.keys(urls).find(k=>file.includes(k))]||'index.php'));await page.evaluate(({registry,enabled})=>{
if(enabled)localStorage.setItem('sakalux_master_suite_settings_v1',JSON.stringify({modules:Object.fromEntries(['prayerReminder','medAdvisor','itemIntel','eventsDashboard','activityIntelligence','factionMemberView','armoryLoanScanner','warLedger','ocOperations','companyManagement','racingChampionship','casinoEdgeScanner','targetAlerts','chainAlarm'].map(id=>[id,true]))}));
window.__stress={timeouts:new Set,intervals:new Set,observers:new Set,requests:[],network:'ok',visibility:'visible',listeners:0};
const t=setTimeout,c=clearTimeout;window.setTimeout=(fn,ms,...args)=>{let id=t(()=>{__stress.timeouts.delete(id);typeof fn==='function'?fn(...args):eval(fn)},ms);__stress.timeouts.add(id);return id};window.clearTimeout=id=>{__stress.timeouts.delete(id);c(id)};
const i=setInterval,ci=clearInterval;window.setInterval=(fn,ms,...args)=>{const id=i(fn,ms,...args);__stress.intervals.add(id);return id};window.clearInterval=id=>{__stress.intervals.delete(id);ci(id)};
const O=MutationObserver;window.MutationObserver=class extends O{observe(...a){__stress.observers.add(this);return super.observe(...a)}disconnect(){__stress.observers.delete(this);super.disconnect()}};
const add=EventTarget.prototype.addEventListener;EventTarget.prototype.addEventListener=function(...a){__stress.listeners++;return add.apply(this,a)}; // registrations, not live listener count
Object.defineProperty(document,'visibilityState',{get:()=>__stress.visibility});Object.defineProperty(document,'hidden',{get:()=>__stress.visibility==='hidden'});
window.fetch=async url=>{const mode=__stress.network;__stress.requests.push({url:String(url).replace(/key=[^&]*/g,'key=FIXTURE'),mode,at:Date.now()});if(mode==='slow')await new Promise(r=>setTimeout(r,500));if(mode==='offline')throw Error('Fixture offline');if(mode==='429')return {ok:false,status:429,json:async()=>({error:{code:5,error:'Fixture rate limit'}}),text:async()=>''};if(mode==='malformed')return {ok:true,status:200,json:async()=>{throw SyntaxError('Fixture malformed JSON')},text:async()=>'{'};return {ok:true,status:200,json:async()=>String(url).includes('scripts.json')?registry:{},text:async()=>''}};
window.GM_xmlhttpRequest=o=>{const mode=__stress.network;__stress.requests.push({url:String(o.url).replace(/key=[^&]*/g,'key=FIXTURE'),mode,at:Date.now()});const id=setTimeout(()=>mode==='offline'?o.onerror?.({status:0}):o.onload?.({status:mode==='429'?429:200,responseText:mode==='malformed'?'{':JSON.stringify(String(o.url).includes('scripts.json')?registry:{})}),mode==='slow'?500:0);return {abort(){clearTimeout(id)}}};
window.GM_getValue=(k,v)=>v;window.GM_setValue=()=>{};window.GM_addStyle=css=>{const s=document.createElement('style');s.textContent=css;document.head.append(s);return s};window.GM={getValue:async(k,v)=>v,setValue:async()=>{},xmlHttpRequest:GM_xmlhttpRequest,addStyle:GM_addStyle};window.alert=()=>{};window.confirm=()=>false;window.prompt=()=>null;localStorage.setItem('SakaLuX_HUB_INSTALL_PROMPT_LAST',String(Date.now()));
window.__snapshot=()=>({nodes:document.querySelectorAll('*').length,timeouts:__stress.timeouts.size,intervals:__stress.intervals.size,observers:__stress.observers.size,listenerRegistrations:__stress.listeners,chatCache:window.SakaLuXChatIntelligence?.health?.().seenMessages});
window.__pulse=n=>{const chat=document.querySelector('.chat-messages');for(let k=0;k<n;k++){const d=document.createElement('div');d.dataset.messageId='stress-'+Date.now()+'-'+k;d.innerHTML='<a href="profiles.php?XID=1000">Player</a> message '+k;chat.append(d);if(chat.children.length>40)chat.firstChild.remove()}};
},{registry,enabled});const source=combined?files.filter(f=>f.startsWith('SakaLuX')).sort((a,b)=>Number(b.includes('Script-Hub'))-Number(a.includes('Script-Hub'))).map(f=>fs.readFileSync(f,'utf8')).join('\n;\n'):fs.readFileSync(file,'utf8');await page.evaluate(source);await page.waitForTimeout(1600);const cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');return {file,page,cdp,errors,context};}
try{
for(const file of files){const item=await setup(file);const {page}=item;const before=await page.evaluate(()=>__snapshot());check(await page.evaluate(()=>innerWidth===412),file+' actual layout viewport is 412px');const original=new URL(page.url());const stock=file.includes('Stock');let routesPassed=0;
for(let cycle=0;cycle<100;cycle++){await page.evaluate(()=>{history.pushState({},'','/index.php');dispatchEvent(new PopStateEvent('popstate'));document.querySelector('#visible').replaceChildren(Object.assign(document.createElement('ul'),{id:'stock_visible'}));__pulse(1)});await page.waitForTimeout(35);await page.evaluate(url=>{history.pushState({},'',url);dispatchEvent(new PopStateEvent('popstate'))},original.pathname+original.search);await page.waitForTimeout(65);if(stock&&await page.locator('#slx-stock-inline').count()===1)routesPassed++;}
await page.waitForTimeout(3500);const after=await page.evaluate(()=>__snapshot());check(after.observers<=before.observers+2,file+' observers remain bounded after 100 routes');check(after.intervals<=before.intervals+2,file+' intervals remain bounded after 100 routes');check(after.nodes<=before.nodes+180,file+' DOM remains bounded after 100 routes');if(stock)check(routesPassed===100,'Stocks remounts once on each of 100 return routes');
// Settings APIs + toggles, without buy/sell/request side effects.
const ui=await page.evaluate(async()=>{const api=window.SakaLuXChatIntelligence||window.SakaLuXStockManagerAdvisor;let toggles=0;if(api?.setEnabled){for(let k=0;k<20;k++){api.setEnabled(false);api.setEnabled(true);toggles++}}if(api?.open)api.open();if(window.SakaLuXScriptHub)window.SakaLuXScriptHub.open();const panels=document.querySelectorAll('#sakalux-chat-settings-overlay,#sakalux-hub-overlay,#slx-stock-panel').length;return {toggles,panels}});
// 10,000 live rows; preserve stock host. Chat searches use actual controls when detected.
const large=await page.evaluate(()=>{const ul=document.querySelector('#stock_visible');const f=document.createDocumentFragment();for(let k=0;k<10000;k++){const li=document.createElement('li');li.className='item-row';li.textContent='Fixture item '+k;f.append(li)}const start=performance.now();ul.append(f);return {rows:ul.children.length,insertMs:performance.now()-start}});await page.waitForTimeout(600);await page.evaluate(()=>{const ul=document.querySelector('#stock_visible');ul.scrollTop=ul.scrollHeight;window.scrollTo(0,500);ul.replaceChildren()});
const visibility=[];for(const state of ['hidden','visible','hidden','visible']){await page.evaluate(state=>{__stress.visibility=state;document.dispatchEvent(new Event('visibilitychange'));__pulse(1)},state);await page.waitForTimeout(180);visibility.push({state,...await page.evaluate(()=>__snapshot())})}
const network=[];for(const mode of ['slow','offline','429','malformed','ok']){await page.evaluate(async mode=>{__stress.network=mode;if(window.SakaLuXScriptHub)await window.SakaLuXScriptHub.refresh().catch(()=>{});if(window.SakaLuXStockManagerAdvisor)await window.SakaLuXStockManagerAdvisor.refresh().catch(()=>{});__pulse(1)},mode);await page.waitForTimeout(600);network.push({mode,requests:await page.evaluate(mode=>__stress.requests.filter(x=>x.mode===mode).length,mode)})}
const final=await page.evaluate(()=>__snapshot());const row={file,version:fs.readFileSync(file,'utf8').match(/@version\s+(\S+)/)[1],before,after,final,routes:100,stockReturns:stock?routesPassed:undefined,ui,large,visibility,network,errors:item.errors};report.results.push(row);check(item.errors.length===0,file+' no uncaught JS errors');console.log('EXTENDED_RESULT '+JSON.stringify(row));await item.context.close();}
const item=await setup('combined',true);const nativeItem=await setup('SakaLuX-Suite.user.js',false,true);const soakItems=[item,nativeItem];
// 30 real minutes, bounded live chat at 40 messages; GC sampling prevents heap sawtooth being mistaken for a leak.
const started=Date.now(),minutes=Number(process.env.SOAK_MINUTES||30);
for(let minute=0;minute<=minutes;minute++){for(const soakItem of soakItems){const {page,cdp}=soakItem;await cdp.send('HeapProfiler.collectGarbage');const metrics=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(x=>[x.name,x.value]));const sample={file:soakItem.file,minute,elapsedSeconds:+((Date.now()-started)/1000).toFixed(1),heapMB:+(metrics.JSHeapUsedSize/1024/1024).toFixed(2),...await page.evaluate(()=>__snapshot()),errors:[...soakItem.errors]};report.soak.push(sample);console.log('SOAK_SAMPLE '+JSON.stringify(sample));}if(minute===minutes)break;const until=started+(minute+1)*60000;while(Date.now()<until){await Promise.all(soakItems.map(x=>x.page.evaluate(()=>__pulse(2))));await item.page.waitForTimeout(Math.min(1000,Math.max(1,until-Date.now())));}}
for(const soakItem of soakItems){const samples=report.soak.filter(x=>x.file===soakItem.file);const first=samples[5]||samples[0],last=samples.at(-1);check(last.heapMB<=first.heapMB+8,soakItem.file+' 30-minute post-GC heap growth <=8 MB after warm-up');check(last.observers<=first.observers+2,soakItem.file+' 30-minute observers bounded');check(last.intervals<=first.intervals+2,soakItem.file+' 30-minute intervals bounded');check(last.nodes<=first.nodes+100,soakItem.file+' 30-minute DOM bounded');check(soakItem.errors.length===0,soakItem.file+' 30-minute soak no uncaught JS errors');}

}finally{await browser.close();fs.writeFileSync(process.argv[2]||'reports/extended-performance-2026-09-18/results.json',JSON.stringify(report,null,2));console.log('EXTENDED_SUMMARY '+JSON.stringify({results:report.results.length,assertions:report.assertions,soak:report.soak}));}
assert(report.assertions.every(x=>x.passed),'Extended stress checks failed; see report');
})().catch(e=>{console.error(e);process.exitCode=1});
