// Reuse exactly the same offline browser fixture as the extended soak.
const fs=require('fs');
const prefix=fs.readFileSync('tests/performance/extended.cjs','utf8').split('try{\nfor(const file of files)')[0];
if(!prefix.includes('async function setup'))throw Error('Extended fixture changed; update interactive adapter');
const body=String.raw`
report.fixture='Offline Chromium public-API panel lifecycle, native Suite switches, chat search and maximize; touch viewport 412x915. API/render CPU time is not phone FPS.';
try{
for(const file of files.filter(x=>x.startsWith('SakaLuX'))){const item=await setup(file);const {page,cdp}=item;await cdp.send('HeapProfiler.collectGarbage');const before=await page.evaluate(()=>__snapshot());const first=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(x=>[x.name,x.value]));
const row=await page.evaluate(async({file,registry})=>{const entry=registry.scripts.find(x=>decodeURIComponent(x.sourceUrl||'').endsWith('/'+file));const global=entry?.apiGlobal||(file.includes('Script-Hub')?'SakaLuXScriptHub':file.includes('Chat-')?'SakaLuXChatIntelligence':file.includes('Account-')?'SakaLuXAccountAuditor':null);const api=global?window[global]:null;const times=[];let opens=0,toggles=0,suiteSwitches=0,chatSearch=false,chatMaximize=false;
const close=()=>{for(const b of document.querySelectorAll('[id^="sakalux"] button,[id^="slx"] button')){if(['×','✕','✖','Close','× Close'].includes(b.textContent.trim())&&!b.disabled)b.click()}};
for(let cycle=0;cycle<30;cycle++){const start=performance.now();if(api?.open){api.open();opens++}else if(file.includes('Suite')){document.getElementById('sakalux-master-suite-launcher')?.click();opens++}await new Promise(r=>requestAnimationFrame(r));times.push(performance.now()-start);close();}
if(api?.setEnabled){for(let k=0;k<20;k++){api.setEnabled(false);api.setEnabled(true);toggles++}}else if(api?.toggleEnabled){for(let k=0;k<20;k++){api.toggleEnabled();api.toggleEnabled();toggles++}}
if(file.includes('Suite')){document.getElementById('sakalux-master-suite-launcher')?.click();const ids=[...document.querySelectorAll('[data-module-toggle]')].map(x=>x.dataset.moduleToggle);for(let cycle=0;cycle<10;cycle++)for(const id of ids){document.querySelector('[data-module-toggle="'+id+'"]')?.click();document.querySelector('[data-module-toggle="'+id+'"]')?.click();suiteSwitches+=2;}close();}
if(file.includes('Chat')){__pulse(20);await new Promise(r=>setTimeout(r,180));const search=document.querySelector('.slx-head-controls [data-s]');if(search){search.click();const input=document.querySelector('.slx-search input');input.value='message';input.dispatchEvent(new Event('input',{bubbles:true}));chatSearch=!!document.querySelector('.slx-search [data-count]');document.querySelector('.slx-search [data-c]')?.click();}const max=document.querySelector('.slx-head-controls [data-m]');if(max){max.click();max.click();chatMaximize=true;}}
times.sort((a,b)=>a-b);return {apiGlobal:global,opens,toggles,suiteSwitches,chatSearch,chatMaximize,frameInclusiveMedianMs:times[15],frameInclusiveP95Ms:times[28]};},{file,registry});await page.waitForTimeout(3500);await cdp.send('HeapProfiler.collectGarbage');const last=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(x=>[x.name,x.value]));const after=await page.evaluate(()=>__snapshot());Object.assign(row,{file,before,after,heapBeforeMB:first.JSHeapUsedSize/1024/1024,heapAfterMB:last.JSHeapUsedSize/1024/1024,scriptMs:(last.ScriptDuration-first.ScriptDuration)*1000,errors:item.errors});report.results.push(row);console.log('INTERACTIVE_RESULT '+JSON.stringify(row));check(item.errors.length===0,file+' repeated panels/toggles no uncaught errors');check(after.observers<=before.observers+3,file+' repeated panels/toggles observers bounded');check(after.intervals<=before.intervals+3,file+' repeated panels/toggles intervals bounded');check(row.heapAfterMB<=row.heapBeforeMB+8,file+' repeated panels/toggles post-GC heap bounded');if(file.includes('Suite'))check(row.suiteSwitches===460,'Suite all 23 switches toggled 20 times');if(file.includes('Chat'))check(row.chatSearch&&row.chatMaximize,'Chat actual search and maximize controls exercised');await item.context.close();}
}finally{await browser.close();fs.writeFileSync('reports/extended-performance-2026-09-18/interactive.json',JSON.stringify(report,null,2));console.log('INTERACTIVE_SUMMARY '+JSON.stringify(report.assertions));}
// Findings are retained even when a budget fails; reviewer must resolve them.
})().catch(e=>{console.error(e);process.exitCode=1});`;
new Function('require',prefix+body)(require);
