// Exercise network-bearing public APIs with synthetic keys, never a real account.
const fs=require('fs');let prefix=fs.readFileSync('tests/performance/extended.cjs','utf8').split('try{\nfor(const file of files)')[0];
prefix=prefix.replace("fs.readFileSync(file,'utf8')","fs.readFileSync(file,'utf8').replace('minGapMs:1100,retryDelays:[3000,6000,12000]','minGapMs:1,retryDelays:[1,1,1]')");
const body=String.raw`
report.fixture='Offline real-browser API error/recovery and burst tests. Synthetic fake key, stubbed fetch/GM responses, no real Torn or external-write actions. Production public read-only methods; N/A for DOM-only scripts. Auditor fixture ONLY scales rate waits to 1ms and retry delays to 1ms; production stays at 1100ms and 3/6/12s, with independent rate-spacing regression.';
try{
for(const file of files.filter(x=>x.startsWith('SakaLuX')&&!/Bazaar|Chat-|Suite/.test(x))){const item=await setup(file);const {page}=item;await page.evaluate(({file,registry})=>{if(file.includes('Script-Hub'))window.SakaLuXScriptHub.setApiKey('SYNTHETIC-NOT-A-REAL-KEY');else window.SakaLuXScriptHub={getApiKey:()=> 'SYNTHETIC-NOT-A-REAL-KEY'};if(file.includes('Account-')){const get=window.GM_getValue;window.GM_getValue=(k,v)=>k==='SakaLuX_AUDITOR_TORN_API_KEY'?'SYNTHETIC-NOT-A-REAL-KEY':get(k,v);}if(file.includes('Stock'))localStorage.setItem('SLX_STOCK_API_KEY','SYNTHETIC-NOT-A-REAL-KEY');if(file.includes('Market'))history.replaceState({},'','/page.php?sid=ItemMarket&itemID=206');
const data={items:[{id:206,name:'Fixture Enhancer',type:'Enhancer',value:{market_price:100}}],inventory:[],ammo:[],events:[],stocks:[{id:1,acronym:'TSB',current_price:100}],money:{onhand:1000000},job:{company_id:0},workstats:{manual_labor:100,intelligence:100,endurance:100},profile:{player_id:1000,name:'Fixture'},basic:{player_id:1000},battlestats:{strength:100,speed:100,defense:100,dexterity:100},strength:100,speed:100,defense:100,dexterity:100,itemmarket:{item:{id:206,name:'Fixture',type:'Enhancer'},listings:[]},eliminationteam:[],eliminationteams:[]};
window.fetch=async url=>{const mode=__stress.network;__stress.requests.push({url:String(url).replace(/key=[^&]*/g,'key=FIXTURE'),mode,at:Date.now()});if(mode==='slow')await new Promise(r=>setTimeout(r,file.includes('Account-')?5:200));if(mode==='offline')throw Error('Fixture offline');return {ok:mode!=='429',status:mode==='429'?429:200,json:async()=>{if(mode==='malformed')throw SyntaxError('Fixture malformed JSON');return mode==='429'?{error:{code:5,error:'Fixture rate limit'}}:String(url).includes('scripts.json')?registry:data},text:async()=> mode==='malformed'?'{':String(url).includes('.meta.js')?'// @version 0.0.1':JSON.stringify(data)}};
window.GM_xmlhttpRequest=opts=>{const mode=__stress.network;__stress.requests.push({url:String(opts.url).replace(/key=[^&]*/g,'key=FIXTURE'),mode,at:Date.now()});const id=setTimeout(()=>{if(mode==='offline')opts.onerror?.({status:0});else opts.onload?.({status:mode==='429'?429:200,responseText:mode==='malformed'?'{':JSON.stringify(mode==='429'?{error:{code:5,error:'Fixture rate limit'}}:String(opts.url).includes('scripts.json')?registry:data)});},mode==='slow'?(file.includes('Account-')?5:200):0);return {abort(){clearTimeout(id)}}};GM.xmlHttpRequest=GM_xmlhttpRequest;
},{file,registry});
const samples=[];for(const mode of ['slow','offline','429','malformed','ok']){const result=await page.evaluate(async({file,registry,mode})=>{__stress.network=mode;const entry=registry.scripts.find(x=>decodeURIComponent(x.sourceUrl||'').endsWith('/'+file));const api=window[entry?.apiGlobal||(file.includes('Script-Hub')?'SakaLuXScriptHub':'SakaLuXAccountAuditor')];const method=file.includes('Elimination')?'testTornKey':file.includes('Market')?'loadoutComparator':file.includes('Account-')?'snapshot':api.hardRefresh?'hardRefresh':'refresh';const start=__stress.requests.length;const call=()=>Promise.resolve().then(()=>api[method](true));const calls=mode==='slow'?Array.from({length:20},call):[call()];const outcome=await Promise.race([Promise.allSettled(calls),new Promise(r=>setTimeout(()=>r('deadline'),8000))]);return {mode,method,callers:calls.length,deadline:outcome==='deadline',rejected:Array.isArray(outcome)?outcome.filter(x=>x.status==='rejected').length:0,reasons:Array.isArray(outcome)?[...new Set(outcome.filter(x=>x.status==='rejected').map(x=>x.reason?.message))]:[],requests:__stress.requests.length-start,health:api.health?.()||undefined};},{file,registry,mode});samples.push(result);await page.waitForTimeout(250);}
const row={file,samples,errors:item.errors};report.results.push(row);console.log('NETWORK_BROWSER_RESULT '+JSON.stringify(row));check(item.errors.length===0,file+' network modes no uncaught JS errors');check(samples.every(x=>!x.deadline),file+' network operations settle within fixture deadline');check(samples.some(x=>x.requests>0),file+' actual production API requests exercised');await item.context.close();}
}finally{await browser.close();fs.writeFileSync('reports/extended-performance-2026-09-18/network-browser.json',JSON.stringify(report,null,2));console.log('NETWORK_BROWSER_SUMMARY '+JSON.stringify(report.assertions));}
})().catch(e=>{console.error(e);process.exitCode=1});`;
new Function('require',prefix+body)(require);
