from pathlib import Path

p=Path('SakaLuX-Suite.user.js')
s=p.read_text(encoding='utf-8')
s=s.replace('// @version      0.8.1','// @version      0.9.0',1)
s=s.replace("const VERSION='0.8.1';","const VERSION='0.9.0';",1)

# Idempotent prayer completion: avoid recursive applyModules loops on persistent success text.
s=s.replace("function markPrayed(){localStorage.setItem(K.prayerDay,utcDay());applyModules()}","function markPrayed(){if(prayedToday())return;localStorage.setItem(K.prayerDay,utcDay());syncReminderIcons()}",1)

# Richer country metadata for all Torn travel destinations and aliases.
old="const COUNTRY={mexico:'🇲🇽',canada:'🇨🇦',cayman:'🇰🇾',hawaii:'🇺🇸',uk:'🇬🇧','united kingdom':'🇬🇧',argentina:'🇦🇷',switzerland:'🇨🇭',japan:'🇯🇵',china:'🇨🇳',uae:'🇦🇪','united arab emirates':'🇦🇪',southafrica:'🇿🇦','south africa':'🇿🇦'};"
new="const COUNTRY_META={mexico:{flag:'🇲🇽',label:'Mexico'},canada:{flag:'🇨🇦',label:'Canada'},cayman:{flag:'🇰🇾',label:'Cayman Islands'},hawaii:{flag:'🇺🇸',label:'Hawaii'},uk:{flag:'🇬🇧',label:'United Kingdom'},argentina:{flag:'🇦🇷',label:'Argentina'},switzerland:{flag:'🇨🇭',label:'Switzerland'},japan:{flag:'🇯🇵',label:'Japan'},china:{flag:'🇨🇳',label:'China'},uae:{flag:'🇦🇪',label:'UAE'},'south africa':{flag:'🇿🇦',label:'South Africa'}};\nconst COUNTRY_ALIASES={'united kingdom':'uk',england:'uk','cayman islands':'cayman','united arab emirates':'uae',southafrica:'south africa'};\nconst COUNTRY=Object.fromEntries(Object.entries(COUNTRY_META).map(([k,v])=>[k,v.flag]));"
if old in s:s=s.replace(old,new,1)

# Add CSS for item tooltip portal and richer mobile cards.
css_anchor=".slx-war-wide{position:fixed!important;inset:8px!important;z-index:2147483646!important;overflow:auto!important;margin:0!important}.slx-armory-loaned{outline:1px solid #b44!important}.slx-armory-available{outline:1px solid #285!important}"
css_new=css_anchor+"\n.slx-item-tip{position:fixed;z-index:2147483647;max-width:min(340px,calc(100vw - 24px));background:#0f141c;color:#eef4ff;border:1px solid #4b6685;border-radius:10px;padding:10px 12px;box-shadow:0 10px 30px #000b;font-size:11px;line-height:1.45;pointer-events:auto}.slx-item-tip b{color:#8acbff}.slx-travel-grid,.slx-company-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:6px;margin-top:8px}.slx-mini-card{border:1px solid #374353;border-radius:8px;background:#111821;padding:7px}.slx-mini-card b{display:block;color:#eef4ff}.slx-risk-good{color:#8ee5b4}.slx-risk-mid{color:#e8bf67}.slx-risk-bad{color:#ff9bb3}"
if css_anchor in s:s=s.replace(css_anchor,css_new,1)

def replace_func(name,next_name,new):
    global s
    a=s.index('function '+name+'(')
    b=s.index('function '+next_name+'(',a)
    s=s[:a]+new.rstrip()+"\n"+s[b:]

replace_func('itemSignals','onEventsPage',r'''function itemSignals(){
 document.querySelectorAll('.slx-item-tags').forEach(x=>x.remove());document.querySelectorAll('.slx-item-tip').forEach(x=>x.remove());
 if(!state['item-signals'])return;
 const cfg={...ITEM_CFG_DEFAULTS,...load(SLX_KEYS.item,{})},map={OC:'oc',ENERGY:'energy',NERVE:'nerve',HAPPY:'happy',HEAL:'heal',ENH:'enh'};
 const candidates=[...document.querySelectorAll('li,tr,[class*="item"],[data-item],[data-itemid],[data-item-id],a[href*="itemID="],img[src*="/images/items/"]')].filter(el=>!el.closest('#'+IDS.overlay)&&!el.closest('.slx-suite-float')&&!el.closest('.slx-item-tip'));
 const seen=new WeakSet();
 const getId=el=>Number(el.getAttribute?.('data-itemid')||el.getAttribute?.('data-item-id')||(el.getAttribute?.('href')||'').match(/itemID=(\d+)/i)?.[1]||(el.getAttribute?.('src')||'').match(/\/images\/items\/(\d+)\//i)?.[1]||el.querySelector?.('[data-itemid],[data-item-id],a[href*="itemID="],img[src*="/images/items/"]')?.getAttribute?.('data-itemid')||0);
 const infer=(txt,id)=>{const low=txt.toLowerCase(),out=[];for(const r of ITEM_RULES)if(cfg[map[r.tag]]&&r.names.some(n=>low.includes(n.toLowerCase())))out.push({tag:r.tag,note:r.note});const intel=ITEM_ID_INTEL[id];if(intel&&cfg[map[intel.tag]]&&!out.some(x=>x.tag===intel.tag))out.unshift({tag:intel.tag,note:intel.note});for(const [tag,re,note] of [['ENERGY',/\+\s*\d+\s*energy/i,'Visible energy gain'],['NERVE',/\+\s*\d+\s*nerve/i,'Visible nerve gain'],['HAPPY',/\+\s*\d+\s*(?:happy|happiness)/i,'Visible happiness gain'],['HEAL',/(?:heal|life|medical cooldown|hospital time)/i,'Medical / recovery effect'],['ENH',/(?:enhancer|temporary effect|duration|cooldown reduction)/i,'Temporary / enhancer effect'],['OC',/(?:organized crime|\boc\b|required role item|crime requirement)/i,'OC / crime requirement']])if(cfg[map[tag]]&&re.test(txt)&&!out.some(x=>x.tag===tag))out.push({tag,note});return out};
 const showTip=(el,title,items,id,txt)=>{document.querySelectorAll('.slx-item-tip').forEach(x=>x.remove());const tip=document.createElement('div');tip.className='slx-item-tip';tip.innerHTML=`<b>${esc(title||'Item')}</b>${id?` · #${id}`:''}<br>${items.map(x=>`<b>${esc(x.tag)}</b> — ${esc(x.note)}`).join('<br>')}<hr style="border-color:#293443">${esc(txt.slice(0,360))}`;document.body.appendChild(tip);const r=el.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-tip.offsetWidth-8,r.left))+'px';tip.style.top=Math.max(8,Math.min(innerHeight-tip.offsetHeight-8,r.bottom+6))+'px';setTimeout(()=>document.addEventListener('pointerdown',e=>{if(!tip.contains(e.target)&&!el.contains(e.target))tip.remove()},{once:true}),0)};
 for(const raw of candidates){const el=raw.matches?.('img')?(raw.closest('li,tr,[class*="item"],[data-item],[data-itemid],[data-item-id],a')||raw):raw;if(seen.has(el)||el.querySelector?.('.slx-item-tags'))continue;seen.add(el);if([...el.children||[]].some(c=>c.matches?.('li,tr,[class*="item"],[data-item],[data-itemid],[data-item-id]')))continue;const txt=(el.innerText||el.getAttribute?.('aria-label')||el.getAttribute?.('title')||raw.getAttribute?.('alt')||'').trim();if(!txt||txt.length>500)continue;const id=getId(el)||getId(raw),matches=infer(txt,id);if(!matches.length)continue;const wrap=document.createElement('div');wrap.className='slx-item-tags';const title=(el.querySelector?.('[class*="name"]')?.textContent||raw.getAttribute?.('alt')||txt.split('\n')[0]).trim();for(const r of matches){const b=document.createElement('button');b.type='button';b.className='slx-item-tag';b.textContent=r.tag;b.title=r.note;b.setAttribute('aria-label',`${r.tag}: ${r.note}`);b.onclick=e=>{e.preventDefault();e.stopPropagation();showTip(el,title,matches,id,txt)};wrap.appendChild(b)}el.appendChild(wrap)}
}
''')

# Recovery planner: enforce cooldown awareness, owned quantity, and explicit efficiency ranking.
replace_func('recoveryData','openRecoveryPanel',r'''function recoveryData(){const hp=visibleLife(),hosp=hospitalMinutes(),medCd=medicalCooldownMinutes(),bonus=recoveryBonus(),missing=hp?Math.max(0,hp.max-hp.cur):0;let items=RECOVERY_ITEMS.filter(x=>!(recoveryCfg.noDrugs&&x.drug)).map(x=>{const pct=x.healPct*(1+bonus/100),heal=hp?Math.max(1,Math.round(hp.max*pct/100)):0,need=hp&&missing>0?Math.max(1,Math.ceil(missing/heal)):0,qty=inventoryQty(x.name),usable=qty===null?need:Math.min(need,qty),restored=heal*usable,waste=hp?Math.max(0,restored-missing):0,eff=heal/Math.max(1,x.cooldown||1);return{...x,healPct:pct,heal,count:need,qty,usable,restored,waste,eff}});const score=x=>recoveryCfg.order==='exit'?x.hospMin:recoveryCfg.order==='full'?x.restored:recoveryCfg.order==='waste'?-x.waste:recoveryCfg.order==='cooldown'?x.eff:recoveryCfg.order==='strongest'?x.healPct:(x.healPct*3)+(x.hospMin/20)+(x.eff/5)-(x.waste/Math.max(1,hp?.max||1))*15;items.sort((a,b)=>score(b)-score(a));const blocked=!!(recoveryCfg.respectCooldown&&medCd>0);return{hp,hosp,medCd,bonus,missing,blocked,items}}
''')
replace_func('openRecoveryPanel','openRecoverySettings',r'''function openRecoveryPanel(){const d=recoveryData(),usable=d.items.filter(x=>x.qty===null||x.qty>0),best=usable[0]||d.items[0],status=d.blocked?`Medical cooldown active — <b>${Math.round(d.medCd)} min</b> remaining.`:(best?`Suggested now: <b>${esc(best.name)}</b>${d.hp?` × ${Math.max(1,best.usable||best.count)}`:''}${best.qty!==null?` · owned ${best.qty}`:''}`:'No suggestion available.');toggleFloat('slx-recovery-panel','Recovery Planner',`${d.hp?`Life: <b>${d.hp.cur.toLocaleString()} / ${d.hp.max.toLocaleString()}</b> · missing <b>${d.missing.toLocaleString()}</b><br>`:'Life: <b>not detected</b><br>'}Hospital: <b>${Math.round(d.hosp)} min</b><br>Medical cooldown: <b>${Math.round(d.medCd)} min</b><br>Recovery bonus: <b>+${d.bonus}%</b><br>${status}<hr style="border-color:#333">${d.items.slice(0,5).map(x=>`${esc(x.name)} — ${x.healPct.toFixed(1)}%${d.hp?` · ${x.count} needed · ${x.restored.toLocaleString()} est. restore · waste ${x.waste.toLocaleString()}`:''}${x.qty!==null?` · owned ${x.qty}`:''}`).join('<br>')}<br><button class="slxs-settings" id="slx-recovery-settings-open">SETTINGS</button>`,()=>{document.getElementById('slx-recovery-settings-open').onclick=openRecoverySettings})}
''')

replace_func('travelMap','ocRoleMatch',r'''function travelMap(){
 document.querySelectorAll('.slx-country-tag').forEach(x=>x.remove());document.getElementById('slx-travel-summary')?.remove();if(!state['member-travel-map']||!/faction|profiles\.php/i.test(location.href))return;
 const normalize=x=>COUNTRY_ALIASES[x]||x,ov=load(SLX_KEYS.travel,{}),rows=factionRows(),counts={};
 for(const r of rows){const id=(r.a.href.match(/XID=(\d+)/)||[])[1]||r.n,low=r.t.toLowerCase();let c=normalize(ov[id]||Object.keys({...COUNTRY_META,...COUNTRY_ALIASES}).find(x=>low.includes(x))||'');if(!COUNTRY_META[c])continue;counts[c]=(counts[c]||0)+1;const tag=document.createElement('button');tag.type='button';tag.className='slx-country-tag slx-badge-mini';tag.textContent=COUNTRY_META[c].flag;tag.title=`${COUNTRY_META[c].label} — tap to edit`;tag.dataset.country=c;tag.onclick=e=>{e.preventDefault();e.stopPropagation();const v=prompt('Country override (blank = automatic):',COUNTRY_META[c].label);if(v===null)return;const k=normalize(v.trim().toLowerCase());if(v.trim())ov[id]=k;else delete ov[id];save(SLX_KEYS.travel,ov);travelMap()};r.a.after(tag)}
 const entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]||COUNTRY_META[a[0]].label.localeCompare(COUNTRY_META[b[0]].label));if(entries.length){pagePanel('slx-travel-summary','🌍 Member Travel Map',`<button id="slx-travel-sort">SORT COUNT/NAME</button> <button id="slx-travel-all">SHOW ALL</button> <button id="slx-travel-wipe">WIPE OVERRIDES</button><div class="slx-travel-grid">${entries.map(([c,n])=>`<button class="slx-mini-card" data-country="${esc(c)}"><b>${COUNTRY_META[c].flag} ${esc(COUNTRY_META[c].label)}</b>${n} member${n===1?'':'s'}</button>`).join('')}</div>`);const panel=document.getElementById('slx-travel-summary');panel?.querySelectorAll('[data-country]').forEach(b=>b.onclick=()=>{const c=b.dataset.country;rows.forEach(r=>{const tag=r.e.querySelector?.(`.slx-country-tag[data-country="${CSS.escape(c)}"]`);if(!r.e.dataset.slxOrigDisplay)r.e.dataset.slxOrigDisplay=r.e.style.display||'__empty__';r.e.style.display=tag?'': 'none'})});document.getElementById('slx-travel-sort')?.addEventListener('click',()=>{entries.sort((a,b)=>COUNTRY_META[a[0]].label.localeCompare(COUNTRY_META[b[0]].label));const grid=panel?.querySelector('.slx-travel-grid');if(grid)grid.innerHTML=entries.map(([c,n])=>`<button class="slx-mini-card" data-country="${esc(c)}"><b>${COUNTRY_META[c].flag} ${esc(COUNTRY_META[c].label)}</b>${n} member${n===1?'':'s'}</button>`).join('');travelMap()});document.getElementById('slx-travel-all')?.addEventListener('click',()=>rows.forEach(r=>{r.e.style.display=r.e.dataset.slxOrigDisplay==='__empty__'?'':(r.e.dataset.slxOrigDisplay||'')}));document.getElementById('slx-travel-wipe')?.addEventListener('click',()=>{if(confirm('Clear all country overrides?')){localStorage.removeItem(SLX_KEYS.travel);travelMap()}})}
}
''')

replace_func('ocRoleMatch','ocReadiness',r'''function ocRoleMatch(){document.querySelectorAll('.slx-oc-match,.slx-oc-pred').forEach(x=>x.remove());if(!state['oc-role-match']||!/(organizedcrimes|crime|faction)/i.test(location.href))return;const cfg={...OC_CFG_DEFAULTS,...load(SLX_KEYS.ocCfg,{})};for(const e of document.querySelectorAll('li,tr,[class*="crime"],[class*="role"],[class*="panel"]')){const t=e.innerText||'';if(t.length>1600||!/(role|success|position|chance)/i.test(t))continue;const ps=[...t.matchAll(/([A-Za-z][A-Za-z \-]{2,34})\s*[:\-]?\s*(\d{1,3}(?:\.\d+)?)\s*%/g)].map(m=>({n:m[1].trim(),p:+m[2]})).filter(x=>x.p<=100);if(!ps.length)continue;const sorted=[...ps].sort((a,b)=>b.p-a.p),best=sorted[0],avg=ps.reduce((a,x)=>a+x.p,0)/ps.length,tier=avg>=75?'HIGH':avg>=65?'NORMAL':avg>=50?'LOW':'CRITICAL',risk=avg>=75?'Balanced Team':avg>=65?'Moderate Risk':avg>=50?'Needs Attention':'High-Risk Assignment';const tag=document.createElement('span');tag.className='slx-oc-match slx-badge-mini';tag.textContent=`BEST ${best.n} ${best.p}%`;tag.title=`Suitability ${tier} · threshold ${cfg.threshold}%`;e.appendChild(tag);const pred=document.createElement('span');pred.className='slx-oc-pred slx-badge-mini';pred.textContent=`EST ${avg.toFixed(0)}% ${avg>=cfg.threshold?'✓':'⚠'} ${tier}`;pred.title=risk;e.appendChild(pred)}}
''')

replace_func('ocReadiness','warPerformance',r'''function ocReadiness(){
 document.getElementById('slx-oc-ready')?.remove();document.querySelectorAll('.slx-oc-loan-role').forEach(x=>x.remove());if(!state['oc-readiness']||!/(organizedcrimes|crime|faction)/i.test(location.href))return;
 const cfg={...OC_CFG_DEFAULTS,...load(SLX_KEYS.ocCfg,{})},t=document.body.innerText||'',no=/not (?:currently )?in an organized crime|not in an oc|join an organized crime/i.test(t),matches=[...t.matchAll(/(?:missing|required item|vacant role|not ready)[^\n]{0,160}/gi)].map(x=>x[0].trim());
 const sections=[...document.querySelectorAll('section,article,div,li')].filter(e=>/recruiting|planning/i.test((e.querySelector('h1,h2,h3,h4,[class*="title"]')?.textContent||'').trim())&&(e.innerText||'').length<8000),captured=[];for(const sec of sections){const phase=/recruiting/i.test(sec.innerText||'')?'Recruiting':'Planning';for(const m of (sec.innerText||'').matchAll(/(?:role|position)\s*:?\s*([A-Za-z][A-Za-z \-]{2,40})[\s\S]{0,120}?(?:requires?|required item)\s*:?\s*([A-Za-z0-9 '&\-]{3,60})/gi))captured.push({phase,role:m[1].trim(),item:m[2].trim()})}
 const generic=[...t.matchAll(/(?:requires?|required)\s*:?\s*([A-Za-z0-9 '&\-]{3,55})/gi)].map(x=>({phase:'Visible',role:'Unknown',item:x[1].trim()}));const requirements=[...captured,...generic].filter((x,i,a)=>a.findIndex(y=>y.phase===x.phase&&y.role===x.role&&y.item===x.item)===i).slice(0,200);if(requirements.length)save(SLX_KEYS.ocReq,{at:Date.now(),url:location.href,requirements});
 const scan=load(SLX_KEYS.ocReq,{requirements:[]}),loan=load(SLX_KEYS.armory,{rows:[]});let loanHits=0,reqHits=0;for(const e of document.querySelectorAll('li,tr,[class*="crime"],[class*="role"]')){const txt=(e.innerText||'').replace(/\s+/g,' ');if(txt.length>1400)continue;const role=(txt.match(/(?:role|position)\s*:?\s*([A-Za-z][A-Za-z \-]{2,35})/i)||[])[1],mem=(txt.match(/([A-Za-z0-9_\-]{2,30})\s*\[\d+\]/)||[])[1];if(!mem)continue;const held=(loan.rows||[]).filter(x=>x.h&&x.h.toLowerCase().includes(mem.toLowerCase())),needed=(scan.requirements||[]).filter(x=>!role||x.role==='Unknown'||x.role.toLowerCase().includes(role.toLowerCase())||role.toLowerCase().includes(x.role.toLowerCase()));const matching=held.filter(h=>needed.some(n=>(h.item||h.t||'').toLowerCase().includes(n.item.toLowerCase())));if(held.length){const b=document.createElement('span');b.className='slx-oc-loan-role slx-badge-mini';b.textContent=`🎒 ${held.length}${matching.length?` / ${matching.length} req`:''}`;b.title=[...held.map(x=>x.item||x.t),...matching.map(x=>'MATCH: '+(x.item||x.t))].join('\n');e.appendChild(b);loanHits++;reqHits+=matching.length}}
 if(no||matches.length||scan.requirements?.length)pagePanel('slx-oc-ready','✅ OC Readiness',`${no?'⚠ <b>Not in an active OC.</b><br>':''}${matches.length?`Warnings: <b>${matches.length}</b><br>${matches.slice(0,cfg.scope==='all'?12:6).map(esc).join('<br>')}`:'No visible missing-role/item warning.'}${scan.requirements?.length?`<br>Cached requirements: <b>${scan.requirements.length}</b> · ${scan.requirements.slice(0,8).map(x=>`${esc(x.phase)} / ${esc(x.role)} → ${esc(x.item)}`).join(' · ')}`:''}<br>Loan holders matched: <b>${loanHits}</b> · role-item matches: <b>${reqHits}</b> · scope: <b>${cfg.scope}</b>`)
}
''')

# War Performance: add reliability, participation and risk filters independently.
replace_func('warPerformance','companyConsole',r'''function warPerformance(){
 document.getElementById('slx-war-performance')?.remove();if(!state['war-performance']||!/faction/i.test(location.href))return;
 const fr=factionRows(),rows=fr.map(x=>{const q=x.t.match(/respect[^0-9]{0,14}([\d,.]+)/i),h=x.t.match(/hits?[^0-9]{0,14}(\d+)/i),a=x.t.match(/attacks?[^0-9]{0,14}(\d+)/i),ret=x.t.match(/retaliations?[^0-9]{0,14}(\d+)/i),assist=x.t.match(/assists?[^0-9]{0,14}(\d+)/i);return{n:x.n,res:q?+q[1].replace(/,/g,''):0,h:h?+h[1]:0,a:a?+a[1]:0,ret:ret?+ret[1]:0,assist:assist?+assist[1]:0,risk:x.status!=='Okay'||x.act==='Offline',status:x.status,act:x.act}}).filter(x=>x.res||x.h||x.a||x.ret||x.assist),d=load(SLX_KEYS.war,{reports:[],hidden:[],search:'',sort:'score',riskFilter:'ALL'});if(!rows.length)return;
 d.reports??=[];d.hidden??=[];const resultText=(document.body.innerText||'').match(/ranked war[\s\S]{0,250}?(victory|won|defeat|lost)/i);d.history??=[];if(resultText){const outcome=/victory|won/i.test(resultText[1])?'W':'L',key=location.pathname+location.search+location.hash+'|'+outcome;if(!d.history.some(x=>x.key===key))d.history.unshift({key,outcome,at:Date.now()});d.history=d.history.slice(0,200)}
 const score=x=>x.res*10+x.h*2+x.a+x.ret*3+x.assist,sig=rows.map(x=>`${x.n}:${x.res}:${x.h}:${x.a}:${x.ret}:${x.assist}`).join('|');if(d.reports[0]?.sig!==sig)d.reports=[{sig,at:Date.now(),url:location.href,rows},...d.reports].slice(0,100);const historical=n=>d.reports.map(r=>r.rows?.find(x=>x.n===n)?.h??null).filter(x=>x!==null).slice(0,5),decorate=x=>{const hs=historical(x.n),part=hs.length?Math.round(hs.filter(v=>v>0).length/hs.length*100):100,zeros=hs.filter(v=>v===0).length,rel=Math.max(0,Math.min(100,Math.round(part-zeros*9+(x.h>0?5:0)-(x.risk?10:0)))),risk=rel<40?'DANGER':rel<60?'HIGH':rel<75?'MEDIUM':rel<90?'LOW':'OK';return{...x,score:score(x),history:hs,part,rel,riskLevel:risk}};const ranked=rows.map(decorate).sort((a,b)=>d.sort==='name'?a.n.localeCompare(b.n):d.sort==='risk'?(a.rel-b.rel||b.score-a.score):b.score-a.score);save(SLX_KEYS.war,d);const visible=ranked.filter(x=>!d.hidden.includes(x.n)&&(!d.search||x.n.toLowerCase().includes(d.search.toLowerCase()))&&(d.riskFilter==='ALL'||x.riskLevel===d.riskFilter));pagePanel('slx-war-performance','⚔️ War Performance',`<button id="slx-war-wide">WIDE</button> <button id="slx-war-risk">SORT RISK</button> <button id="slx-war-filter">FILTER ${esc(d.riskFilter)}</button> <button id="slx-war-search">SEARCH</button> <button id="slx-war-aar">AAR</button> <button id="slx-war-backup">BACKUP</button><br>Tracked: <b>${rows.length}</b> · MVP: <b>${esc(ranked[0].n)}</b> · avg reliability: <b>${Math.round(ranked.reduce((a,x)=>a+x.rel,0)/ranked.length)}%</b> · reports: <b>${d.reports.length}</b> · W/L: <b>${d.history.filter(x=>x.outcome==='W').length}/${d.history.filter(x=>x.outcome==='L').length}</b><br>${visible.slice(0,40).map((x,i)=>`${i+1}. <button data-war-member="${esc(encodeURIComponent(x.n))}">${esc(x.n)}</button> — ${x.res}R / ${x.h}H / ${x.a}A · Rel <b>${x.rel}%</b> · Part ${x.part}% · ${x.riskLevel} · L5 [${x.history.join(',')||'—'}]`).join('<br>')}`);
 const panel=document.getElementById('slx-war-performance');document.getElementById('slx-war-wide')?.addEventListener('click',()=>panel?.classList.toggle('slx-war-wide'));document.getElementById('slx-war-risk')?.addEventListener('click',()=>{d.sort=d.sort==='risk'?'score':'risk';save(SLX_KEYS.war,d);warPerformance()});document.getElementById('slx-war-filter')?.addEventListener('click',()=>{const opts=['ALL','OK','LOW','MEDIUM','HIGH','DANGER'];d.riskFilter=opts[(opts.indexOf(d.riskFilter)+1)%opts.length];save(SLX_KEYS.war,d);warPerformance()});document.getElementById('slx-war-search')?.addEventListener('click',()=>{d.search=prompt('Member search:',d.search||'')||'';save(SLX_KEYS.war,d);warPerformance()});document.getElementById('slx-war-aar')?.addEventListener('click',()=>{const top=ranked.slice(0,5),danger=ranked.filter(x=>['HIGH','DANGER'].includes(x.riskLevel));prompt('After Action Report',`War report ${new Date().toLocaleString()}\nMembers: ${rows.length}\nAvg reliability: ${Math.round(ranked.reduce((a,x)=>a+x.rel,0)/ranked.length)}%\nHigh risk: ${danger.map(x=>x.n).join(', ')||'none'}\nTop: ${top.map(x=>x.n+' '+x.res+'R/'+x.h+'H').join(', ')}`)});document.getElementById('slx-war-backup')?.addEventListener('click',()=>prompt('War Performance backup:',JSON.stringify(d)));panel?.querySelectorAll('[data-war-member]').forEach(b=>b.onclick=()=>{const n=decodeURIComponent(b.dataset.warMember),x=ranked.find(y=>y.n===n);if(confirm(`${n}\n${x.res} respect · ${x.h} hits · ${x.a} attacks\nReliability ${x.rel}% · Participation ${x.part}% · ${x.riskLevel}\n\nHide from ledger?`)){if(!d.hidden.includes(n))d.hidden.push(n);save(SLX_KEYS.war,d);warPerformance()}})
}
''')

replace_func('companyConsole','oddsScout',r'''function companyConsole(){
 document.getElementById('slx-company-console')?.remove();if(!state['company-console']||!/company/i.test(location.href))return;
 const t=document.body.innerText||'',emps=[...document.querySelectorAll('tr,li,[class*="employee"]')].filter(e=>/wage|position|employee|train|effectiveness/i.test(e.innerText||'')),employeeRows=emps.map(e=>{const tx=(e.innerText||'').replace(/\s+/g,' '),a=e.querySelector('a[href*="profiles.php"],a[href*="XID="]'),eff=+((tx.match(/(?:effectiveness|efficiency)[^0-9]{0,10}(\d+)/i)||[])[1]||0);return{name:(a?.textContent||tx.split(' ')[0]||'Employee').trim(),wage:+((tx.match(/(?:wage|salary)[^$]{0,12}\$([\d,]+)/i)||[])[1]||'0').replace(/,/g,''),eff,text:tx}}),wages=[...t.matchAll(/(?:wage|salary)[^$]{0,20}\$([\d,]+)/gi)].map(m=>+m[1].replace(/,/g,'')),income=(t.match(/(?:income|revenue|profit)[^$]{0,30}\$([\d,]+)/i)||[])[1],stock=(t.match(/stock[^0-9$]{0,20}([\d,]+)/i)||[])[1],tr=(t.match(/trains?[^0-9]{0,20}(\d+)/i)||[])[1],tax=(t.match(/tax[^$]{0,25}\$([\d,]+)/i)||[])[1],d=load(SLX_KEYS.company,{snapshots:[],training:[],tax:[],prices:[],stockLog:[]}),snap={at:Date.now(),employees:emps.length,wages:wages.reduce((a,b)=>a+b,0),income:income?+income.replace(/,/g,''):null,stock:stock?+stock.replace(/,/g,''):null,trains:+tr||null,tax:tax?+tax.replace(/,/g,''):null};if(!d.snapshots[0]||Date.now()-d.snapshots[0].at>300000)d.snapshots=[snap,...d.snapshots].slice(0,250);if(snap.stock!=null&&d.stockLog[0]?.stock!==snap.stock)d.stockLog.unshift({at:Date.now(),stock:snap.stock});d.stockLog=d.stockLog.slice(0,250);save(SLX_KEYS.company,d);const sorted=[...employeeRows].sort((a,b)=>(b.eff-a.eff)||(a.wage-b.wage));
 pagePanel('slx-company-console','🏢 Company Console',`Employees: <b>${emps.length}</b> · wages: <b>$${snap.wages.toLocaleString()}</b> · income: <b>${snap.income!=null?'$'+snap.income.toLocaleString():'—'}</b> · stock: <b>${snap.stock??'—'}</b> · trains: <b>${snap.trains??'—'}</b> · tax: <b>${snap.tax!=null?'$'+snap.tax.toLocaleString():'—'}</b><br><button id="slx-co-price">PRICE</button> <button id="slx-co-train">TRAIN</button> <button id="slx-co-tax">TAX</button> <button id="slx-co-history">HISTORY</button> <button id="slx-co-emps">EMPLOYEES</button> <button id="slx-co-backup">BACKUP</button><div class="slx-company-grid">${sorted.slice(0,12).map(x=>`<div class="slx-mini-card"><b>${esc(x.name)}</b>Eff ${x.eff||'—'} · $${x.wage.toLocaleString()}</div>`).join('')}</div>`);
 document.getElementById('slx-co-price')?.addEventListener('click',()=>{const c=+prompt('Cost per item')||0,m=+prompt('Markup %','10')||0,v=Math.round(c*(1+m/100));if(v){d.prices.unshift({at:Date.now(),cost:c,markup:m,price:v});d.prices=d.prices.slice(0,200);save(SLX_KEYS.company,d)}alert('Suggested price: $'+v.toLocaleString())});document.getElementById('slx-co-train')?.addEventListener('click',()=>{const n=prompt('Training note / employee:');if(n){d.training.unshift({at:Date.now(),note:n});d.training=d.training.slice(0,500);save(SLX_KEYS.company,d)}});document.getElementById('slx-co-tax')?.addEventListener('click',()=>{const v=+prompt('Tax amount')||0;if(v){d.tax.unshift({at:Date.now(),amount:v});d.tax=d.tax.slice(0,500);save(SLX_KEYS.company,d)}});document.getElementById('slx-co-emps')?.addEventListener('click',()=>prompt('Employees sorted by effectiveness:',sorted.slice(0,60).map(x=>`${x.name} — eff ${x.eff||'—'} — $${x.wage.toLocaleString()}`).join('\n')));document.getElementById('slx-co-history')?.addEventListener('click',()=>alert(`Snapshots: ${d.snapshots.length}\nStock changes: ${d.stockLog.length}\nTraining logs: ${d.training.length}\nTax logs: ${d.tax.length}\nPrice records: ${d.prices.length}`));document.getElementById('slx-co-backup')?.addEventListener('click',()=>prompt('Company Console backup:',JSON.stringify(d)))
}
''')

replace_func('oddsScout','raceLeague',r'''function oddsScout(){
 document.querySelectorAll('.slx-odds-hint').forEach(x=>x.remove());document.getElementById('slx-odds-summary')?.remove();if(!state['odds-scout']||!/(casino|bookie|sports)/i.test(location.href))return;
 const cfg={...ODDS_CFG_DEFAULTS,...load(SLX_KEYS.odds,{})},markets=[],seen=new Set(),active=(document.querySelector('[class*="tabs"] [class*="active"][title],[class*="tab"][class*="active"]')?.getAttribute('title')||document.querySelector('[class*="tabs"] [class*="active"]')?.textContent||'Sports').trim();for(const e of document.querySelectorAll('tr,li,[class*="bet"],[class*="market"],[class*="event"],[class*="sport"]')){const t=(e.innerText||'').trim().replace(/\s+/g,' ');if(t.length>1200||t.length<8)continue;const key=t.slice(0,220);if(seen.has(key))continue;seen.add(key);const o=[...t.matchAll(/(?:^|\s)x?([1-9]\d*(?:\.\d{1,3})?)(?=\s|$)/gi)].map(m=>+m[1]).filter(x=>x>=1.01&&x<=1000);if(o.length<2||o.length>8)continue;const probs=o.map(x=>100/x),sum=probs.reduce((a,x)=>a+x,0),margin=sum-100,spread=Math.max(...probs)-Math.min(...probs),risk=spread>=45?'One-Sided':spread<=15?'Coin Flip':'Competitive',best=Math.max(...probs);if(e.querySelector('.slx-odds-hint'))continue;const tag=document.createElement('span');tag.className='slx-odds-hint slx-badge-mini';tag.textContent=`M ${margin.toFixed(1)}% · ${risk}`;tag.title='Implied: '+probs.map(x=>x.toFixed(1)+'%').join(' / ');e.appendChild(tag);markets.push({t,o,probs,margin,spread,risk,best})}
 if(markets.length){const best=[...markets].sort((a,b)=>a.margin-b.margin)[0],sport=/football|soccer/i.test(active+' '+best.t)?'football':/basketball|nba/i.test(active+' '+best.t)?'basketball':/tennis/i.test(active+' '+best.t)?'tennis':/baseball|mlb/i.test(active+' '+best.t)?'baseball':active||'sports';pagePanel('slx-odds-summary','🎲 Odds Scout',`<button id="slx-odds-collapse">${cfg.collapsed?'EXPAND':'HIDE'}</button> ${cfg.collapsed?'':`Sport: <b>${esc(sport)}</b> · markets: <b>${markets.length}</b> · lowest margin: <b>${best.margin.toFixed(1)}%</b> · risk: <b>${best.risk}</b><br>${markets.sort((a,b)=>a.margin-b.margin).slice(0,10).map(x=>`${x.margin.toFixed(1)}% · ${x.risk} — ${esc(x.t.slice(0,95))}`).join('<br>')}<br><button id="slx-odds-research">RESEARCH EVENT</button>`}`);document.getElementById('slx-odds-collapse')?.addEventListener('click',()=>{cfg.collapsed=!cfg.collapsed;save(SLX_KEYS.odds,cfg);oddsScout()});document.getElementById('slx-odds-research')?.addEventListener('click',()=>{if(cfg.research===false)return;const q=encodeURIComponent(`${sport} ${best.t.slice(0,130)}`);window.open('https://www.google.com/search?q='+q,'_blank')})}
}
''')

# Racing extras: rename, CSV export and recompute leaderboard from saved race logs.
needle="<button id=\"slx-race-new\">NEW</button> <button id=\"slx-race-switch\">SWITCH</button> <button id=\"slx-race-log\">RACE LOG</button> <button id=\"slx-race-stats\">STATS</button> <button id=\"slx-race-backup\">BACKUP/IMPORT</button> <button id=\"slx-race-del\">DELETE</button>"
rep="<button id=\"slx-race-new\">NEW</button> <button id=\"slx-race-switch\">SWITCH</button> <button id=\"slx-race-rename\">RENAME</button> <button id=\"slx-race-log\">RACE LOG</button> <button id=\"slx-race-stats\">STATS</button> <button id=\"slx-race-csv\">CSV</button> <button id=\"slx-race-backup\">BACKUP/IMPORT</button> <button id=\"slx-race-del\">DELETE</button>"
if needle in s:s=s.replace(needle,rep,1)
insert="document.getElementById('slx-race-switch')?.addEventListener('click',()=>{const n=prompt('Championship:\\n'+Object.keys(d.champs).join('\\n'),d.active);if(n&&d.champs[n]){d.active=n;save(SLX_KEYS.race2,d);raceLeague()}});"
if insert in s:
 s=s.replace(insert,insert+"document.getElementById('slx-race-rename')?.addEventListener('click',()=>{const n=prompt('Rename championship:',d.active)?.trim();if(n&&n!==d.active&&!d.champs[n]){d.champs[n]=d.champs[d.active];delete d.champs[d.active];d.active=n;save(SLX_KEYS.race2,d);raceLeague()}});document.getElementById('slx-race-csv')?.addEventListener('click',()=>{const lines=['date,driver,position'];for(const r of [...c.races].reverse())for(const x of r.rows)lines.push(`${new Date(r.at).toISOString()},\"${String(x.n).replace(/\"/g,'\"\"')}\",${x.p}`);prompt('Race CSV:',lines.join('\\n'))});",1)

# Docs release notes.
doc=Path('greasyfork/SakaLuX-Suite.md')
if doc.exists():
 d=doc.read_text(encoding='utf-8')
 d=d.replace('**v0.8.1**','**v0.9.0**',1)
 d += "\n\n### v0.9.0 — deep parity pass\n- Item Signals now uses richer DOM/item-ID discovery, semantic effect inference, touch/click tooltips, and duplicate-safe markers.\n- Recovery Planner now respects medical cooldown, owned quantity, estimated restore, waste, and efficiency ranking.\n- Member Travel Map now covers all Torn travel destinations with aliases, filter cards, sorting, profile/faction flags, and mobile-friendly controls.\n- OC Role Match now exposes Low/Normal/High/Critical suitability tiers and configurable threshold status.\n- OC Readiness now scans visible Recruiting/Planning sections, caches role-item requirements, and correlates armory loans to those requirements.\n- War Performance now adds reliability, participation, L5 history, risk levels and risk filters.\n- Company Console adds employee effectiveness ranking, stock-change history and richer local management records.\n- Odds Scout adds sport detection, favourite/risk context and improved market analysis.\n- Race League Board adds championship rename and CSV export.\n- Daily Prayer completion was made idempotent to prevent recursive rerender loops.\n"
 doc.write_text(d,encoding='utf-8')

p.write_text(s,encoding='utf-8')
