'use strict';
const REGISTRY='https://raw.githubusercontent.com/SakaLuX/SakaLuX-Script-HUB/main/scripts.json';
const HUB='https://greasyfork.org/scripts/592699';
const $=id=>document.getElementById(id);
const tr={
en:{navScripts:'Scripts',navUpdates:'Updates',navAbout:'About',eyebrow:'THE SAKALUX PLATFORM',heroOne:'Your Torn tools.',heroTwo:'One powerful hub.',heroText:'Discover, install and keep your favorite Torn userscripts up to date — from a single command center.',explore:'Explore scripts →',installHub:'Install Script Hub ↗',modules:'modules',autoUpdates:'Live GitHub registry',libraryLabel:'YOUR ARSENAL',library:'Script library',librarySubtitle:'All SakaLuX tools, synced with the official registry.',releaseLabel:'RELEASE FEED',updatesTitle:'Latest updates',updatesSubtitle:'Release details from GitHub.',aboutTitle:'One ecosystem. More control.',aboutText:'SakaLuX brings your Torn tools together. Compatible with TornPDA and Tampermonkey.',independent:'Independent community project; not affiliated with Torn.',search:'Search scripts…',all:'All',empty:'No matching scripts.',install:'INSTALL ↗',online:'Live GitHub registry',offline:'GitHub unavailable',version:'Version'},
ro:{navScripts:'Scripturi',navUpdates:'Actualizări',navAbout:'Despre',eyebrow:'PLATFORMA SAKALUX',heroOne:'Scripturile tale Torn.',heroTwo:'Un singur hub puternic.',heroText:'Descoperă, instalează și actualizează scripturile Torn preferate dintr-un singur centru de control.',explore:'Descoperă scripturile →',installHub:'Instalează Script Hub ↗',modules:'module',autoUpdates:'Registry GitHub live',libraryLabel:'ARSENALUL TĂU',library:'Biblioteca de scripturi',librarySubtitle:'Toate modulele SakaLuX, sincronizate cu registrul oficial.',releaseLabel:'NOUTĂȚI',updatesTitle:'Ultimele actualizări',updatesSubtitle:'Informațiile vin direct din GitHub.',aboutTitle:'Un ecosistem. Mai mult control.',aboutText:'SakaLuX reunește instrumentele Torn. Compatibil cu TornPDA și Tampermonkey.',independent:'Proiect independent, neafiliat cu Torn.',search:'Caută scripturi…',all:'Toate',empty:'Niciun script găsit.',install:'INSTALARE ↗',online:'Registry GitHub live',offline:'GitHub indisponibil',version:'Versiunea'}};
let lang=localStorage.getItem('sakalux-lang')==='ro'?'ro':'en',scripts=[],category='all',selected=null,tab='info';
const t=k=>tr[lang][k]||k;
function elem(tag,cls,txt){let x=document.createElement(tag);if(cls)x.className=cls;if(txt!==undefined)x.textContent=txt;return x}
function validUrl(u){try{return new URL(u).protocol==='https:'&&['greasyfork.org','update.greasyfork.org','raw.githubusercontent.com','github.com'].includes(new URL(u).hostname)}catch{return false}}
function installUrl(s){return [s.downloadUrl,s.greasyForkUrl,s.sourceUrl].find(validUrl)||HUB}
function languages(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=t(x.dataset.i18n));$('search').placeholder=t('search');$('language').textContent=lang==='en'?'RO':'EN';render()}
function categories(){let el=$('categories');el.replaceChildren();for(const c of ['all',...[...new Set(scripts.map(x=>x.category||'Other'))].sort()]){let b=elem('button','pill'+(c===category?' active':''),c==='all'?t('all'):c);b.onclick=()=>{category=c;render()};el.append(b)}}
function cards(){let q=$('search').value.toLowerCase(),el=$('scriptsGrid');el.replaceChildren();let arr=scripts.filter(x=>(category==='all'||x.category===category)&&[x.name,x.description,x.category].join(' ').toLowerCase().includes(q));if(!arr.length){el.append(elem('div','empty',t('empty')));return}for(const s of arr){let a=elem('article','script-card'),h=elem('div','card-head'),title=elem('div'),foot=elem('div','card-foot');title.append(elem('div','card-title',s.name),elem('div','card-version','v'+s.version+' · '+(s.category||'Other')));h.append(elem('div','script-icon',s.icon||'◆'),title);a.append(h,elem('p','',s.description||''));for(const mode of ['info','new']){let b=elem('button','small-btn',mode.toUpperCase());b.onclick=()=>open(s,mode);foot.append(b)}let link=elem('a','small-btn install',t('install'));link.href=installUrl(s);link.target='_blank';link.rel='noopener noreferrer';foot.append(link);a.append(foot);el.append(a)}}
function updates(){let el=$('updatesList');el.replaceChildren();for(const s of scripts.filter(x=>x.release).sort((a,b)=>(b.release.date||'').localeCompare(a.release.date||'')).slice(0,8)){let d=elem('div','update-item'),l=elem('div');l.append(elem('strong','',s.name+' · v'+s.version),elem('p','',s.release.notes?.[0]||''));d.append(l,elem('time','',s.release.date||''));d.tabIndex=0;d.setAttribute('role','button');d.onclick=()=>open(s,'new');d.onkeydown=e=>{if(e.key==='Enter'){open(s,'new')}};el.append(d)}}
function render(){categories();cards();updates();if(selected)details()}
function open(s,mode){selected=s;tab=mode;details();$('details').showModal()}
function details(){let s=selected;if(!s)return;$('detailCategory').textContent=s.category||'';$('detailTitle').textContent=s.name+' · v'+s.version;$('tabInfo').classList.toggle('selected',tab==='info');$('tabNew').classList.toggle('selected',tab==='new');$('detailContent').textContent=tab==='info'?(s.info||s.description||''):[t('version')+': '+(s.release?.version||s.version),s.release?.date||'',...(s.release?.notes||[]).map(n=>'• '+n)].join('\n');$('detailInstall').href=installUrl(s);$('detailInstall').textContent=t('install')}
$('search').addEventListener('input',cards);$('language').onclick=()=>{lang=lang==='en'?'ro':'en';localStorage.setItem('sakalux-lang',lang);languages()};$('closeDialog').onclick=()=>$('details').close();$('tabInfo').onclick=()=>{tab='info';details()};$('tabNew').onclick=()=>{tab='new';details()};$('details').onclick=e=>{if(e.target===$('details'))$('details').close()};$('year').textContent=new Date().getFullYear();languages();
(async()=>{try{let r=await fetch(REGISTRY+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);let data=await r.json();if(!Array.isArray(data.scripts))throw Error('Invalid registry');scripts=data.scripts.filter(s=>s&&s.active!==false&&s.id&&s.name);$('moduleCount').textContent=scripts.length;$('registryStatus').textContent=t('online');render()}catch(e){$('registryStatus').textContent=t('offline');$('registryStatus').classList.add('offline');$('scriptsGrid').replaceChildren(elem('div','empty',t('offline')));console.error(e)}})();